### ISSUE TITLE
tars2c++优化建议

### ISSUE THREAD

**Issue by eagle518** [TarsCloud/Tars#107]
inline bool operator==(const FileInfo&l, const FileInfo&r)
    {
        return l.path == r.path && l.size == r.size && l.canExec == r.canExec && l.md5 == r.md5;
    }
    inline bool operator!=(const FileInfo&l, const FileInfo&r)
    {
        return !(l == r);
    }
缩短!=的比较路径，生成的代码建议改为：
inline bool operator==(const FileInfo&l, const FileInfo&r)
    {
        return !(l != r);
    }
    inline bool operator!=(const FileInfo&l, const FileInfo&r)
    {
       return l.path != r.path || l.size != r.size || l.canExec != r.canExec || l.md5 != r.md5;
    }

**Comment by helloopenworld** [comment]
这个建议挺好的，我们优化一下。
