### ISSUE TITLE
建议C++版本的tars编解码增加optional功能

### ISSUE THREAD

**Issue by chenzj** [TarsCloud/Tars#116]
目前tars协议是支持require和optional选项的。但是在C++实现时，optional选项实际上是不生效的（无法判断指定的字段是否是默认值还是没有设置），建议在实现中实现，有很多的场景需要optional选项。
具体实现方式建议：增加一个字段，表示协议中所有字段是否被设置了，该字段的每一位对应一个字段。
然后所有的字段修改为private， 采用set/get接口修改和获取，采用has接口判断是否存在该字段。

**Comment by loveyacper** [comment]
这是tars协议和protocol相比的一个区别或缺失，有时需要区别默认值和未设置。出于历史原因这块不大可能再改了。不过tars现在也支持了protocol buffers，你可以使用pb协议达到这个目的。

**Comment by chenzj** [comment]
但是使用pb协议的话，就不能支持直接用tars生成出相应的接口定义了吧

**Comment by jakyliu** [comment]
@chenzj 支持pb的同时，也增加了protoc的编译插件，支持pb到tars的接口定义生成，你可以试试。protoc ‐‐plugin=protoc-gen-tars-java=${plugin_path} 
--tars-java_out=${out_path} 
--java_out=${out_path} ${proto_path}
具体见 http://mp.weixin.qq.com/s/Hbv2Vh-Pyss0KffAmbTL_Q
