### ISSUE TITLE
NodeServer发布接口bug

### ISSUE THREAD

**Issue by XLILT** [TarsCloud/Tars#118]
我搭建环境测试发布功能，发现总是失败。后来追踪日志，定位到问题。具体位置为：
nodeserver/CommandPatch.h  line: 463
改动如下：
原文：    TC_File::copyFile(sLocalExtractPach + "/" + sServerName, _serverObjectPtr->getExePath(), true);
修改为：TC_File::copyFile(sLocalExtractPach + "/" + sServerName, _serverObjectPtr->getExeFile(), true);

我做出该修改后重编，发布功能正常。

另外提个意见。
你们的安装教程虽然步骤很详细，不过在nodeserver节点的部署上面有些模糊。在不清楚你们的架构和目录结构之前，nodeserver部署困难。希望能自动生成nodeserver的模板配置和脚本。

最后提个问题。
nodeserver不可以被web系统管理起来吗，如果可以是直接加到Tars应用下面吗？

**Comment by helloopenworld** [comment]
谢谢反馈，CommandPatch.h的问题我们核实一下。
nodeserver的部署再优化一下。
