### ISSUE TITLE
能否使用.NET 或者 NETCore来使用这个库？

### ISSUE THREAD

**Issue by NMSAzulX** [TarsCloud/Tars#121]
这个库看起来很棒，但是我们很多基于.NET Core的业务，能否提供一个Core版本的？

**Comment by yangyulin007** [comment]
支持支持！

**Comment by leegkon** [comment]
强烈要求支持dotnet core

**Comment by DivenK** [comment]
强烈要求支持dotnet core

**Comment by 690486439** [comment]
强烈要求支持dotnet core

**Comment by windsOne** [comment]
强烈支持 dotnet core

**Comment by cky421** [comment]
强烈支持 dotnet core

**Comment by burebure** [comment]
强烈支持 dotnet core

**Comment by jeanary** [comment]
强烈支持 dotnet core

**Comment by nicktse8899** [comment]
强烈支持 dotnet core

**Comment by Damon-Liu** [comment]
能否使用dotnet core来支持这个，我们很多项目都是使用的dotnet做的，难道以后dotnet真的要在中国消失了么

**Comment by lison666** [comment]
强烈支持 dotnet core

**Comment by zhuyu19911016** [comment]
强烈支持 dotnet core

**Comment by Debuggerliu** [comment]
顶

**Comment by jiangdaxia** [comment]
建议支持dotnetcore

**Comment by HeinoLee** [comment]
支持 dotnet Core

**Comment by guodf** [comment]
最期待的莫过.Net Core的一抹红晕为Tars化成的那一抹红印

**Comment by WayneShao** [comment]
I am looking forward it.

**Comment by a280238558** [comment]
强烈支持 dotnet core

**Comment by yuefengkai** [comment]
强烈支持 dotnet core

**Comment by MingqiSs** [comment]
强烈要求支持dotnet core

**Comment by pidanwl** [comment]
建议支持dotnetcore

**Comment by mopetite** [comment]
强烈要求支持dotnet core

**Comment by ShiWei-L** [comment]
.net core天生跨平台并且高性能，采用中间件模式。使用C#进行开发具有非常高的效率，希望支持.net core

**Comment by onlymisaky** [comment]
顶上去

**Comment by yunfeiyang1916** [comment]
来支持.net core。

**Comment by Jnskerry** [comment]
强烈支持.net core

**Comment by liuyl1992** [comment]
能快速支持.net core吗,还不支持这么高效率的平台真是遗憾

**Comment by guozhigao** [comment]
顶顶顶

**Comment by alvis-lee** [comment]
强烈支持 dotnet core

**Comment by cnblogsTim** [comment]
强烈支持 dotnet core

**Comment by abcba** [comment]
强烈要求支持 dotnet core

**Comment by crybigsea** [comment]
希望能提供.net core版本

**Comment by zlzforever** [comment]
希望能提供.net core版本

**Comment by hylx2013** [comment]
强烈要求支持dotnet core

**Comment by marklightning** [comment]
有 .NET 或者 NETCore 需求的扫码进微信群沟通
![img_5611](https://user-images.githubusercontent.com/29880465/33250332-d3ec0b94-d36a-11e7-80c5-75889d6c7c41.JPG)

**Comment by fs7744** [comment]
写了个简单的dotnet core 版 tars  实现  (tars协议等均未完善，仅能简单的 hello world) 
https://github.com/fs7744/Tars.Csharp
希望能做个抛砖引玉，与大家一起讨论 tars c# 版 如何做？各部分如何设计

**Comment by fs7744** [comment]
hi, all
Tars.Csharp 已经针对 rpc调用，tars协议解析 做了简单支持
希望各位大佬能对这部分做些建议，比如处理缺失啊，写法考虑不全啊，等等， 
鄙人感激不尽，毕竟我对 tars 不够熟悉，都是边了解边尝试写
后续会逐渐尝试写tars 配置，负载均衡等功能部分

**Comment by ShiWei-L** [comment]
@fs7744 加油兄弟

**Comment by marklightning** [comment]
![tars_netcore_barcode](https://user-images.githubusercontent.com/29880465/34819751-9fc81f08-f6f9-11e7-9a0e-bd4367ab23e4.jpg)
update netcore wechat barcode

**Comment by TCZWJ** [comment]
希望能提供.net core版本

**Comment by feishu** [comment]
希望官方支持呀

**Comment by geffzhang** [comment]
https://github.com/tarsnet 已经开始支持C#的开发工作

**Comment by wukai1211** [comment]
官方可以报一下进度不？？？

**Comment by chenbigit** [comment]
强烈要求支持dotnet core

**Comment by robyle** [comment]
.net core天生跨平台并且高性能，采用中间件模式。使用C#进行开发具有非常高的效率，希望支持.net core，少了它就等于少了一半的开发者拥护。

**Comment by aioloswong** [comment]
强烈要求支持.NET Core，.NET  Core跨平台，性能高，模块化设计 ，支持Docker，用C#开发，考法效率也高。官方能公布.NET Core的开发计划吗？
