### ISSUE TITLE
MySQL主备，是指一主一从，主从同步。在master不可服务的时候才启用slave吗？

### ISSUE THREAD

**Issue by u203** [TarsCloud/Tars#130]
MySQL主备，是指一主一从，主从同步。在master不可服务的时候才启用slave吗？

**Comment by loveyacper** [comment]
这里的主从同步主要是为了数据的可靠性，并不是为了failover。

**Comment by u203** [comment]
请问从库在什么时候被启用？

**Comment by yuansx** [comment]
这个主备mysql，主要还是mysql的应用，百度上很多资料会有相关的mysql主备原理的
