### ISSUE TITLE
异常上报，自定义的异常不能正常上报，不管上报什么异常，都只显示  tars.viewstatus

### ISSUE THREAD

**Issue by Zereao** [TarsCloud/Tars#148]
异常上报时，`NotifyHelper.getInstance().notifyError("ssssssss"); `  ， 该语句不能正常上报 自定义的异常信息"ssssssss"，Web管理平台输出的信息永远是“tars.viewstatus” ； 
同时，`NotifyHelper.getInstance().asyncReport("startSS");`  ，该语句能够正常上报情况，并且能在管理平台正常显示。

**Comment by yuansx** [comment]
找不到这个NotifyHelper哦
