### ISSUE TITLE
开启协程情况下，染色信息是否会丢失？

### ISSUE THREAD

**Issue by chenzj** [TarsCloud/Tars#156]
https://github.com/Tencent/Tars/blob/7cd7a863f4f8aed48858add64d87f36a738336d2/cpp/servant/libservant/ServantProxy.cpp#L215
https://github.com/Tencent/Tars/blob/7cd7a863f4f8aed48858add64d87f36a738336d2/cpp/servant/libservant/ServantProxy.cpp#L644

这里开启协程情况下，染色信息是否会丢失？

**Comment by loveyacper** [comment]
不会。

**Comment by chenzj** [comment]
这里，协程切出去后，当前线程会处理下一个任务。
假如任务1是被染色的，其线程私有数据中，染色信息是被染色；
当协程切出去后，处理任务2，而任务2是不染色的；这是其线程私有数据会被值为不染色；
等到任务1处理完后，协程切回来，这个时候，线程私有数据中的染色信息依然是不染色

这个时候，任务1后续的处理就都是不染色了，染色信息丢失

**Comment by loveyacper** [comment]
你说的是对的，协程方式调用时，染色信息可能会丢失。

**Comment by berli** [comment]
@chenzj  这个就是线程私有数据在携程来回切换后没有现场保护引起的，受此影响有：染色日志，采样数据，灰度路由功能都会被覆盖；目前正在解决这个bug
