### ISSUE TITLE
节点服务器上只需要tarsnode就可以吗

### ISSUE THREAD

**Issue by jiahemei** [TarsCloud/Tars#158]
请问，节点服务器上安装tarsnode就可以了吗？

java、php、nodejs运行环境，是根据发布的服务自动配置运行环境吗？

谢谢

**Comment by bobzhangyong** [comment]
tarsnode 是负责和tar通讯的， 如果你的节点服务器上需要部署 php的应用，你需要自己在节点服务器上安装 php， 如果跑nodejs 需要自己安装nodejs， 运行环境tarsnode 不会帮忙自动初始化，tarsnode 可以帮你下发一些配置文件

**Comment by jiahemei** [comment]
节点服务器上只需要一个tarsnode服务就够了吗？

1. 手工部署的核心基础服务：tarsAdminRegistry, tarsregistry, tarsnode, tarsconfig, tarspatch
2. 通过管理平台部署的普通基础服务：tarsstat, tarsproperty,tarsnotify, tarslog，tarsquerystat，tarsqueryproperty

这两部分，那几个服务是要部署到节点上？

**Comment by loveyacper** [comment]
在业务节点上部署的只有tarsnode节点是必须的，tarsnode负责业务发布、进程状态监控、管理命令透传等功能。
