### ISSUE TITLE
Tars中jce协议require字段的必要性？

### ISSUE THREAD

**Issue by txlstars** [TarsCloud/Tars#163]
require字段的意义在哪里？统一按照optional这种方式处理不是更好吗？

**Comment by loveyacper** [comment]
历史原因吧。其实protobuf2不也是有required，也是在protobuf3之后，才开始推荐全部optional

**Comment by medns** [comment]
我认为 IDL 定义并不一定是为了计算机编解码方便，其中更重要的是面对人类是有好的，可以直接从 IDL 定义中获知字段属性。要不直接用 JSON 不是更方便？

**Comment by ysbbswork** [comment]
> require字段的意义在哪里？统一按照optional这种方式处理不是更好吗？

有时候给你个接口，和相应的协议，请求体的字段又很多，又没有文档（可能是很老的接口）require和optional能让你很快知道哪些是字段是必须要填的，哪些是选填的，接口的使用一目了然。
虽然现在为了避免麻烦大家都使用optional，但是对于后来的人阅读并不友好。
