### ISSUE TITLE
C++代码中，关于的Message.h中ReqMessage结构体的疑问

### ISSUE THREAD

**Issue by dwxiayi** [TarsCloud/Tars#165]
发送、回应的消息定义为：
    RequestPacket               request;        //请求消息体
    ResponsePacket              response;       //响应消息体
而非指针，因此在消息的线程间传递时会发生很多次的拷贝构造，这种情况在作为client访问服务时尤为严重，当高并发或者消息较大时会产生很多的性能影响。
例如：
     发请求时，函数 ServantProxy::tars_invoke中 
          msg->request.sBuffer      = buf;
          作为同步回应时当前上下文会被挂起或者协程切换，使用原来的buf是安全的

    处理回应时：
        CommunicatorEpoll::handleInputImp函数中pTransceiver->doResponse(done)中解包,tarsResponseLen函数push_back会发生拷贝构造
        AdapterProxy::finishInvoke(ResponsePacket & rsp)中 msg->response = rsp;同样会发送拷贝

因此，我觉得将上述数据的传递方式定义为指针，实际数据放在堆区会有更好的性能。

**Comment by loveyacper** [comment]
针对你举得例子简单说下：
**1.msg->request.sBuffer = buf;**  
这里其实可以使用string的swap方法，或者C++11的std::move解决拷贝；（遗憾的是历史原因使用了vector<char>类型做缓存和string不匹配；未来考虑升到C++11）

**2.tarsResponseLen函数push_back会发生拷贝构造**
同样的，C++11的   done.emplace_back(std::move(rsp));完美解决拷贝

3.msg->response = rsp;
由于参数是引用，使用swap方法可以解决。

当然，需要对tars代码生成工具做修改，以支持swap和C++11的move构造。

**Comment by dwxiayi** [comment]
github上的代码你们是否考虑修改？
据我所知C++11引入类似fork的写时复制机制，所以这点应该影响不大。
我们服务的客户中大量都是使用gcc4.3的用户，所以很纠结
ps：请原理我的强迫症。
