### ISSUE TITLE
[Java]使用maven-assembly-plugin打包后无法启动

### ISSUE THREAD

**Issue by hank-whu** [TarsCloud/Tars#166]
AppContainer中对资源文件的访问有问题:
> context = new XmlAppContext(new File(servantXML.toURI()));

ConfigurationManager中对资源文件的访问有问题:
> ServerConfig cfg = new ServerConfig().load(Config.parseFile(System.getProperty("config")));

不要使用File来操作资源文件，使用Resource获取InputStream的方式来访问.

**Comment by LawlietLi** [comment]
访问文件内容时都会构造成FileInputStream的

**Comment by hank-whu** [comment]
使用maven-assembly-plugin打包后，servantXML是被打包到jar中的。
new File(servantXML.toURI()) 是找不到的，然后就报错了。

**Comment by hank-whu** [comment]
```java
//正确的使用方式：
InputStream inputStream = Test.class.getClassLoader.getResourceAsStream("xxx.xml");
```

**Comment by LawlietLi** [comment]
明白你的意思了，tars在通常情况下打成war包发布，一般不存在这个问题，不过这里可以修改一下

**Comment by hank-whu** [comment]
@LawlietLi 请在maven中央仓库发布一下你们的最新版本

**Comment by zengjieyu** [comment]
发版了？

> @LawlietLi 请在maven中央仓库发布一下你们的最新版本
