### ISSUE TITLE
有提供go语言支持的计划么？

### ISSUE THREAD

**Issue by tangramor** [TarsCloud/Tars#167]
C++的学习曲线对不少人来说陡峭了点，我们不少同事有学习go语言的想法

**Comment by maplebeats** [comment]
golang已经在内部支持了，正在更多的业务上进行测试验证，上半年应该就会放出来，感谢支持:D

**Comment by breath-co2** [comment]
上半年还剩5天...

**Comment by maplebeats** [comment]
计划听说调整到下半年了，毕竟新东西，大规模验证比较久。

**Comment by sandyskies** [comment]
@tangramor  差不多这两月

**Comment by maplebeats** [comment]
这个issues可以关掉了，哈哈

**Comment by sandyskies** [comment]
https://github.com/TarsCloud/TarsGo
