### ISSUE TITLE
tars接口一直获取不了spring容器里的bean

### ISSUE THREAD

**Issue by jaryun** [TarsCloud/Tars#17]
我这边一直获取不到，我看了日志，spring初始化的时候都是正常完成了，初始化完成后也能取到我设置内容，但通过tars接口就取不到了。请问通过tars接口能取到spring容器的bean吗。
@Servant
public interface TestServant {
	public String request(String requestXml);
}

public class TestServantImpl implements TestServant {

	private ServiceUtils serviceUtils;

	private String test;
	public String request(String requestXml) {
		if (serviceUtils == null) {
			return "serviceUtils is null";
		} else {
			try {
				return serviceUtils.doInvoke(requestXml);
			} catch (Exception e) {
				return "exception";
			}
		}
	}

	public ServiceUtils getServiceUtils() {
		return serviceUtils;
	}

	public void setServiceUtils(ServiceUtils serviceUtils) {
		this.serviceUtils = serviceUtils;
	}

	public void init() {
		System.out.println("---------init servant----------");
		System.out.println("---------"+test+"----------");
		if(serviceUtils==null){
			System.out.println("---------serviceUtils is null----------");
		}else{
			System.out.println("---------serviceUtils is not null----------");
		}
	}

	public String getTest() {
		return test;
	}

	public void setTest(String test) {
		this.test = test;
	}
}

	<bean name="serviceUtils" class="com.rzt.business.atom.util.ServiceUtils">
		<property name="genericService" ref="genericService"></property>
	</bean>
	<bean name="testServantImpl" class="com.server.test.impl.TestServantImpl"  init-method="init">
		<property name="serviceUtils" ref="serviceUtils"></property>
		<property name="test" value="dddd"></property>
	</bean>

下面是spring初始化时的部分日志，这里说明spring已经实例化了serviceUtils，但接口调用的时候serviceUtils 就为空了：
     [LOG] [SYSTEM] [目录[commonConf]无可用的commonParam配置文件]
---------init servant----------
---------dddd----------
---------**serviceUtils is not null**----------
四月 17, 2017 4:37:30 下午 org.apache.catalina.util.SessionIdGeneratorBase createSecureRandom

调用tars接口后返回的结果：
INFO tars-log | set tars-log default level=INFO
INFO tars-log | try to set tars-log.root from java system property (server.root)
INFO tars-log | set tars-log defaultRoot=\log\
**serviceUtils is null**

**Comment by besthaos** [comment]
目前tars java框架内部没有使用spring，框架加载的TestServantImpl并不是你在spring中配置的那个对象
