### ISSUE TITLE
在Debian系环境运行create_tars_server.sh时报错

### ISSUE THREAD

**Issue by tangramor** [TarsCloud/Tars#180]
是perl工具rename报的：`Bareword "DemoServer" not allowed while "strict subs" in use at (user-supplied code).`

我已经提交了 PR：https://github.com/Tencent/Tars/pull/179

**Comment by loveyacper** [comment]
perl->shell?   shell语法确实略有差异，待验证后merge

**Comment by tangramor** [comment]
create_tars_server.sh 里面使用了rename，这是个perl写的系统工具，在debian上运行时就报了上面的错误

**Comment by tangramor** [comment]
刚刚修改了PR https://github.com/Tencent/Tars/pull/179 ，把不同rename命令的判断方式从OS方式改成来源包的方式，应该可以适应各种不同的Linux发行版
