### ISSUE TITLE
jce生成的cpp代码中的类的display方法的问题

### ISSUE THREAD

**Issue by tsingakbar** [TarsCloud/Tars#193]
目前没有重载来显示`vector<byte>`类型的成员，当字符串直接来显示的，直接导致乱码，并且这个成员后面的成员就显示不了了。

**Comment by helloopenworld** [comment]
vector<byte>的数据本身是二进制的数据，不太适合用生成代码的display方法显示，另外代码生成的类目前是不建议去重载其中的方法。

建议：
对于有vector<char>成员的结构体，如果想打印出其中的内容，建议根据业务自身的需求实现打印struct包含vector<char>成员变量的方法，方便内容的查看

如果不想打印其中的内容，对于vector<char>在display方法中使用导致的问题，后面的解决方案是只显示vector<char>简要信息来规避这个问题
