### ISSUE TITLE
能否上传性能测试样例代码并解读性能测试报告？

### ISSUE THREAD

**Issue by chenghanpeng** [TarsCloud/Tars#194]
从实现上看，CPP的实现提供更多特性，EPOLL ET，Coroutine特性。Java的实现使用的Java 原生的NIO，但是JDK中Selector的实现是基于EPOLL LT的。看到测试效果两者几乎没什么差异，似乎不太合理。能否上传测试代码供重现？
另外能否解释一下为什么CPP的实现和JAVA性能相近的原因？
最后，还有点好奇，当时为什么没考虑使用libevent，Netty等这样的框架？

**Comment by helloopenworld** [comment]
https://github.com/Tencent/Tars/tree/master/cpp/examples/StressDemo

**Comment by chenghanpeng** [comment]
多谢，我看对应的CPP和Java版本。
能否解读一下你们提供的性能报告？设计和实现差异挺大的，为何两者性能如此接近？
