### ISSUE TITLE
应用名称大小写问题

### ISSUE THREAD

**Issue by mountkin** [TarsCloud/Tars#207]
通过web界面创建两个应用: `TestAPP`和`TestApp` （手误，不是故意的 :innocent:）
然后发现客户端连接时是区分大小写的，大小写不对会报错`ex:server servant mismatch exception: ret:-4`， 这应该是预期行为。
但web管理界面上显示就乱套了，看下图：
![tars](https://user-images.githubusercontent.com/1496652/40464726-721f5d8c-5f4f-11e8-9e1c-35b099cd70b2.png)

**Comment by mountkin** [comment]
比较悲剧的是把其中的一个应用下线后，另外一个也没了 :sob:

**Comment by wjx82850707** [comment]
看界面是老版本的管理平台，老版本的管理平台已经不升级了，不过新版本管理平台也有这个问题，已经在排期优化中，请关注版本的更新。
