### ISSUE TITLE
PHP http 服务 无法 下发 服务配置.

### ISSUE THREAD

**Issue by xcwen** [TarsCloud/Tars#216]
下发 服务配置.功能  看起来是基于 tas 协议的.

**Comment by meijing0114** [comment]
由于swoole本身的实现，对于http服务，端口只接受http协议的请求，非http协议返回bad request。但是tars平台默认将同一端口绑定为管理端口，导致这一问题较难解决。需要与swoole开发者共同解决这个问题。

**Comment by xcwen** [comment]
谢谢:>
