### ISSUE TITLE
RegistryServer可以做分布式部署吗？

### ISSUE THREAD

**Issue by double2li** [TarsCloud/Tars#221]
RegistryServer可以做分布式部署吗？如果只有单点服务器肯定有性能瓶颈

**Comment by loveyacper** [comment]
完全可以的
这样业务配置中locator项后面就是多个tcp地址了

**Comment by xcwen** [comment]
问题是怎么部署, 有文档吗:>

**Comment by yuansx** [comment]
直接部署，配置中数据库指向同一个地址就行了
