### ISSUE TITLE
registry服务能否提供集群内、外两个IP

### ISSUE THREAD

**Issue by tangramor** [TarsCloud/Tars#223]
部署在集群内的registry服务，返回的会是集群内部网络IP，但如果集群外部调用registry服务，返回的还是内部IP，但集群通常只会通过开放端口映射的方式来对集群外部提供服务，所以IP会不同

一种方案是加一个API网关，实现对集群内部IP的转换；
一种是registry本身就可以提供外部IP选项

**Comment by yuansx** [comment]
对于做了nat的网络，目前是存在这种问题，暂时还没有解决
