### ISSUE TITLE
tars服务网关的解决方案

### ISSUE THREAD

**Issue by huangzz** [TarsCloud/Tars#234]
tars好像没有提供服务网关的解决方案。一般服务网关会提供统一的服务接入、协议适配（前端http后端rpc）、流量管控和安全防护。tars对这一块是怎么考虑的？有没有建议，比如接入Kong，zuul等服务网关方案

**Comment by cygsxak** [comment]
自己使用Nginx或者Kong（其实还是NG）配置。
