### ISSUE TITLE
TARS parser version1.0.1到1.1.0

### ISSUE THREAD

**Issue by flyying-fish** [TarsCloud/Tars#236]
TARS parser自动生成代码的version1.0.1到1.1.0有什么变化吗？开发中项目出现版本不同一定要升级？

**Comment by flyying-fish** [comment]
补充一下，主要是tars2node的版本问题如何平滑升级呢？

**Comment by ziyang314** [comment]
升级主要是修复一些bug，所以最好是升级。如果你使用过程中没发现什么问题也可选择不升级
