### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [TarsCloud/Tars#244]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [AsyncProcThread](https://github.com/Tencent/Tars/blob/a8813bfd38e121e38930a5191941e6a293b80e13/cpp/servant/libservant/AsyncProcThread.cpp#L31 "Destructor for AsyncProcThread")
- [TC_Epoller::create](https://github.com/Tencent/Tars/blob/a8813bfd38e121e38930a5191941e6a293b80e13/cpp/util/src/tc_epoller.cpp#L61 "TC_Epoller::create function")
- [TC_ThreadPool::destructor](https://github.com/Tencent/Tars/blob/ecc53c594f8a3e290dd041e071ded08e024fcddc/cpp/util/src/tc_thread_pool.cpp#L81 "TC_ThreadPool::destructor function")

**Comment by loveyacper** [comment]
Thanks for your advice.
Yes, delete null pointer is fine.

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by yuansx** [comment]
You can use clang-tidy to check and standardize your source code.
