### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [TarsCloud/Tars#245]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [TC_LoopQueue constructor](https://github.com/Tencent/Tars/blob/a8813bfd38e121e38930a5191941e6a293b80e13/cpp/util/include/util/tc_loop_queue.h#L42)
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex") ⇒ [TC_ThreadMutex constructor](https://github.com/Tencent/Tars/blob/a8813bfd38e121e38930a5191941e6a293b80e13/cpp/util/src/tc_thread_mutex.cpp#L25)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string") ⇒ [Activator::activate](https://github.com/Tencent/Tars/blob/d0e67977a82705860075d4352f2c089db6b64deb/cpp/framework/NodeServer/Activator.cpp#L24)

**Comment by loveyacper** [comment]
Out of memory should not be concerned.
But call to pthread_mutex_init() should be checked.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by yuansx** [comment]
Out of memory should not be concerned.
pthread_mutex_init() is already processed.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
