### ISSUE TITLE
怎么支持springboot呢？

### ISSUE THREAD

**Issue by ishgy** [TarsCloud/Tars#248]
可以提供一个支持springboot的文档吗，公司准备采用springboot进行开发，thx

**Comment by LawlietLi** [comment]
目前支持使用spring的xml进行配置，spring boot集成版正在开发中

**Comment by SWTHongbin** [comment]
现在解决了吗？

**Comment by knfcn** [comment]
https://github.com/TarsCloud/TarsJava/blob/master/docs/tars_java_spring_boot.md
