### ISSUE TITLE
Does the team have the plan to transfer the project to C++11 or a higher standard?

### ISSUE THREAD

**Issue by goldhillpaladin** [TarsCloud/Tars#257]
请问你们有计划把项目迁移到C++11标准吗？

**Comment by goldhillpaladin** [comment]
另外，QQ群满了，有办法加进去吗？

**Comment by loveyacper** [comment]
Yes， tars cpp required gcc 4.8 or above.
QQ group code: 669339903

**Comment by goldhillpaladin** [comment]
So, we can use C++11 in taf in the future, too?

**Comment by loveyacper** [comment]
C++11 or above is prefered.
