### ISSUE TITLE
spring cloud 集成tars启动报错

### ISSUE THREAD

**Issue by gitzkm** [TarsCloud/Tars#276]
### What language are you using?
 
 java 
### What operating system (Linux, Ubuntu, …) and version?
 
 win10
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 jdk8
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
按照tars_java_spring_cloud.md中的步骤，集成tars 到springcloud。server能启动，并能在eureka发现服务。client启动报错，报错如图
![image](https://user-images.githubusercontent.com/9098704/43115349-226b0e5a-8f36-11e8-9531-2ccba56d2461.png)
![image](https://user-images.githubusercontent.com/9098704/43115407-57bacf28-8f36-11e8-8040-578e3e64321e.png)

求大神指导

**Comment by TOKISAKIKURUMI** [comment]
你好，能贴出一下你的使用代码和配置文件吗
