### ISSUE TITLE
加快推出.net core版本。

### ISSUE THREAD

**Issue by codeex** [TarsCloud/Tars#286]
需要需要！

**Comment by chenzuo** [comment]
请问作者什么时间能推出这个版本。

**Comment by wadnm** [comment]
希望作者能早日加入dotnet core版本，期待期待！

**Comment by Shinetaku** [comment]
rpc最核心的就是跨平台，连跨平台都做不好。让人怎么用？thrift,grpc哪个netcore用不了？鹅厂最后一点.net都没了么。怪不得整个windows应用商店就没几个鹅厂的应用。

**Comment by nxtreaming** [comment]
.NET 在开源行业属于最末等公民，不受重视是合情合理的，你自己选错了平台，怪自己眼瞎，不要责怪别人不支持。

**Comment by Shinetaku** [comment]
@nxtreaming 呵呵。我没啥意见啊，你开心就好了。反正跨语言跨平台的多了去了。Spring.Cloud都能接入Netcore了、Rabbbit.RPC也能凑活用。心态轻松点。没人砸你饭碗。

**Comment by nxtreaming** [comment]
@Shinetaku 砸饭碗之说从何而来？
大公司也要考虑成本，如果.net用的人多，自然会考虑出.net的版本，不要瞎举例子，在开源行业最基本的礼仪是不要强迫别人实现你的需求，更不要因为别人没有实现你的需求你就去说人家风凉话。

**Comment by Shinetaku** [comment]
@nxtreaming 这项目不是商用？那为什么配置页面只接受腾讯云主机？阿里的Dubbo也没要求必须阿里云吧。
没人逼你必须实现需求，我们有.net core的开发，也有java的开发，各做各的微服务，用spring.cloud统一入口，内部rpc通讯下，有何问题？非要用一种语言统一，我们把.netcore开发都辞退就ok？
上面一堆人在要求支持netcore，视而不见，非要拿语言、开源这些东西扣帽子。
微软怎么了，微软还是GitHub最大的开源贡献者。net core也是开源的。.net再渣，开发者人数也不会出前5。受不受欢迎，好不好用自然有人去评价。
问题页好几页的问题不去close，在这扯语言问题。

呵呵，你开心就好。顺便说下，听说你们鹅厂.net core大拿老张都被逼无奈辞职了。真是大厂作风啊。

**Comment by ElderJames** [comment]
#121 在做了

**Comment by geffzhang** [comment]
.netcore的支持已经在做了，9.8 活动我介绍总体情况。
@Shinetaku 不要在这里造谣，我辞职创业绝对不是无奈辞职，我和腾讯合作非常好，而且这个.netcore的支持工作是我在主导，大家可以关注https://github.com/tarsnet

**Comment by Shinetaku** [comment]
@geffzhang 我道歉，确实是我不太了解情况，从朋友那里听说你离职了。就有些武断了。
@nxtreaming 有没人教过你开源行业的礼仪里包含尊重别人的选择这一条？无论选.net的是眼瞎，选错平台也好，还是别的原因也好，请尊重下。大家的反馈你可以忽视，但请勿人身攻击。
语言本身没有高低之分，无论是高级语言还是低级语言都有其存在的价值，做java的鄙视做.net的。这本身就是一件可笑的事。开源并不是把代码公开出来就叫开源，而是一种精神一种态度，开放包容共享。

**Comment by farway000** [comment]
看到脑残在这里黑Tars,黑.net core，黑张队长，莫名其妙。傻逼到处都惹人厌。

**Comment by h0730303779** [comment]
> .NET 在开源行业属于最末等公民，不受重视是合情合理的，你自己选错了平台，怪自己眼瞎，不要责怪别人不支持。

这脸丢到全世界去了

**Comment by ShyUncle** [comment]
> .NET 在开源行业属于最末等公民，不受重视是合情合理的，你自己选错了平台，怪自己眼瞎，不要责怪别人不支持。
egg 疼，我选择unsubscribe
