### ISSUE TITLE
[Imrpovement] Replace StringBuffer with Stringbuilder, it does not need to be synchronized

### ISSUE THREAD

**Issue by TimmyYu** [TarsCloud/Tars#287]
### What language are you using?
 
JAVA
 
### What operating system (Linux, Ubuntu, …) and version?
 
LINUX
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
JDK1.8
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

Stringbuffer needs to be used when thread synchronization, there will be synchronization consumption, StringBuilder will be more efficient than StirngBuffer

**Comment by LawlietLi** [comment]
already merged
