### ISSUE TITLE
[Improve] Reactor Pattern  is not normalized

### ISSUE THREAD

**Issue by house0128** [TarsCloud/Tars#289]
hi,    
I find something is not right in tars.In reactor pattern,we use one reactor to accept SelectionKey.OP_ACCEPT,and some reactors to accept SelectionKey.OP_READ.  

In tars,SelectorManager  contains  array of reactor,use  array[0] to accept SelectionKey.OP_ACCEPT.
`selectorManager.getReactor(0).registerChannel(serverChannel, SelectionKey.OP_ACCEPT);`
      And others to accept SelectionKey.OP_READ.  
`selectorManager.nextReactor().registerChannel(channel, SelectionKey.OP_READ, session);`
 But not exluced array[0],so the array[0]  accept both SelectionKey.OP_ACCEPT and SelectionKey.OP_READ.  
    
   I think the nextReactor()  excluded  array[0]  is better.

**Comment by knfcn** [comment]
Thanks
on long connections,array[0] is long time idle, so make full use of all network threads
