### ISSUE TITLE
这个_statPropMsg可不可以换成unordered_map

### ISSUE THREAD

**Issue by tsingakbar** [TarsCloud/Tars#290]
https://github.com/Tencent/Tars/blob/fd96902da54970364e24609b1e4f601d3204394b/cpp/servant/servant/StatReport.h#L202
因为项目里面实际的上报，往往是封装成了宏比如
```cpp
#define REPORT_PROPERTY(property) { \
  StatReport *p = Application::getCommunicator()->getStatReport(); \
  PropertyReportPtr proRepo = p->createPropertyReport(property, PropertyReport::count()); \
  proRepo->report(1); \
}
```
REPORT_PROPERTY("prop1")，这里面每次都会调用createPropertyReport来生成一个上报对象，然后就发现这里的map.find就成了个小的代码热点……
之所以之前的开发封装这个宏，主要是为了应对REPORT_PROPERTY("prefix"+var)这种上报吧，事先创建好上报对象然后复用对象太麻烦

**Comment by tsingakbar** [comment]
或者有什么好的调用方法可以分享下？

**Comment by loveyacper** [comment]
意思是使用unordermap代替map以提高查找效率么？

**Comment by tsingakbar** [comment]
@loveyacper 这个不赖tars，但是tars提供的上报接口忒麻烦了，实际项目里面都是像我上面贴的代码那样封装的。但是一旦进程里面要上报的key比较多，每次加全局锁查找map就比较慢。
换成unordered_map只能说缓解一下，但是还是比较希望tars能给个更好点的接口。
