### ISSUE TITLE
Service log fail to export to log file

### ISSUE THREAD

**Issue by pstrike** [TarsCloud/Tars#294]
### What language are you using?
 Java
 
### What operating system (Linux, Ubuntu, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 jdk 1.8
 
### Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
In order to check service log, login tarsnode server, and check the log file in below path: /usr/local/app/tars/app_log/XXXApp/XXXService

However, in the log file, it indicate below err:
java redirect stdout and stderr  to /usr/local/app/tars/app_log//XXXApp/XXXService/XXXApp.XXXService.log
cannot execute java|errno=No such file or directory

Please notice, in above err msg, there are double slash in the path "/usr/local/app/tars/app_log//XXXApp/XXXService/XXXApp.XXXService.log". Not sure whether this is the cause. If so, how to config the log path?

**Comment by LawlietLi** [comment]
Double slash is same as one slash. Tarsnode will create this directory.

**Comment by knfcn** [comment]
restart tarsnode
