### ISSUE TITLE
tars在序列化这块可以用protobuf代替不？

### ISSUE THREAD

**Issue by cnzf1** [TarsCloud/Tars#295]
请问tars在序列化这块可以用protobuf代替不？
如果不行的话，有没有较好的方式解决不同协议，相同场景结构的差异化问题？结构转换得头晕。。。

**Comment by loveyacper** [comment]
可以直接使用proto文件，不使用tars文件。 pb2tarscpp是protobuf的插件，protoc调用该插件，生成tars所需的rpc调用代码，但是序列化仍然使用的是protobuf。

**Comment by cnjeffliu** [comment]
@loveyacper 尝试了这种方式，需要通过pb写rpc接口，比较麻烦吧 ，因为我已经写了很多tars的结构文件了

**Comment by loveyacper** [comment]
对，这种方式是抛弃.tars文件，只使用proto文件。支持的pb的缘由如下，你应该看一下文档先：
“当你第一次接触tars的时候，你已经有不少业务采用了protobuf协议；如果想要把这些业务迁移到tars，你还需要手动把proto文件翻译成tars文件,非常麻烦而且容易出错。 现在tars使用protoc的插件机制，提供了对proto文件的直接支持，能够生成tars rpc相关代码，使得迁移平滑省心”

**Comment by loveyacper** [comment]
pb2tarscpp是 protoc plugin，你不要手动调用，框架会自己调用它。2577247583 qq沟通

**Comment by EDDYCJY** [comment]
@cnjeffliu @loveyacper 您好，打扰一下。请问 pb2tarscpp 这一个 protoc plugin，是在哪里下载的呢？
我网上搜了一下没有找到。。。。

感谢

**Comment by loveyacper** [comment]
这插件代码就在tool下面的目录啊，是我写的，从网上肯定搜不到的

2018年9月30日星期日，煎鱼 <notifications@github.com> 写道：

**Comment by loveyacper** [comment]
> @loveyacper 很抱歉，我真的看了 https://github.com/TarsCloud/Tars 下并没有 tool 相关的目录？？？
> 能麻烦告诉我具体在哪里吗？

https://github.com/TarsCloud/TarsCpp/tree/717971e1cb77de16c06d01c824efd3a2d3c855db/tools/pb2tarscpp

**Comment by EDDYCJY** [comment]
@loveyacper 看到了，感谢。是我没找对具体语言的目录 😅

**Comment by scguang301** [comment]
没看到pb2tarsphp，有php的版本吗
