### ISSUE TITLE
monitorStat failed

### ISSUE THREAD

**Issue by qingzhong110** [TarsCloud/Tars#296]
### What language are you using?
 php
 
### What operating system (Linux, Ubuntu, …) and version?
 
 centos7
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 按照官方要求的版本
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
[root@tars-test client]# php index.php 
PHP Notice:  Undefined offset: -1 in /root/test/client/vendor/phptars/tars-monitor/src/client/CommunicatorMonitor.php on line 54
PHP Notice:  Undefined offset: -1 in /root/test/client/vendor/phptars/tars-monitor/src/client/CommunicatorMonitor.php on line 55
PHP Warning:  socket_connect(): Host lookup failed [-10003]: Unknown server error in /root/test/client/vendor/phptars/tars-monitor/src/client/CommunicatorMonitor.php on line 90
monitorStat failed
PHP Notice:  Undefined offset: -1 in /root/test/client/vendor/phptars/tars-monitor/src/client/CommunicatorMonitor.php on line 54
PHP Notice:  Undefined offset: -1 in /root/test/client/vendor/phptars/tars-monitor/src/client/CommunicatorMonitor.php on line 55
PHP Warning:  socket_connect(): Host lookup failed [-10003]: Unknown server error in /root/test/client/vendor/phptars/tars-monitor/src/client/CommunicatorMonitor.php on line 90
monitorStat failed
PHP Fatal error:  Uncaught Exception in /root/test/client/vendor/phptars/tars-monitor/src/client/CommunicatorMonitor.php:92
Stack trace:
#0 /root/test/client/vendor/phptars/tars-monitor/src/client/CommunicatorMonitor.php(61): Tars\monitor\client\CommunicatorMonitor->socketTcp(NULL, NULL, '\x00\x00\x00\xCD\x10\x03,<@\x01V\x15tar...', 2)
#1 /root/test/client/vendor/phptars/tars-monitor/src/StatFServant.php(49): Tars\monitor\client\CommunicatorMonitor->invoke(Object(Tars\monitor\client\RequestPacketMonitor), 2)
#2 /root/test/client/vendor/phptars/tars-monitor/src/StatFWrapper.php(231): Tars\monitor\StatFServant->reportMicMsg(Array, true)
#3 /root/test/client/vendor/phptars/tars-monitor/src/StatFWrapper.php(175): Tars\monitor\StatFWrapper->reportMicMsg(Array, true)
#4 /root/test/client/vendor/phptars/tars-client/src/Communicator.php(149): Tars\monitor\StatFWrapper->monitorStat('PHPTest.PHPServ...', 'sayHelloWorld', '172.16.100.108', 10005, 5, 0, 0)
#5 /root/test/client/PHPTest/PHPServer/obj/TestTafServiceServant.php(84): Tars\clie in /root/test/client/vendor/phptars/tars-monitor/src/client/CommunicatorMonitor.php on line 92

**Comment by meijing0114** [comment]
tars.tarsstat.StatObj 此基础服务是否已经存在？
