### ISSUE TITLE
tarsnode访问公共框架的验证和加密

### ISSUE THREAD

**Issue by hanwoody** [TarsCloud/Tars#297]
在多数据中心之间，tarsnode需要通过互联网访问公共框架，需要有：

- 连接建立时需要验证tarsnode是我自己的，而不是别人的节点
- 通讯需要加密，并不一定需要非常高强度的加密

**Comment by loveyacper** [comment]
目前tars cpp自带简单的账号密码验证，不知能否符合你的需求。
或者使用tars ssl连接来验证身份?

**Comment by hanwoody** [comment]
目前的tars node节点，连接框架时，有密码验证？是在模版里配置吗？

**Comment by lszChain** [comment]
https://github.com/TarsCloud/Tars/blob/master/docs/tars_auth.md
按照这个链接做好了配置，客户端仍然可以不用用户名和密码调用服务接口

**Comment by guzitajiu** [comment]
tars鉴权问题，现在暂时还不能用，我们正在加紧测试；
