### ISSUE TITLE
tars的web控制台访问登录

### ISSUE THREAD

**Issue by hanwoody** [TarsCloud/Tars#298]
tars的web控制台，需要一个简单的用户名和密码的验证登录，避免裸露到公网上。

**Comment by ipqbgsmile** [comment]
嗯 嗯 很有这个需求

**Comment by bobzhangyong** [comment]
#196

**Comment by hanwoody** [comment]
有个设想，能不能借着tars引入用户系统，直接支持了多租户？

- 支持创建多个用户，每个用户可以创建私有的key
- 每个用户用自己私有key配置到tarsnode，tarsnode使用该key做计算节点的接入认证
- 每个用户登录后，只看到自己的计算节点IP，和自己的应用

**Comment by wjx82850707** [comment]
已经在排期优化中，请关注版本的更新情况
