### ISSUE TITLE
web后台点击服务监控室core掉

### ISSUE THREAD

**Issue by ipqbgsmile** [TarsCloud/Tars#299]
core栈如下

(gdb) bt
#0  0x00007fe51c373277 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fe51c374968 in __GI_abort () at abort.c:90
#2  0x00007fe51c36c096 in __assert_fail_base (fmt=0x7fe51c4c7580 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x5ee341 "0", 
    file=file@entry=0x5e82d0 "/home/smile/Tars/cpp/framework/RegistryServer/DbHandle.cpp", line=line@entry=961, 
    function=function@entry=0x5e8fe0 <CDbHandle::loadIPPhysicalGroupInfo(bool)::__PRETTY_FUNCTION__> "int CDbHandle::loadIPPhysicalGroupInfo(bool)") at assert.c:92
#3  0x00007fe51c36c142 in __GI___assert_fail (assertion=0x5ee341 "0", file=0x5e82d0 "/home/smile/Tars/cpp/framework/RegistryServer/DbHandle.cpp", line=961, 
    function=0x5e8fe0 <CDbHandle::loadIPPhysicalGroupInfo(bool)::__PRETTY_FUNCTION__> "int CDbHandle::loadIPPhysicalGroupInfo(bool)") at assert.c:101
#4  0x00000000004839f7 in CDbHandle::loadIPPhysicalGroupInfo (this=this@entry=0xb34bd8 <g_app+376>, fromInit=fromInit@entry=true) at /home/smile/Tars/cpp/framework/RegistryServer/DbHandle.cpp:961
#5  0x0000000000484dec in CDbHandle::loadObjectIdCache (this=this@entry=0xb34bd8 <g_app+376>, bRecoverProtect=bRecoverProtect@entry=false, iRecoverProtectRate=30, iLoadTimeInterval=iLoadTimeInterval@entry=0, 
    bLoadAll=bLoadAll@entry=true, fromInit=fromInit@entry=true) at /home/smile/Tars/cpp/framework/RegistryServer/DbHandle.cpp:1116
#6  0x000000000049fd04 in ReapThread::init (this=this@entry=0xb34ad8 <g_app+120>) at /home/smile/Tars/cpp/framework/RegistryServer/ReapThread.cpp:80
#7  0x00000000004aaff0 in RegistryServer::initialize (this=0xb34a60 <g_app>) at /home/smile/Tars/cpp/framework/RegistryServer/RegistryServer.cpp:35
#8  0x000000000046847a in tars::Application::main (this=this@entry=0xb34a60 <g_app>, argc=argc@entry=2, argv=argv@entry=0x7ffcc9904738) at /home/smile/Tars/cpp/servant/libservant/Application.cpp:608
#9  0x0000000000467b66 in main (argc=2, argv=0x7ffcc9904738) at /home/smile/Tars/cpp/framework/RegistryServer/main.cpp:30

**Comment by loveyacper** [comment]
这个一般是访问mysql没有权限导致的，应该是忘记了grant语句。
