### ISSUE TITLE
访问 http://192.168.23.134:8080/ 报错。

### ISSUE THREAD

**Issue by iiCircle** [TarsCloud/Tars#302]
错误码:500
子错误码：
错误信息：Could not open JDBC Connection for transaction; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Communications link failure The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
URI:/
URL:http://192.168.23.134:8080/
Method:GET
Referer:

**Comment by yuansx** [comment]
这个是数据库权限配置不对，Install.md的数据库配置部分重新配置一下权限试试
