### ISSUE TITLE
为什么我的server一重启就停止了，突然出现的情况，错误日志也没有

### ISSUE THREAD

**Issue by isomophism** [TarsCloud/Tars#303]
2340 2018-09-05 15:48:08|9408|DEBUG|CommandStop.h:canExecute:61|Pifuyi.WrinkleDrawServer beging deactivate------|byRegistry|1
2341 2018-09-05 15:48:08|9408|DEBUG|CommandStop.h:canExecute:74|server state is Inactive.
2342 2018-09-05 15:48:08|9408|DEBUG|NodeImp.cpp:stopServer:445|stopServer [Pifuyi.WrinkleDrawServer] from 101.236.57.221 succ:server state      is Inactive.
2343 2018-09-05 15:48:09|9385|DEBUG|CommandStop.h:canExecute:61|Pifuyi.WrinkleDrawServer beging deactivate------|byRegistry|0
2344 2018-09-05 15:48:09|9385|DEBUG|CommandStop.h:execute:117|pid:46489
2345 2018-09-05 15:48:09|9385|DEBUG|CommandStop.h:execute:121|print the server status :/proc/46489/status|

是server没注册吗，可视我在页面上注册了啊

**Comment by lvxiaoqi** [comment]
我也遇到了同样的情况，你的是怎么解决的？
