### ISSUE TITLE
java 采用TUP2时不会生效

### ISSUE THREAD

**Issue by liamyue** [TarsCloud/Tars#307]
### What language are you using?
 
 java
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
不需要useVersion3 _newData不会为null 所以一直会采用version3
protected HashMap<String, byte[]> _newData = new HashMap<String, byte[]>();
 public void useVersion3() {
    _newData = new HashMap<String, byte[]>();
 }
public <T> void put(String name, T t) {
        if (null != _newData) {
            if (name == null) {
                throw new IllegalArgumentException("put key can not is null");
            }
            if (t == null) {
                throw new IllegalArgumentException("put value can not is null");
            }
            if (t instanceof Set) {
                throw new IllegalArgumentException("can not support Set");
            }
            TarsOutputStream _out = new TarsOutputStream();
            _out.setServerEncoding(encodeName);
            _out.write(t, 0);
            //tup2  parName value-byte[]
            byte[] _sBuffer = TarsUtil.getBufArray(_out.getByteBuffer());
            _newData.put(name, _sBuffer);
        } else {
            super.put(name, t);
        }
    }

**Comment by LawlietLi** [comment]
使用tup前，需要在生成服务端代码的插件配置中添加<tup>true</tup>配置，生成支持tup的服务端接口代码
