### ISSUE TITLE
java tars 服务状态异常

### ISSUE THREAD

**Issue by hgyue** [TarsCloud/Tars#308]
![132](https://user-images.githubusercontent.com/38428857/45295049-fb5bfc00-b52f-11e8-8546-d7f6bab674c9.png)
java tars 服务发布到管理平台后，点击服务名，不能查看服务状态，前端返回 1002（如图），C++服务是正常的！

**Comment by wjx82850707** [comment]
这种情况一般是node挂了，检查下node状态 。 

       //请求的node节点没有注册或者节点心跳超时
        EM_TARS_NODE_NOT_REGISTRY_ERR = 1001,
        //主控请求node节点超时
        EM_TARS_CALL_NODE_TIMEOUT_ERR = 1002,
        //从主控数据库获取服务的描述信息错误
        EM_TARS_LOAD_SERVICE_DESC_ERR = 1003,
        //服务可能处在停止或者发布过程中
        EM_TARS_SERVICE_STATE_ERR = 1004,
        //同样的请求已经在处理了
        EM_TARS_REQ_ALREADY_ERR = 1005,
        //请求来自非法的ip地址,如并非合法的主控地址
        EM_TARS_INVALID_IP_ERR = 1006,
        //参数错误
        EM_TARS_PARAMETER_ERR = 1007,
        //非tars方面的问题，用于node判断业务机器问题等
        EM_TARS_OTHER_ERR = 1008,
        //获取patch file异常
        EM_TARS_GET_PATCH_FILE_ERR = 1009,
        //调用patch server准备发布包失败
        EM_TARS_PREPARE_ERR = 1010,
        //未知错误
        EM_TARS_UNKNOWN_ERR = -1,
        //成功
        EM_TARS_SUCCESS = 0
