### ISSUE TITLE
tup组包协议有支持Dart语言的计划吗？

### ISSUE THREAD

**Issue by lengyue524** [TarsCloud/Tars#311]
服务端使用tas，手机端使用tup-oc和tup-java解包数据。
最近在研究flutter，准备引入flutter到项目中。
难在了tup组包这块。自己实现了一部分，但是越写发现坑越大。

**Comment by yuansx** [comment]
暂时没有这个计划哦

**Comment by PANZHIYONGpzy** [comment]
请问将来会有这个计划吗？因为flutter好像用得越来越多了。
