### ISSUE TITLE
执行tars_install.sh报错

### ISSUE THREAD

**Issue by wins1978** [TarsCloud/Tars#312]
ERROR|[TARS][CommunicatorEpoll::handleInputImp] connect error tcp -h 10.xxx.xxx.xxx -p 19386,tars.tarsnode.ServerObj,_connExcCnt=1,Connection refused

我IP都填写了，不知配置文件哪里出错（见附件）
[tars-conf.zip](https://github.com/TarsCloud/Tars/files/2404305/tars-conf.zip)

**Comment by yuansx** [comment]
意思是绑定ip 10.xxx.xxx.xxx 端口19386错了，你看下机器的ip是不是这个，另外netstat -tpln | grep 19386看下是不是其他进程占用了这个端口

**Comment by leeqx** [comment]
检查下mysql中的配置：db_tars.t_server_conf db_tars.t_adapter_conf 这两个表的中的node_name 是否是你本机的ip，如果不是，直接update以下就可以了（更新完之后，可能需要执行下/usr/local/app/tars/tars_install.sh)
