### ISSUE TITLE
tars-spring-cloud-starter 在client端使用注解@EnableTarsConfiguration引起冲突

### ISSUE THREAD

**Issue by wangkun001** [TarsCloud/Tars#313]
#### tars-spring-cloud-starter 在client端使用注解@EnableTarsConfiguration引起冲突
* 原因： 由于@EnableTarsConfiguration注解 @import导入TarsStartLifecycle类，在client端启动时加载TarsStartLifecycle执行configLogger()方法时报错：
```
  if (communicator == null || StringUtils.isEmpty(objName)) {
            System.out.println("ERROR tars-log | config error: locator and objName can't be empty.");
        }
```
* 错误： ERROR tars-log | config error: locator and objName can't be empty.

* 建议： 新添加一个client端注解@EnableTarsClientConfiguration，排除TarsStartLifecycle类，如下：
```
package com.qq.tars.spring.annotation;

import com.qq.tars.spring.TarsConfiguration;
import org.springframework.context.annotation.Import;

import java.lang.annotation.*;

@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Import({TarsConfiguration.class})
public @interface EnableTarsClientConfiguration {
}
```

**Comment by LawlietLi** [comment]
如果你只用客户端的话可以不用添加@EnableTarsConfiguration注解
