### ISSUE TITLE
Tars 是否有计划支持 Rust

### ISSUE THREAD

**Issue by zerolocusta** [TarsCloud/Tars#316]
已为 Tars 编写 Rust 版本二进制协议(tup/tars)解析模块，[tars-stream](https://github.com/zerolocusta/tars-stream)，官方是否有计划对 Rust 进行整体支持?

**Comment by yuansx** [comment]
目前不支持，需要看市场对这个的需求情况考虑是否纳入计划当中，感谢你的支持
