### ISSUE TITLE
spelling error

### ISSUE THREAD

**Issue by qinkan** [TarsCloud/Tars#318]
In https://github.com/TarsCloud/Tars/blob/master/build/install.sh file line 150：
sed -i "s/registry.tars.com/${MachineIp}/g" `grep registry1.tars.com -rl ./config/*`
it should be：
sed -i "s/registry.tars.com/${MachineIp}/g" `grep registry.tars.com -rl ./config/*`

**Comment by yuansx** [comment]
It has been fixed, thanks
