### ISSUE TITLE
目前感觉在docker集群部署，扩容方面还不太方便

### ISSUE THREAD

**Issue by we7team** [TarsCloud/Tars#325]
希望在docker集群部署中，节点容器可以根据环境变量中的服务名，自动发现，自动部署

**Comment by LeoYang90** [comment]
是啊，节点可以自动进行注册发现会方便很多

**Comment by yuansx** [comment]
目前正在做k8s方面的支持

**Comment by nustee** [comment]
目前单个集群能支持的最大节点数是多少啊，容器化以后，节点数量会急剧上升
