### ISSUE TITLE
安装开发环境的时候会报缺少数据库表

### ISSUE THREAD

**Issue by dolphinxwc** [TarsCloud/Tars#331]
跟着安装文档安装一个开发环境，用CentOS的操作系统，执行完exec-sql.sh后，系统会报错：
‘db_tars.t_server_notifys’ doesn't exist.进入数据库里面看db_tars数据库，确实没有这个表。

**Comment by yuansx** [comment]
发布一下tarsnotify这个服务就可以了，或者自己创建这个表，可参考这个issues
https://github.com/TarsCloud/Tars/issues/117

**Comment by edidada** [comment]
CREATE TABLE `t_server_notifys` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `application` varchar(128) DEFAULT '',
  `server_name` varchar(128) DEFAULT NULL,
  `container_name` varchar(128) DEFAULT '',
  `node_name` varchar(128) NOT NULL DEFAULT '',
  `set_name` varchar(16) DEFAULT NULL,
  `set_area` varchar(16) DEFAULT NULL,
  `set_group` varchar(16) DEFAULT NULL,
  `server_id` varchar(100) DEFAULT NULL,
  `thread_id` varchar(20) DEFAULT NULL,
  `command` varchar(50) DEFAULT NULL,
  `result` text,
  `notifytime` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_name` (`server_name`),
  KEY `servernoticetime_i_1` (`notifytime`),
  KEY `indx_1_server_id` (`server_id`),
  KEY `query_index` (`application`,`server_name`,`node_name`,`set_name`,`set_area`,`set_group`)
) ENGINE=InnoDB AUTO_INCREMENT=192 DEFAULT CHARSET=utf8;


--------------------- 
作者：youz1976 
来源：CSDN 
原文：https://blog.csdn.net/u014520797/article/details/83021083 
版权声明：本文为博主原创文章，转载请附上博文链接！

**Comment by yuansx** [comment]
谢谢贴出来，表的创建你可以从代码中找到的
