### ISSUE TITLE
安装开发环境过程中，缺少db_tars_web.t_tars_files数据表

### ISSUE THREAD

**Issue by dolphinxwc** [TarsCloud/Tars#332]
安装完Tars的组件，发现日志里面一直提示‘db_tars_web.t_tars_files’ doesn't exist.

**Comment by ypingcn** [comment]
https://github.com/TarsCloud/TarsWeb/blob/master/sql/db_tars_web.sql

**Comment by Andrew-M-C** [comment]
> https://github.com/TarsCloud/TarsWeb/blob/master/sql/db_tars_web.sql
> 请确认是否已经导入这个文件

  请问你说的 “导入” 是什么意思？在代码中 include？

**Comment by ypingcn** [comment]
> 
> 
> > https://github.com/TarsCloud/TarsWeb/blob/master/sql/db_tars_web.sql
> > 请确认是否已经导入这个文件
> 
> 请问你说的 “导入” 是什么意思？在代码中 include？

数据库执行这个文件，source 一下
