### ISSUE TITLE
tars 怎么和云的 docker 管理统一，服务发现上和 k8s 是否功能重叠

### ISSUE THREAD

**Issue by monkeycraps** [TarsCloud/Tars#333]
tars 怎么和云的 docker 管理统一，服务发现上和 k8s 是否功能重叠
有什么云上的使用建议么 ？

**Comment by yuansx** [comment]
确实是有重叠的部分，因为k8s开源出来前，tars已经开发了，不过我们内部已经在做k8s方面的支持了，敬请期待哦！！
