### ISSUE TITLE
Python 作为客户端销毁通信器的时候报错，如下图

### ISSUE THREAD

**Issue by smb111** [TarsCloud/Tars#336]

**Comment by smb111** [comment]
![error](https://user-images.githubusercontent.com/22951694/47471287-33976f80-d83c-11e8-8a59-d0272e6ce69e.png)

**Comment by smb111** [comment]
@loveyacper 老大帮忙解决一下~

**Comment by helloopenworld** [comment]
目前tup下面的tars python这块，建议先只使用协议这块，客户端和服务端通信这块还不够成熟，不建议继续使用，预计明天上半年我们会开源新的python语言的tars 开发框架，欢迎到时使用。
