### ISSUE TITLE
请问Tars的jce文件有Intellij IDEA的语法高亮插件么

### ISSUE THREAD

**Issue by duguying** [TarsCloud/Tars#340]
### What language are you using?
 go
 
### What operating system (Linux, Ubuntu, …) and version?
 linux
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 whatever
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**请问Tars的jce文件有Intellij IDEA的语法高亮插件么**

**Comment by sandyskies** [comment]
你好，我们建议使用vscode，vscode有tars文件或者jce文件的插件，可以高亮
