### ISSUE TITLE
我用的是java语言，tars服务是正常的，但是在调用的时候，经常报com.qq.tars.rpc.exc.ClientException: NetSign.SignServer.SignServerObj|server error code -1|  或者com.qq.tars.rpc.exc.ClientException: NetSign.SignServer.SignServerObj|server error code -99|，请问有类似的error code 说明文档可以查吗？

### ISSUE THREAD

**Issue by zhengfengliu** [TarsCloud/Tars#343]
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by TOKISAKIKURUMI** [comment]
好的，我们会补上
