### ISSUE TITLE
接口调试 提示内部系统错误

### ISSUE THREAD

**Issue by kanrin** [TarsCloud/Tars#346]
部署应用之后接口调试提示错误
使用的应用框架为go
示例的HelloGo

**Comment by kanrin** [comment]
![98f20516-1d43-467f-b501-267a744cbcb3](https://user-images.githubusercontent.com/9295961/48938094-1f35b800-ef4b-11e8-8a46-9c34ba5ba520.png)
***
进入接口调试 点击调试提示内部系统错误

**Comment by sandyskies** [comment]
其他语言是否有相同问题？

**Comment by kanrin** [comment]
其他语言目前没有试过，主要是其他语言也不熟悉⁄(⁄ ⁄ ⁄ω⁄ ⁄ ⁄)⁄，请查看下。

**Comment by ziyang314** [comment]
先上机器查看一下具体报错信息。pm2 logs --err
