### ISSUE TITLE
web管理系统安全性问题

### ISSUE THREAD

**Issue by xuhuan** [TarsCloud/Tars#35]
目前的web管理系统好像没用户体系吧，那安全方面通过什么方式来保障？

**Comment by marklightning** [comment]
目前是没有用户体系的，便于私有云统一权限管理，这个也便于使用者与自己的系统二次开发相结合。
另外，后续已经有考虑建立用户体系。

**Comment by marklightning** [comment]
@meiping 安排下版本更新的时间

**Comment by xuhuan** [comment]
@marklightning 有一个用户体系对于大部分用户来说基本就可以开箱即用，对于需要接入自己用户体系的也可以作为接入参考。
