### ISSUE TITLE
rsync 在tars中的作用是什么

### ISSUE THREAD

**Issue by leeqx** [TarsCloud/Tars#357]
### What language are you using?
 c++
 
### What operating system (Linux, Ubuntu, …) and version?
 
 centos
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
 gcc
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

### 问题（功能能咨询）：
tars 中发布版本时下载的包是tarsnode通过tarspatch下载，为什么需要启动rsync 服务？
什么场景下需要使用rsync？

**Comment by yuansx** [comment]
多节点部署tarspatch时会用到

**Comment by yuansx** [comment]
部署2个节点tarspatch，web和其中一个tarspatch相同机器，发布时，其中一个tarspatch可以拉取发布包，另外一个没有部署web的拉取不到发布包(因为发布包没有上传到这台机器上)，这个时候就需要用到rsync同步了。当然建议多节点部署tarspatch时，上传发布包路径使用网络文件系统，例如ceph、nfs等

**Comment by leeqx** [comment]
@yuansx 建议将这些加到readme中

**Comment by freelw** [comment]
了解了
