### ISSUE TITLE
日志级别

### ISSUE THREAD

**Issue by SWTHongbin** [TarsCloud/Tars#360]
生产上debug级别日志也在打印
在服务管理table-更多命令-修改日志级别为info,不管用

**Comment by ziyang314** [comment]
检查下前台发出的OSS请求参数是否是：command: tars.setloglevel INFO？

**Comment by SWTHongbin** [comment]
> 检查下前台发出的OSS请求参数是否是：command: tars.setloglevel INFO？

  有的！但是没有起作用

**Comment by SWTHongbin** [comment]
> tars日志等级是INFO日志是最低级别的，所以开了INFO，那还是会打印DEBUG日志的

我已经在项目里面做了日志级别
