### ISSUE TITLE
鉴权功能无效。

### ISSUE THREAD

**Issue by lszChain** [TarsCloud/Tars#364]
鉴权功能无效问题。
问题描述：用c++写的tars服务，配置了鉴权。服务重启后，自己写的客户端测试程序在没有配置用户名和密码的情况下仍然可以调用tars服务的接口。

**Comment by yuansx** [comment]
鉴权功能目前还没有完善！！

**Comment by lszChain** [comment]
嗯，看了源码，authServer服务部署上去了，也自己配了tarsauth模板，可是其他服务启动的时候似乎并没有解析endpoint的-e选项判断是否调用authServer的applyToken接口，而communicator连接器也没有涉及到调用authProcess接口的代码。所以我怀疑鉴权接口有名无实。
