### ISSUE TITLE
tars-spring-cloud-client 启动报错

### ISSUE THREAD

**Issue by wansweet** [TarsCloud/Tars#365]
application.yml配置：
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false

tars:
  client:
    async-invoke-timeout: 10000
    locator: http://localhost:8761/eureka/

报错：
Description:

Field clientProperties in com.qq.tars.register.eureka.EurekaRegisterHandler required a bean of type 'com.qq.tars.spring.config.TarsClientProperties' that could not be found.

Action:

Consider defining a bean of type 'com.qq.tars.spring.config.TarsClientProperties' in your configuration.

**Comment by cyhank** [comment]
同遇到这个问题.
根据https://github.com/TarsCloud/Tars/issues/313 中的回答,自定义一个排除了@TarsStartLifecycle的接口@EnableTarsClientConfiguration,这样启动才不会报错,你可以试试

**Comment by xvange** [comment]
解决了吗？我也遇到这个问题
