### ISSUE TITLE
请问框架代码更新升级需要做哪些操作？

### ISSUE THREAD

**Issue by mrzhengrui** [TarsCloud/Tars#366]
### What language are you using?
 C++、GO
 
### What operating system (Linux, Ubuntu, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 gcc 7.3
 
如果要更新使用最新的框架代码，是否要把安装过程重新走一遍？有没有其他简单操作办法？

**Comment by yuansx** [comment]
你想要更新框架哪些部分呢？如果是新增服务想用最新框架的特性，更新编译环境就可以了，基础服务目前没有更改，所以环境不需要重新搭建的

**Comment by mrzhengrui** [comment]
如果基础服务有更新，是不是需要重新编译源码，并重新部署基础服务的tgz包就可以了？

**Comment by yuansx** [comment]
是的
