### ISSUE TITLE
接口调试报内部系统错误

### ISSUE THREAD

**Issue by mtejiang** [TarsCloud/Tars#367]
![image](https://user-images.githubusercontent.com/2627564/50409393-407d1300-082d-11e9-8871-fd649fc454d1.png)

pm2的错误日志
[root@bogon HelloServer]# pm2 logs --err
0|tars-nod | error: 192.168.33.1||InfTestController.js:36|[interfaceDebug]: TypeError: Cannot read property 'hasOwnProperty' of undefined
0|tars-nod |     at ObjectProxy.initialize (/root/Tars/web/node_modules/@tars/rpc/core/client/ObjectProxy.js:56:16)
0|tars-nod |     at Communicator._createObjectProxy (/root/Tars/web/node_modules/@tars/rpc/core/client/Communicator.js:143:12)
0|tars-nod |     at new TarsClient (/root/Tars/web/app/service/infTest/TarsClient.js:33:25)
0|tars-nod |     at Object.InfTestService.debug (/root/Tars/web/app/service/infTest/InfTestService.js:29:18)
0|tars-nod |     at <anonymous>  

tars文件内容
[root@bogon HelloServer]# cat HelloServant.tars 
module TEST
{
struct SayHelloReq
{
	0 require string sMsg;
};
struct SayHelloRsp
{
	0 require string sRes;
};
interface HelloServant
{
        int test();
	int sayHello(SayHelloReq tReq, out SayHelloRsp tRsp);
};
};

**Comment by ziyang314** [comment]
是不是你的sayHello方法没有返回任何东西，或者你的服务没有跑起来

**Comment by mtejiang** [comment]
[root@bogon Client]# ./HelloClient world
2018-12-26 15:17:04|CommunicatorEpoll::run id:8898
iRet: 0
Rsp: Hello, world

**Comment by ziyang314** [comment]
打开F12查看一下接口返回了什么

**Comment by mtejiang** [comment]
![image](https://user-images.githubusercontent.com/2627564/50439609-a650c400-092d-11e9-8cde-b847df05fa33.png)
这个吗？

**Comment by user12138** [comment]
相同的问题 现在还是没修好

**Comment by ziyang314** [comment]
在app/service/infTest/TarsClient.js中加一个空对象可以跳过这个：
this._worker = Tars._createObjectProxy(objName, setName ? setName : '',{});

**Comment by githubchenglin** [comment]
解决办法
1、修改ObjectProxy.js文件，
我的机器上该文件路径为：/usr/local/src/TarsWeb/node_modules/@tars/rpc/core/client/ObjectProxy.js
找到第55行代码：ObjectProxy.prototype.initialize = function ($ObjName, $SetName, options) {
在下面添加一句：options = options || {};
保存退出
2、确认你的".tars"文件里面的“}”后面添加了分号“;”
3、重启tars-node-web：pm2 restart tars-node-web

仍然不行的使用：pm2 logs --err 查看你的错误原因吧，这种情况我没碰过
