### ISSUE TITLE
脚本及Java 有关datatime 字段默认值兼容性问题

### ISSUE THREAD

**Issue by towangle** [TarsCloud/Tars#37]
已有脚本默认值为：
t_server_conf表 patch_time、posttime字段的默认值为：'0000-00-00 00:00:00'，
同时com.qq.tars.entity.ServerConf Java类里面的patchTime和posttime字段默认值也为'0000-00-00 00:00:00'

建议将这两个datatime类型脚本及Java 类的默认值修改成：'1000-01-01 00:00:00'，这样针对5.7版本MySQL默认值就不需要做任何自定义调整，同时兼容5.6、5.7，更具备通用性

**Comment by towangle** [comment]
同时存在问题的还有 t_adapter_conf 和t_profile_template里的posttime

**Comment by wjx82850707** [comment]
我们已经修复了这个问题，请更新一下代码到最新版本。
