### ISSUE TITLE
当accept 返回-1 时，且errno != EAGAIN 的时候 死循环调用accept

### ISSUE THREAD

**Issue by leeqx** [TarsCloud/Tars#370]
### What language are you using?
 
 c++
### What operating system (Linux, Ubuntu, …) and version?
 centos
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
 gcc
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
1.  当进程可打开的文件句柄达到限制之后，此时如果再再有请求连接服务端口，服务将会一直死循环调用accept接口
```c++
  // tc_epoll_server.cpp:
void TC_EpollServer::NetThread::run()
{
....
     do
     {
                                    ret = accept(ev.data.u32, it->second->_ep.isIPv6() ? AF_INET6 : AF_INET);
     }while(ret);
 .....
}
int C_EpollServer::NetThread::accept(int fd, int domain){
....
         //直到发生EAGAIN才不继续accept
        if(errno == EAGAIN)
        {
            return false;
        }
....
}
```

**Comment by yuansx** [comment]
是的，按照这种分析是有这个问题。accept返回-1，错误码非EAGAIN的有很多情况，例如已经close的fd，accept返回EBADF，参数错误返回EINVAL，文件描述符超过设置最大值返回ENFILE，内存不足返回ENOMEM，内核态到用户态拷贝失败返回EFAULT等等，其中前2个框架做了保障，后面的不做处理，另外被信号打断返回EINTR会再次进入accept（看不太明白可以忽略）
你是遇着errno是什么呢？可以提出来分析一下吗

**Comment by leeqx** [comment]
这个错误码，EMFILE，too many open file

**Comment by gzg1984** [comment]
这个设计逻辑的前提是：你其他打开的文件句柄都会在近期关闭，所以我只要多试几次就应该能遇到有空闲句柄的情况。
处理方法之一： 看看为什么其他的文件句柄都没有关闭
处理方法之二：看看自己的ulimit，然后尝试改大一点
ulimit -a|grep open
open files                      (-n) 2000000
