### ISSUE TITLE
如何把DPDK集成到TARS??

### ISSUE THREAD

**Issue by ALBERTdbg** [TarsCloud/Tars#374]
### What language are you using?
 C++
### What operating system (Linux, Ubuntu, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 GCC
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by gzg1984** [comment]
dpdk+tars有两个解决方案思路：
1：用现成的协议栈，比如mtcp，利用mtcp里的mtcp_epoll的函数替换tars中的epoll函数，让dpdk+mtcp跑在tars下层。 这个做法对tars框架改动不大，但是也用不上dpdk的很多高级功能。
2：将tars底层的netthread体系换成dpdk的rx_burst体系，直接轮询收包，run-to-complete处理。这种方案对tars框架改动比较大，但是理论上可以最大化地降低响应延迟。

以上就是把DPDK继承到tars里的方法了，如果有其他问题，欢迎回复在下面，谢谢！

**Comment by ALBERTdbg** [comment]
> dpdk+tars有两个解决方案思路：
> 1：用现成的协议栈，比如mtcp，利用mtcp里的mtcp_epoll的函数替换tars中的epoll函数，让dpdk+mtcp跑在tars下层。 这个做法对tars框架改动不大，但是也用不上dpdk的很多高级功能。
> 2：将tars底层的netthread体系换成dpdk的rx_burst体系，直接轮询收包，run-to-complete处理。这种方案对tars框架改动比较大，但是理论上可以最大化地降低响应延迟。
> 
> 以上就是把DPDK集成到tars里的方法了，如果有其他问题，欢迎回复在下面，谢谢！

好的 非常感谢~

**Comment by ALBERTdbg** [comment]
大神，请问你们有没有做过dpdk+tars的项目，如果有的话是基于什么需求的？谢谢~

@gzg1984

**Comment by ALBERTdbg** [comment]
@gzg1984 

大神，请问你们有没有做过dpdk+tars的项目，如果有的话是基于什么需求的？谢谢~

**Comment by ALBERTdbg** [comment]
@gzg1984 

我们的需求是要用dpdk在tars前面做过滤分流分发，有没有必要深入改造协议栈呢？

**Comment by gzg1984** [comment]
> @gzg1984
> 
> 大神，请问你们有没有做过dpdk+tars的项目，如果有的话是基于什么需求的？谢谢~

有做过dpdk+tars降低响应延迟的研发。




> @gzg1984
> 
> 我们的需求是要用dpdk在tars前面做过滤分流分发，有没有必要深入改造协议栈呢？
在不清楚你的具体应用场景和开发目标的时候，只能笼统地说“改造和不改造协议栈都有可以达到过滤分流的目的，一般而言改造协议栈进行分流的响应延迟和处理时间会大大降低。”
