### ISSUE TITLE
现在想改造成微服务，选型了Tars，想问问 Tars在 服务和服务之间的 API调用鉴权 是什么样子的，还有 在服务网关这块 是什么样子的，有什么最近实践 ？

### ISSUE THREAD

**Issue by chenhuandong8010** [TarsCloud/Tars#375]
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by guzitajiu** [comment]
api鉴权方面现在还在完善中，后续会更新，暂时还不能用；网关这块还没有；
