### ISSUE TITLE
How to understand the expansion of tarsnode

### ISSUE THREAD

**Issue by Cowboyc** [TarsCloud/Tars#376]
1. If the service needs to be expanded, does the precondition for each machine to be expanded include that the basic and core services (including the web management system) of the tars and the tarsnode must be expanded first?

2. Is there any concept of master node and child node in this tar? According to https://github.com/tarscloud/tars/blob/master/install.zh.md, how can the master node identify this expansion node when modifying the IP address of the expansion machine on the machine to be expanded?

**Comment by Cowboyc** [comment]
https://github.com/TarsCloud/Tars/blob/master/Install.zh.md，，其中所说也只是修改一个扩容节点，如果我都很多1000台机器，怎么扩容

**Comment by dpp2009** [comment]
运维是有批量部署的工具的，和批量安装其他软件一样

**Comment by joan2015** [comment]
framework和web只有一套，考虑到单点的风险，最多部署到2台上就够了。扩容是扩容业务服务，只需要安装tarsnode即可。framwork和web会和每台业务服务器上的tarsnode进行通信，完成上报状态，发布，重启等等功能。

**Comment by Andrew-M-C** [comment]
> 容

“framework和web只有一套，考虑到单点的风险，最多部署到2台上就够了”

**Comment by cnfinder** [comment]
根据架构通信图来看 ，扩容主要是针对应用节点。 里面包含一个Node节点和多个server服务。 是这样吗？
我想咨询下 如果单独安装 tarsnode 节点啊？ 可以提供下教程吗？ 以及tarsnode 配置连接到registry服务。

**Comment by ETZhangSX** [comment]
单独安装tarsnode节点扩容的教程已经在[install.md#4.2.2](https://github.com/TarsCloud/Tars/blob/master/Install.zh.md#422-%E6%9C%8D%E5%8A%A1%E6%89%A9%E5%AE%B9%E5%89%8D%E5%AE%89%E8%A3%85tarsnode)中给出
