### ISSUE TITLE
执行npm run prd后，3000端口启动不起来

### ISSUE THREAD

**Issue by wangyc4007** [TarsCloud/Tars#377]
### What language are you using?
 
 Chinese
### What operating system (Linux, Ubuntu, …) and version?
 
 Linux version 3.10.0-229.el7.x86_64
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
 gcc 版本 4.8.2 (GCC) 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

所有的都安装完成后，执行npm run prd命令，3000端口不能启动，访问不到web管理平台，以tarsregistry日志为例（|ERROR|[TARS][CommunicatorEpoll::handleInputImp] connect error tcp -h 192.168.3.27 -p 19386,tars.tarsnode.ServerObj,_connExcCnt=1,Connection refused），谢谢解答
                                                                       本人邮箱m18059234007@163.com

**Comment by ziyang314** [comment]
可能端口被占用，换个端口试下。
也可能是没有安装好，到web根目录下执行npm install试下

**Comment by wangyc4007** [comment]
> 可能端口被占用，换个端口试下。
> 也可能是没有安装好，到web根目录下执行npm install试下

谢谢，已解决
