### ISSUE TITLE
请问如何测试TARS的性能，具体的过程是什么？？

### ISSUE THREAD

**Issue by ALBERTdbg** [TarsCloud/Tars#378]
### What language are you using?
 C++
### What operating system (Linux, Ubuntu, …) and version?
 Linux
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 gcc
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by gzg1984** [comment]
https://github.com/TarsCloud/TarsGo/blob/master/docs/tars_go_performance.md

**Comment by ALBERTdbg** [comment]
谢谢，我看TARS官网里面大概和你描述的差不多。现在有一个问题就是，我们需要知道下面链接里的这些TARS性能数据是怎么测试出来的，用了哪些测试工具，我们能不能自己也把这些数据测试出来，所以特别想请教大神帮帮忙，不胜感激~

https://github.com/TarsCloud/Tars/blob/master/docs/tars_performce.md

@gzg1984

**Comment by gzg1984** [comment]
服务端是基于tars写的echo回消息的简单服务，客户端是调用这个tars -echo 服务的简单客户端。这两个程序可以自己写的。

**Comment by helloopenworld** [comment]
可以参考这个测试用例https://github.com/TarsCloud/TarsCpp/tree/master/examples/StressDemo
