### ISSUE TITLE
v1.6.0使用build/install.sh安装完成，tarsnotify.tgz发布失败，pm2 log 显示doEndpoints, exception ,return: -13001

### ISSUE THREAD

**Issue by leevenluo** [TarsCloud/Tars#382]
0|tars-node-web  | [TARS][EndpointManager doEndpoints, exception ,return: -13001 ,objname: tars.tarsAdminRegistry.AdminRegObj  ,setname:
0|tars-node-web  | [AdminService.addTask]: Error: call remote server timeout(no adapter selected)
0|tars-node-web  |     at tars.AdminRegProxy.RPCClientPrx.rpcClient.(anonymous function) [as addTaskReq] (/root/Tars/web/app/service/util/rpcClient/index.js:48:35)
0|tars-node-web  |     at <anonymous>
0|tars-node-web  | [TARS][EndpointManager doEndpoints, exception ,return: -13001 ,objname: tars.tarsAdminRegistry.AdminRegObj  ,setname:
0|tars-node-web  | error: TaskService.js:31|[adminService.getTaskRsp]: Error: call remote server timeout(no adapter selected)
0|tars-node-web  |     at tars.AdminRegProxy.RPCClientPrx.rpcClient.(anonymous function) [as getTaskRsp] (/root/Tars/web/app/service/util/rpcClient/index.js:48:35)
0|tars-node-web  |     at <anonymous>

**Comment by leevenluo** [comment]
![image](https://user-images.githubusercontent.com/3760432/53028055-1b112c00-34a1-11e9-92be-4593e7b455d3.png)
![image](https://user-images.githubusercontent.com/3760432/53028122-3c721800-34a1-11e9-9b46-3dd2ff67cd0a.png)
![image](https://user-images.githubusercontent.com/3760432/53028132-40059f00-34a1-11e9-91a0-2f6edac27b50.png)
![image](https://user-images.githubusercontent.com/3760432/53028134-41cf6280-34a1-11e9-9371-56782d4e6651.png)
![image](https://user-images.githubusercontent.com/3760432/53028150-45fb8000-34a1-11e9-9b91-c5db3edfff41.png)

**Comment by kiscz** [comment]
is this issue solved?

**Comment by guzitajiu** [comment]
问题的原因应该是 **“步骤4.3. 安装web管理系统”** 中，修改web下的配置文件不成功，导致tars_web无法访问tarsadminregistry，从而包上述的错误

**Comment by StarCarrol** [comment]
这个问题怎么解决的，我重启服务的时候也报了类似的错误
