### ISSUE TITLE
tars2node和nodejs版本源码对应不上

### ISSUE THREAD

**Issue by qlyzpqz** [TarsCloud/Tars#383]
### What language are you using?
 nodejs
 
### What operating system (Linux, Ubuntu, …) and version?
 linux
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 nodejs v8.10.0
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
发现TarsNode的源码应该不是最新的，和Tars/cpp/tools/tars2node里的版本也对应不上

Tars/cpp/tools/tars2node生成的tars协议序列化对象为TarsInputStream、TarsOutputStream

Tars/nodejs/stream定义的序列化对象为InputStream、OutputStream

**Comment by medns** [comment]
您可使用此项目 [https://github.com/tars-node/tars2node](https://github.com/tars-node/tars2node)
配合这个 Group 下的其他模块，以及 NPM 的包
