### ISSUE TITLE
tarsnode 上报：ERROR|ServerObject.cpp:reportMemProperty:706|stream is empty:

### ISSUE THREAD

**Issue by jackylee92** [TarsCloud/Tars#385]
### What language are you using?
 PHP
 
### What operating system (Linux, Ubuntu, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
产生非常多的：ERROR|ServerObject.cpp:reportMemProperty:706|stream is empty:
log文件：tarsnode/tars.tarsnode_ReportMemThread4.log
错误信息：2019-03-01 06:10:31|4381|ERROR|ServerObject.cpp:reportMemProperty:706|stream is empty:
![image](https://user-images.githubusercontent.com/24886757/53615662-fa23a600-3c19-11e9-9bbd-30b7d76d1ca2.png)

![image](https://user-images.githubusercontent.com/24886757/53615674-090a5880-3c1a-11e9-9cc2-b22371445d92.png)

**Comment by dpp2009** [comment]
能查出是哪个服务上报的么

**Comment by change93** [comment]
请问问题是否解决了呢

> ### What language are you using?
> PHP
> 
> ### What operating system (Linux, Ubuntu, …) and version?
> Linux
> 
> ### What runtime / compiler are you using (e.g. jdk version or version of gcc)
> gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
> 
> Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
> 产生非常多的：ERROR|ServerObject.cpp:reportMemProperty:706|stream is empty:
> log文件：tarsnode/tars.tarsnode_ReportMemThread4.log
> 错误信息：2019-03-01 06:10:31|4381|ERROR|ServerObject.cpp:reportMemProperty:706|stream is empty:
> ![image](https://user-images.githubusercontent.com/24886757/53615662-fa23a600-3c19-11e9-9bbd-30b7d76d1ca2.png)
> 
> ![image](https://user-images.githubusercontent.com/24886757/53615674-090a5880-3c1a-11e9-9cc2-b22371445d92.png)

请问问题是否有解决呢

**Comment by KatharineOzil** [comment]
感谢jackylee92的提问以及dpp2009, change93的跟进。
由于无法联系到提问者、无法定位到问题细节情况，该问题先行关闭。后面若是还有其他问题，请开启新的Issue提问。
