### ISSUE TITLE
tars admin后台tarsstat报错：ERROR:192.168.0.114|insert2Db_ip:db.mysql.com|port:3306:统计入库失败，请及时处理!

### ISSUE THREAD

**Issue by ouYoung3** [TarsCloud/Tars#387]
### What language are you using?
 java
 
### What operating system (Linux, Ubuntu, …) and version?
 centos 7.4
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 jdk 1.8.0_65 X64
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
tarsstat日志如下：
ERROR:192.168.0.114|insert2Db_ip:db.mysql.com|port:3306:统计入库失败，请及时处理!
tarsproperty日志如下：
ERROR:192.168.0.114_stat ip:192.168.0.114 ReapSSDProcThread::run write db:ip:db.mysql.com|port:3306|timeout 3 Minute.

**Comment by kevenfeng** [comment]
![image](https://user-images.githubusercontent.com/5917426/54001812-863c4d00-4187-11e9-9c38-a3c3cd9c1b9e.png)
把db改成你自己的就行了

**Comment by KatharineOzil** [comment]
感谢ouYoung3的提问以及kevenfeng的跟进。
由于无法联系到提问者，Issue开启时间超过半年，该问题先行关闭。后面若是还有其他问题，请开启新的Issue提问。
