### ISSUE TITLE
项目介绍英文描述不一致，语法错误？

### ISSUE THREAD

**Issue by fjx2000** [TarsCloud/Tars#388]
### What language are you using?
 English

在项目介绍的标题是
Tars is a highly performance rpc framework based on naming service using tars protocol and provides a semi-automatic operation platform.
下面的描述是
Tars is a high-performance RPC framework based on name service and Tars protocol, also integrated administration platform, and implemented hosting-service via flexible schedule.

标题是不是有语法错误，highly performance rpc ?  是不是应该改成和下面的描述一致 Tars is a high-performance RPC framework

**Comment by change93** [comment]
已修复
