### ISSUE TITLE
tarsnode不能部署在外网节点吗？只能部署在同一局域网才行？

### ISSUE THREAD

**Issue by coretimes** [TarsCloud/Tars#392]
tars没法部署外网节点吗？我用外网ip来部署节点tarsnode就会报主控机器内网ip无法访问，然后我用外网ip去部署主控就没法启动成功，是不是tars的节点没法部署在外网ip上只能在内网上部署？

**Comment by coretimes** [comment]
@loveyacper @LawlietLi @meijing0114 @medns

**Comment by medns** [comment]
外网和内网的端口需要（TCP）可以连上才可以
