### ISSUE TITLE
tars鉴权功能是否支持？鉴权的使用是否成熟？

### ISSUE THREAD

**Issue by ALBERTdbg** [TarsCloud/Tars#395]
### What language are you using?
 
 c++

### What operating system (Linux, Ubuntu, …) and version?
 
Linux 

### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
gcc 

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by ALBERTdbg** [comment]
目前为止，tars的鉴权功能是否支持？鉴权的使用是否成熟？

**Comment by ruanshudong** [comment]
cpp版本鉴权master分支上已经合入, 可以试用了.
