### ISSUE TITLE
目前使用c++语言在tars框架下能不能实现tars调用链功能？

### ISSUE THREAD

**Issue by ALBERTdbg** [TarsCloud/Tars#396]
### What language are you using?
 
C++ 

### What operating system (Linux, Ubuntu, …) and version?
 
redhat 

### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
g++ 

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by ALBERTdbg** [comment]
对于tars调用链有一些疑惑，所以自己写了一篇博客列举了几个问题，希望各位指点~

https://blog.csdn.net/weixin_43507027/article/details/89315964

**Comment by chhy2009** [comment]
The missing file(text_map_carrier.h) had been commit, see commit 831b21

**Comment by dujue** [comment]
@chhy2009 感谢您提交了缺失的text_map_carrier.h文件，但是我在对tarsframework进行重新编译时，仍然会出现其他错误。
   错误详细信息：[https://blog.csdn.net/shuishishuideyingzi/article/details/90035196](https://blog.csdn.net/shuishishuideyingzi/article/details/90035196)

1.环境
1.1 C++11
1.2 cmake-3.1.2
1.3 curl-7.29.0
1.4 opentracing-cpp ,version : 1.5.x
1.5 zipkin-cpp-opentracing  ,version : master

错误1: 
       初始化动态数组错误。
错误2:
     `
tarscpp/servant/protocol/framework/NodeDescriptor.tars
[ 66%] Built target FRAMEWORK-PROTOCOL
Scanning dependencies of target tarsconfig
[ 66%] Building CXX object ConfigServer/CMakeFiles/tarsconfig.dir/ConfigImp.cpp.o
[ 67%] Building CXX object ConfigServer/CMakeFiles/tarsconfig.dir/main.cpp.o
[ 67%] Building CXX object ConfigServer/CMakeFiles/tarsconfig.dir/ConfigServer.cpp.o
Linking CXX executable ../deploy/tarsconfig/bin/tarsconfig
../tarscpp/servant/lib/libtarsservant.a(TarsCurrent.cpp.o)：在函数‘_GLOBAL__sub_I__ZN4tars11TarsCurrentC2EPNS_13ServantHandleE’中：
/usr/local/include/opentracing/propagation.h:72：对‘opentracing::v2::propagation_error_category()’未定义的引用
/usr/local/include/opentracing/propagation.h:76：对‘opentracing::v2::propagation_error_category()’未定义的引用
/usr/local/include/opentracing/propagation.h:81：对‘opentracing::v2::propagation_error_category()’未定义的引用
/usr/local/include/opentracing/propagation.h:85：对‘opentracing::v2::propagation_error_category()’未定义的引用
/usr/local/include/opentracing/propagation.h:90：对‘opentracing::v2::propagation_error_category()’未定义的引用
../tarscpp/servant/lib/libtarsservant.a(Servant.cpp.o):/usr/local/include/opentracing/propagation.h:72: more undefined references to `opentracing::v2::propagation_error_category()' follow
../tarscpp/servant/lib/libtarsservant.a(Communicator.cpp.o)：在函数‘tars::Communicator::initClientConfig()’中：
/home/TarsFramework/tarscpp/servant/libservant/Communicator.cpp:153：对‘zipkin::IpAddress::IpAddress(zipkin::IpVersion, std::string const&)’未定义的引用
../tarscpp/servant/lib/libtarsservant.a(Communicator.cpp.o)：在函数‘tars::Communicator::initClientConfig()’中：
/home/maocc/tars-pjt/tars-install-pkgs/unVM-pkgs/TarsFramework/tarscpp/servant/servant/Communicator.h:318：对‘zipkin::makeZipkinOtTracer(zipkin::ZipkinOtTracerOptions const&)’未定义的引用
../tarscpp/servant/lib/libtarsservant.a(Communicator.cpp.o)：在函数‘_GLOBAL__sub_I__ZN4tars12ClientConfig7LocalIpE’中：
/usr/local/include/opentracing/propagation.h:72：对‘opentracing::v2::propagation_error_category()’未定义的引用
/usr/local/include/opentracing/propagation.h:76：对‘opentracing::v2::propagation_error_category()’未定义的引用
/usr/local/include/opentracing/propagation.h:81：对‘opentracing::v2::propagation_error_category()’未定义的引用
/usr/local/include/opentracing/propagation.h:85：对‘opentracing::v2::propagation_error_category()’未定义的引用
/usr/local/include/opentracing/propagation.h:90：对‘opentracing::v2::propagation_error_category()’未定义的引用
../tarscpp/servant/lib/libtarsservant.a(AppCache.cpp.o):/usr/local/include/opentracing/propagation.h:72: more undefined references to `opentracing::v2::propagation_error_category()' follow
collect2: 错误：ld 返回 1
make[2]: *** [deploy/tarsconfig/bin/tarsconfig] 错误 1
make[1]: *** [ConfigServer/CMakeFiles/tarsconfig.dir/all] 错误 2
make: *** [all] 错误 
`

**Comment by chhy2009** [comment]
错误1:
初始化动态数组错误。

**Comment by chhy2009** [comment]
错误1:
初始化动态数组错误。
This problem is fixed in commit 715419.
错误2:
It doesn't happened in my side. Maybe there are something wrong when you install opentracing.

**Comment by jcy1001** [comment]
[ 64%] Linking CXX executable ../deploy/tarsconfig/bin/tarsconfig
../tarscpp/servant/lib/libtarsservant.a(Application.cpp.o): In function `__static_initialization_and_destruction_0':
/usr/local/include/opentracing/propagation.h:72: undefined reference to `opentracing::v3_unstable::propagation_error_category()'
/usr/local/include/opentracing/propagation.h:76: undefined reference to `opentracing::v3_unstable::propagation_error_category()'
/usr/local/include/opentracing/propagation.h:81: undefined reference to `opentracing::v3_unstable::propagation_error_category()'
/usr/local/include/opentracing/propagation.h:85: undefined reference to `opentracing::v3_unstable::propagation_error_category()'
/usr/local/include/opentracing/propagation.h:90: undefined reference to `opentracing::v3_unstable::propagation_error_category()'
../tarscpp/servant/lib/libtarsservant.a(CommunicatorEpoll.cpp.o):/usr/local/include/opentracing/propagation.h:72: more undefined references to `opentracing::v3_unstable::propagation_error_category()' follow
../tarscpp/servant/lib/libtarsservant.a(Communicator.cpp.o): In function `tars::Communicator::initClientConfig()':
/home/jcy/work/Tars/framework/tarscpp/servant/libservant/Communicator.cpp:156: undefined reference to `zipkin::IpAddress::IpAddress(zipkin::IpVersion, std::string const&)'
../tarscpp/servant/lib/libtarsservant.a(Communicator.cpp.o): In function `TraceManager':

**Comment by chhy2009** [comment]
@dujue @jcy1001 :
Maybe you miss some details, please see:
https://github.com/TarsCloud/TarsCpp/blob/master/docs-en/tars_cpp_user_guide.md#13-tars-call-chain

Compile and install
The feature of tars call chain is controlled by the compile option _USE_OPENTRACKING, which is off by default.
Open mode: Execute export _USE_OPENTRACKING=1 in the shell before compile tars. ** After the framework is compiled, modify the 'servant/makefile/makefile.tars' file and add a line to the front before install tars:
_USE_OPENTRACKING=1
to indicates that the framework has opened the call chain switch**. In addition, opentraking, curl, zipkin_opentracing install path need to be manually modified to the correct path (The default path is /usr/local/lib).

**Comment by guzitajiu** [comment]
暂时应该还不能用，后期会补全这方面的功能；开发团队正在开发
