### ISSUE TITLE
C++中存在套接字泄露的问题

### ISSUE THREAD

**Issue by scuiris** [TarsCloud/Tars#400]
### What language are you using?
 
 C++
### What operating system (Linux, Ubuntu, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 gcc 6.3
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
![image](https://user-images.githubusercontent.com/46811986/57501312-9dc7bb80-7319-11e9-9355-db556aa9a31e.png)
这种写法会造成当fin包和数据包间隔时间很短的情况下少处理一个fin事件

**Comment by guzitajiu** [comment]
你指的具体场景是什么，长链接还是短连接？这与套接字泄露有什么关系？不太理解你的意思，你详细的阐述一下。

**Comment by KatharineOzil** [comment]
感谢这位朋友的提问以及guzitajiu的跟进。
由于无法联系到提问者、无法定位到问题细节情况，该问题先行关闭。后面若是还有其他问题，请开启新的Issue提问。
