### ISSUE TITLE
Java client calls CPP tars service RPC network layer takes an unusual time, which is high

### ISSUE THREAD

**Issue by yljgo** [TarsCloud/Tars#402]
### What language are you using?
 java , cpp
 
### What operating system (Linux, Ubuntu, …) and version?
 centos7.3
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 gcc 6.3, jdk 1.8
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

Some requests from the client to the server take a long time

**Comment by walkertest** [comment]
请问是超时设置没有生效的问题吗？

https://github.com/TarsCloud/TarsJava/issues/19

可以看看是否是这个issue，tars-java的版本上已经fix了，还没有经过完整测试
