### ISSUE TITLE
建议规范下文档的中英文版本文件命名和链接

### ISSUE THREAD

**Issue by wencan** [TarsCloud/Tars#406]
目前文档存在下面两个问题：
- 链接错误。比如英文README.md链接了中文Introduction.md
- 文件命名不规范。部分英文版以.md为后缀，中文版以zh.md为后缀；部分恰好相反。

建议统一英文文档以md为后缀，中文文档以zh.md为后缀。docs目录名照此修改。

我原想改过来，提交个pull request。怕不合作者的意思。

**Comment by change93** [comment]
已修改
