### ISSUE TITLE
tars是否有结合k8s支持服务打成镜像部署的方案

### ISSUE THREAD

**Issue by iliangzi** [TarsCloud/Tars#407]
### What language are you using?
 
PHP&GO
### What operating system (Linux, Ubuntu, …) and version?
 linux
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by ruanshudong** [comment]
https://tarscloud.github.io/TarsDocs/rumen/an-zhuang/k8s-docker-1.html
