### ISSUE TITLE
关于tars-node-web的疑问

### ISSUE THREAD

**Issue by skysmall** [TarsCloud/Tars#418]
### What language are you using?
 c++
 
### What operating system (Linux, Ubuntu, …) and version?
 centos 7
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 jdk 1.8
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

1、在网页（ tars-node-web）中，配置自己的服务时，线程数有什么作用？

**Comment by Fr1ck** [comment]
你好，设置线程数之后框架就会给servant启动相应的线程数，用来处理业务。可以看下TarsCpp/docs/tars_cpp_server_thread.md里对框架服务线程的说明。

**Comment by skysmall** [comment]
谢谢解答 ------------------ 原始邮件 ------------------
发件人: "Fr1ck"<notifications@github.com>
发送时间: 2019年7月19日(星期五) 下午3:15
收件人: "TarsCloud/Tars"<Tars@noreply.github.com>;
抄送: "skysmall"<849687563@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [TarsCloud/Tars] 关于tars-node-web的疑问 (#418)



你好，设置线程数之后框架就会给servant启动相应的线程数，用来处理业务。可以看下TarsCpp/docs/tars_cpp_server_thread.md里对框架&#x670D;务线程的说明。
 
&mdash;
