### ISSUE TITLE
一键部署出现错误：IOError: [Errno 2] No such file or directory: '/data/Tars/framework/build/deploy/tarsnotify/tarsnotify'

### ISSUE THREAD

**Issue by githubchenglin** [TarsCloud/Tars#422]
使用一键部署出现错误：IOError: [Errno 2] No such file or directory: '/data/Tars/framework/build/deploy/tarsnotify/tarsnotify'

我看了一下，这个文件（文件夹）的确不存在，而且感觉这个目录是否有问题？这是一键部署的bug么？？

**Comment by githubchenglin** [comment]
一键部署的python脚本是真的有问题呀：出错代码为这一行：
 shutil.copy(srcDir+"/"+server,dstBinDir+"/"+server)
此时的server=tarsnotify , srcDir=/data/Tars/framework/build/deploy/tarsnotify ,这个目录根本就不存在。
大哥你们这开源的东西 文档太随便写了

**Comment by ETZhangSX** [comment]
你好，应该不止这个报错的，可以看一下编译部分是否有问题，文件不存在应该是没有编译成功，可能的原因是机器或服务器或虚拟机的内存不足。经测试1G内存都会出现上述问题，可以使用虚拟内存将内存增加到2G，实测CentOS7可以通过编译。

**Comment by githubchenglin** [comment]
我的内存确实只有1G 我尝试增加内存试一下感谢您的回复！




------------------ 原始邮件 ------------------
发件人: "ETZhangSX"<notifications@github.com>; 
发送时间: 2019年6月30日(星期天) 晚上6:32
收件人: "TarsCloud/Tars"<Tars@noreply.github.com>; 
抄送: "爱洗头的廖成林"<13347220417@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [TarsCloud/Tars] 一键部署出现错误：IOError: [Errno 2] No such file or directory: '/data/Tars/framework/build/deploy/tarsnotify/tarsnotify' (#422)




你好，应该不止这个报错的，可以看一下编译部分是否有问题，文件不存在应该是没有编译成功，可能的原因是机器或服务器或虚拟机的内存不足。经测试1G内存都会出现上述问题，可以使用虚拟内存将内存增加到2G，实测CentOS7可以通过编译。

**Comment by TCZWJ** [comment]
> 一键部署的python脚本是真的有问题呀：出错代码为这一行：
> shutil.copy(srcDir+"/"+server,dstBinDir+"/"+server)
> 此时的server=tarsnotify , srcDir=/data/Tars/framework/build/deploy/tarsnotify ,这个目录根本就不存在。
> 大哥你们这开源的东西 文档太随便写了

淡定。。。开源的东西需要大家一起完善，用开源东西不是付费买东西，没有谁服务谁的道理，只有围绕“大家一起把开源越做越好”

**Comment by githubchenglin** [comment]
吐槽之后的几天 官方把部署文档更新了一版，这一版相对于之前的介绍 很多坑已经说出来了

**Comment by bartdong** [comment]
> 吐槽之后的几天 官方把部署文档更新了一版，这一版相对于之前的介绍 很多坑已经说出来了

> 你好，应该不止这个报错的，可以看一下编译部分是否有问题，文件不存在应该是没有编译成功，可能的原因是机器或服务器或虚拟机的内存不足。经测试1G内存都会出现上述问题，可以使用虚拟内存将内存增加到2G，实测CentOS7可以通过编译。

感谢githubchenglin的提问，及ETZhangSX的回答，相关信息已更新至安装文档。
