### ISSUE TITLE
发布成功后，刚开始tarsquerystat、tarsqueryproperty的当前状态为active，但一段时间后会变成inactive

### ISSUE THREAD

**Issue by ouliuquan** [TarsCloud/Tars#432]
### What language are you using?
 C++
 
### What operating system (Linux, Ubuntu, …) and version?
 CentOS 7.6
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 GCC 4.8.5
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

“发布成功后，刚开始tarsquerystat、tarsqueryproperty的当前状态为active，但一段时间后会变成inactive

原因：一个WEB管理平台的模板配置文件有问题，另一个这两个服务的obj名字没有和系统对应上

解决办法：修改WEB平台模板配置文件中，关于数据库配置，改成你自己设置的。修改两个服务的objname为固定的NoTarsObj”

我遇到一样的问题，搜索发现这个问题两年半前就存在了，请你们有时间修复一下，避免后面的人再次遇到这种问题
![tars4](https://user-images.githubusercontent.com/38776890/61341636-bdc7ae00-a879-11e9-9fc0-a3fb6c1ac374.JPG)

**Comment by ouliuquan** [comment]
还有，我知道文档已经这样写了，但是这始终是一个让人摸不着头脑的地方，如果确实是没有办法修改，那我们也应该是Install.md里面特意去强调这个地方。

**Comment by ruanshudong** [comment]
新框架安装的时候, 这些服务都自动安装了, 应该没有这个问题了, 可以参考文档再试一试.
