### ISSUE TITLE
docker版本,Java启动脚本模板有错误

### ISSUE THREAD

**Issue by laijiawei** [TarsCloud/Tars#439]
Java
linux docker版本
Jdk10

tars docker容器内使用的Jdk版本是1.10，启动脚本模板有
-XX:+PrintGCApplicationStoppedTime这个参数，导致启动失败。

**Comment by itcheng2019** [comment]
赞一个

**Comment by laijiawei** [comment]
db_tars库，t_profile_template表，
update t_profile_template set profile='以下模板' where template_name='tars.tarsjava.default'

--------模板------------
<tars>
 <application>
   enableset=${enableset}
    setdivision=${setdivision}
    <client>
      locator=${locator}
      sync-invoke-timeout=20000
     async-invoke-timeout=20000
      refresh-endpoint-interval=60000
     stat=tars.tarsstat.StatObj
      property=tars.tarsproperty.PropertyObj
      report-interval=60000
     modulename=${modulename}
      sample-rate=100000
      max-sample-count=50
   </client>
   <server>
      app=${app}
      server=${server}
      localip=${localip}
      local=${local}
      basepath=${basepath}
      datapath=${datapath}
      logpath=${logpath}
      loglevel=DEBUG
      logsize=15M
     log=tars.tarslog.LogObj
     config=tars.tarsconfig.ConfigObj
      notify=tars.tarsnotify.NotifyObj
      mainclass=com.qq.tars.server.startup.Main
     classpath=${basepath}/conf:${basepath}/WEB-INF/classes:${basepath}/WEB-INF/lib
      jvmparams=-Dcom.sun.management.jmxremote.ssl\=false -Dcom.sun.management.jmxremote.authenticate\=false -Xms2000m -Xmx2000m -Xmn1000m -Xss1000k -XX:PermSize\=128M -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction\=60 -XX:+CMSParallelRemarkEnabled -XX:+CMSScavengeBeforeRemark  -verbosegc -XX:+PrintGCDetails -XX:ErrorFile\=${logpath}/${app}/${server}/jvm_error.log
      sessiontimeout=120000
     sessioncheckinterval=60000
      tcpnodelay=true
     udpbuffersize=8192
      charsetname=UTF-8
     backupfiles=conf
    </server>
 </application>
</tars>
----------------------------------------------------
ps：这个项目坑太多了，且行且珍惜。
