### ISSUE TITLE
tars基础服务启动不起来, 每次都要重新执行tars_install.sh脚本解决

### ISSUE THREAD

**Issue by muyehub** [TarsCloud/Tars#442]
### What language are you using?
 PHP
 
### What operating system (Linux, Ubuntu, …) and version?
 CentOS7.6
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 gcc 4.8.5, mysql5.7.27 php7.1.31 vagrant2.2.5
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
事情是这样的,  我在vagrant中装了一个虚拟机, 按照TarsPHP官方文档中搭建了一套环境, 但我第二天重启的时候发现很多系统服务挂掉了, 设置状态是Active, 当前状态是Off, 我就一点点排查, 后来看到有一个issue中提到重新执行一下/usr/local/app/tars/tars_install.sh脚本试试看, 我试了一下果然好使了.

但是, 当我再次重启虚拟机之后又会发生同样的情况, 难道每次都需要执行一下这个安装脚本么?

另: 在web系统中使用pm2 logs tars-node-web查看, 发现有下图这么一段报错出现, 不知道是不是这里的缘故?
![image](https://user-images.githubusercontent.com/3871604/62447435-ee737700-b797-11e9-8445-fc2a7a1bfe9f.png)

再另: 不知道tars系统和web管理系统有没有启动的先后顺序, 是不是跟我先启动web管理系统而没有先启动tars系统有关系?

谢谢解答.

**Comment by bobzhangyong** [comment]
检查  /usr/local/app/tars/app_log/tars 这个下面对应每个服务的日志

是否是 虚拟机重启以后 导致ip 变化，导致实际ip 和 之前等级的绑定ip 不一致，导致无法启动。

**Comment by muyehub** [comment]
你好, 我详细看了所有的服务, 今天重启的时候所有服务都启动了, 日志中并没有启动的纪录, 虚拟机的ip我设定死了, 就是192.168.2.2, 不会每次启动都变化. 但还是在点击重启或者停止按钮时会发生系统内部错误的报错, 日志中没有记载, 给我感觉好像就是web服务启动了, tars服务没有启动一样, 日志居然也没有纪录, 有点奇怪. 我把我的虚拟机打包传到了下方链接处, 如果特别不忙, 请麻烦您看一下, 如果忙就算了, 我可以把tars_install.sh设置为开机启动就行了, 感谢.
https://app.vagrantup.com/muyev/boxes/tarsphp_service
t

**Comment by bartdong** [comment]
tarsregistry是tars的主控服务，与tarsWeb是独立的，如果要正常使用必须要都启动起来才可以。
把tars_install.sh设置为开机启动是一个解决办法。
希望能帮到你。

**Comment by ruanshudong** [comment]
请使用最新的部署脚本一键安装 , 可以参考
