### ISSUE TITLE
Install.zh.md 说明文件需要修正

### ISSUE THREAD

**Issue by freelw** [TarsCloud/Tars#444]
2.2. c++ 开发环境安装

这里面
“
然后进入build源码目录

cd ${source_folder}/build
chmod u+x build.sh
./build.sh prepare
./build.sh all
”

需要修正为

“
然后进入build源码目录

cd ${source_folder}/TarsFramework/build
chmod u+x build.sh
./build.sh prepare
./build.sh all
“

**Comment by guzitajiu** [comment]
done

**Comment by freelw** [comment]
谢谢
