### ISSUE TITLE
上传发布包，提示not found

### ISSUE THREAD

**Issue by nobslin** [TarsCloud/Tars#449]
问题1：
第一次在无外网的机器上部署单机tars，部署看起来成功，发布tarsnotify包时候，上传包提示not found，是什么原因呢
问题2：
为什么每次刚部署完tars，每个服务里的服务监控和特性监控tab按钮，都会提示：cannot
 read propertyly keys of undefined 和 adminservice.getEndpoints 错误呢

麻烦指导怎么查看问题，谢谢！

**Comment by qiuxin** [comment]
问题1： 在Tars/framework/build目录下，make tarsproperty-tar生成tarsnotify.tgz，然后copy到web所在机器，选择tarsnotify.tgz所在路径上传和发布即可。我这边操作实际操作一切正常。 我们环境如果存在差异，我们再评估环境差异对功能的影响。

**Comment by qiuxin** [comment]
问题2： 确保所有的tars框架服务（tarsstat-tar，tarsnotify-tar，tarsproperty-tar，tarslog-tar，tarsquerystat-tar，tarsqueryproperty-tar）都有部署成功，点击服务监控和特性监控按钮，需要调用对应服务。

**Comment by qiuxin** [comment]
问题2： 日志的查看，见/usr/local/app/tars/app_log/tars/目录下

**Comment by qiuxin** [comment]
第2个问题根因： 当刚部署好的Tars环境，点击“服务监控”和“特性监控”的时候， 就会返回缓慢，web超时后弹出“Bad Gateway”菜单。  实际上，这个问题的原因应该是： “服务监控”和“特性监控”需要对比前一天的数据，而新安装的环境根本找不到前一天的数据，所以会提示出错。
