### ISSUE TITLE
编译安装TARS报错

### ISSUE THREAD

**Issue by hejinke** [TarsCloud/Tars#451]
执行./build.sh all 命令的时候报以下错误：
请问怎么解决

[ 32%] Built target tars2oc
[ 33%] Built target tars2php
[ 34%] Built target tars2android
Linking CXX executable tars2node
../../util/lib/libtarsutil.a(tc_encoder.cpp.o): In function `tars::TC_Encoder::gbk2utf8(char*, int&, char const*, int)':
/usr/local/TarsFramework/tarscpp/util/src/tc_encoder.cpp:39: undefined reference to `libiconv_open'
/usr/local/TarsFramework/tarscpp/util/src/tc_encoder.cpp:75: undefined reference to `libiconv_close'
/usr/local/TarsFramework/tarscpp/util/src/tc_encoder.cpp:66: undefined reference to `libiconv'
../../util/lib/libtarsutil.a(tc_encoder.cpp.o): In function `tars::TC_Encoder::gbk2utf8(std::string const&)':
/usr/local/TarsFramework/tarscpp/util/src/tc_encoder.cpp:84: undefined reference to `libiconv_open'
/usr/local/TarsFramework/tarscpp/util/src/tc_encoder.cpp:118: undefined reference to `libiconv'
/usr/local/TarsFramework/tarscpp/util/src/tc_encoder.cpp:134: undefined reference to `libiconv_close'
../../util/lib/libtarsutil.a(tc_encoder.cpp.o): In function `tars::TC_Encoder::utf82gbk(char*, int&, char const*, int)':
/usr/local/TarsFramework/tarscpp/util/src/tc_encoder.cpp:203: undefined reference to `libiconv_open'
/usr/local/TarsFramework/tarscpp/util/src/tc_encoder.cpp:214: undefined reference to `libiconv'
/usr/local/TarsFramework/tarscpp/util/src/tc_encoder.cpp:223: undefined reference to `libiconv_close'
/usr/local/TarsFramework/tarscpp/util/src/tc_encoder.cpp:218: undefined reference to `libiconv_close'
../../util/lib/libtarsutil.a(tc_encoder.cpp.o): In function `tars::TC_Encoder::gbk2utf8(std::string const&, std::vector<std::string, std::allocator<std::string> >&)':
/usr/local/TarsFramework/tarscpp/util/src/tc_encoder.cpp:142: undefined reference to `libiconv_open'
/usr/local/TarsFramework/tarscpp/util/src/tc_encoder.cpp:178: undefined reference to `libiconv'
/usr/local/TarsFramework/tarscpp/util/src/tc_encoder.cpp:196: undefined reference to `libiconv_close'
collect2: error: ld returned 1 exit status
make[2]: *** [tarscpp/tools/tars2node/tars2node] Error 1
make[1]: *** [tarscpp/tools/tars2node/CMakeFiles/tars2node.dir/all] Error 2
make: *** [all] Error 2

**Comment by qiuxin** [comment]
你是在哪个路径下下载的代码？代码是否是否下载全了？编译需要使用的相关软件，是否都装了？

**Comment by hejinke** [comment]
git clone https://github.com/TarsCloud/TarsFramework.git
直接克隆仓库的

**Comment by hejinke** [comment]
按照这个教程来的，不过mysql是自己安装的，mysql的有设置好
https://tarsphp.gitbook.io/doc/huan-jing-da-jian/platform

**Comment by qiuxin** [comment]
git clone https://github.com/TarsCloud/TarsFramework.git  之后，进入TarsFramework目录，然后执行git submodule update --init --recursive 命令，确保代码都下载。再编译看看？

**Comment by qiuxin** [comment]
另外在确保mysql安装好的前提下，确保如下两个文件被正确修改:
/usr/local/TarsFramework/tarscpp下的CMakeLists.txt
/usr/local/TarsFramework 的CMakeLists.txt
中的：
set(MYSQL_DIR_INC "/usr/local/mysql/include")
set(MYSQL_DIR_LIB "/usr/local/mysql/lib")
修改成为：
set(MYSQL_DIR_INC "/usr/include/mysql")
set(MYSQL_DIR_LIB "/usr/lib64/mysql")

**Comment by qiuxin** [comment]
同时查看mysql版本，目前仅仅支持mysql 5.6，5.7。 不支持mysql 8.0

**Comment by qiuxin** [comment]
无其它问题关闭。
