### ISSUE TITLE
读取db配置

### ISSUE THREAD

**Issue by lizihuai** [TarsCloud/Tars#454]
### What language are you using?
 
 在配置文件中配置了db的配置,大致看了下tars读取配置的部分,好像没有读取db配置
### What operating system (Linux, Ubuntu, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
 golang
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
也许是我没找对地方,如果有读取这部分内容麻烦说下在哪里读取的.

**Comment by ETZhangSX** [comment]
读取配置部分分为两种
- 一种是拉取服务基本配置，在文件`TarsGo/tars/config.go`中定义，你看的应该是这部分
- 另一种是拉取自定义配置，可以拉取指定的自己上传到web管理平台上的配置，在文件`TarsGo/tars/util/conf/conf.go`中定义，具体用法可以参考同目录下的`conf_test.go`文件，服务中使用只要引入包 `"github.com/TarsCloud/TarsGo/tars/util/conf"` 即可使用；
