### ISSUE TITLE
HelloPrx是怎么生成的？

### ISSUE THREAD

**Issue by hypeaches** [TarsCloud/Tars#464]
### What language are you using?
 c++
 
### What operating system (Linux, Ubuntu, …) and version?
 centos7
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
 
请问HelloPrx是怎么产生的？
我使用/usr/local/tars/cpp/script/create_tars_server.sh app EchoServer Echo
创建了一个测试程序，但是写客户端的时候，没有EchoPrx，请文怎么产生这个类？

**Comment by ETZhangSX** [comment]
创建的服务的prx类都在tars文件生成的头文件中定义，需要使用对应的脚本进行转换
```sh
/usr/local/tars/cpp/tools/tars2cpp Echo.tars
```
会在当前目录下生成`Echo.h`，`EchoPrx`定义在里面

**Comment by hypeaches** [comment]
然而并没有啊
![图片](https://user-images.githubusercontent.com/35215878/65488605-1780d000-dedc-11e9-9a27-03ce7e2b932a.png)
参考demo代码，路径：
https://github.com/TarsCloud/TarsCpp/blob/d687aae51a016c313812c973ec75ab4cad7fbcaa/examples/QuickStartDemo/HelloServer/Client/main.cpp
![图片](https://user-images.githubusercontent.com/35215878/65488669-38492580-dedc-11e9-8c0f-8f4865ee99f0.png)

**Comment by ETZhangSX** [comment]
你发的截图中有定义了
`Echo.h: 509:        typedef tars::TC_AutoPtr<EchoProxy> EchoPrx;`
`EchoPrx`是`EchoProxy`的智能指针类型
