### ISSUE TITLE
安装mysql-devel时出现错误

### ISSUE THREAD

**Issue by MrTuesday1020** [TarsCloud/Tars#467]
**Linux version:** 
CentOS Linux release 7.6.1810 (Core)
**Mysql version:**  
mysql 5.7

按照[官方教程](https://github.com/TarsCloud/Tars/blob/master/Install.zh.md)使用yum安装mysql-devel时出现错误
```
# yum -y install  mysql-devel
Loaded plugins: fastestmirror
Repository base is listed more than once in the configuration
Repository updates is listed more than once in the configuration
Repository extras is listed more than once in the configuration
Repository centosplus is listed more than once in the configuration
Repository epel is listed more than once in the configuration
Repository epel-debuginfo is listed more than once in the configuration
Repository epel-source is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * base: mirrors.163.com
 * extras: mirrors.163.com
 * updates: mirrors.cn99.com
Resolving Dependencies
--> Running transaction check
---> Package mariadb101u-devel.x86_64 1:10.1.41-1.el7.ius will be installed
--> Processing Dependency: mariadb101u-libs(x86-64) = 1:10.1.41-1.el7.ius for package: 1:mariadb101u-devel-10.1.41-1.el7.ius.x86_64
--> Running transaction check
---> Package mariadb101u-libs.x86_64 1:10.1.41-1.el7.ius will be installed
--> Processing Dependency: mariadb101u-common(x86-64) = 1:10.1.41-1.el7.ius for package: 1:mariadb101u-libs-10.1.41-1.el7.ius.x86_64
--> Running transaction check
---> Package mariadb101u-common.x86_64 1:10.1.41-1.el7.ius will be installed
--> Processing Dependency: mariadb101u-config(x86-64) = 1:10.1.41-1.el7.ius for package: 1:mariadb101u-common-10.1.41-1.el7.ius.x86_64
--> Running transaction check
---> Package mariadb101u-config.x86_64 1:10.1.41-1.el7.ius will be installed
--> Processing Conflict: 1:mariadb101u-config-10.1.41-1.el7.ius.x86_64 conflicts mysql-community-server
--> Processing Conflict: 1:mariadb101u-common-10.1.41-1.el7.ius.x86_64 conflicts mysql-community-common
--> Processing Conflict: 1:mariadb101u-libs-10.1.41-1.el7.ius.x86_64 conflicts mysql-community-libs-compat
--> Processing Conflict: 1:mariadb101u-libs-10.1.41-1.el7.ius.x86_64 conflicts mysql-community-libs
--> Finished Dependency Resolution
Error: mariadb101u-common conflicts with mysql-community-common-5.7.27-1.el7.x86_64
Error: mariadb101u-libs conflicts with mysql-community-libs-compat-5.7.27-1.el7.x86_64
Error: mariadb101u-config conflicts with mysql-community-server-5.7.27-1.el7.x86_64
Error: mariadb101u-libs conflicts with mysql-community-libs-5.7.27-1.el7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

尝试了[这个方法](https://github.com/TarsCloud/Tars/issues/437)，问题依旧重现。

any help or suggestion?

**Comment by qiuxin** [comment]
你的系统中安装了mariadb？  mariadb和MySQL冲突。卸载mariadb再试试

**Comment by qiuxin** [comment]
如果是学习或者验证环境，建议格式化系统。 
然后通过如下几行命令，就可以成功安装MySQL
## install mysql 5.7
wget https://repo.mysql.com//mysql80-community-release-el7-3.noarch.rpm
rpm -ivh mysql80-community-release-el7-3.noarch.rpm
yum-config-manager --disable mysql80-community
yum-config-manager --enable mysql57-community
yum install -y mysql-community-server
yum install -y mysql-devel

**Comment by qiuxin** [comment]
https://github.com/qiuxin/Tars/tree/master/shellDeploy 这个文件夹中有一键安装部署的脚本，供你参考, 详见其中的introduction.md文件。

**Comment by MrTuesday1020** [comment]
> 如果是学习或者验证环境，建议格式化系统。
> 然后通过如下几行命令，就可以成功安装MySQL
> 
> ## install mysql 5.7
> wget https://repo.mysql.com//mysql80-community-release-el7-3.noarch.rpm
> rpm -ivh mysql80-community-release-el7-3.noarch.rpm
> yum-config-manager --disable mysql80-community
> yum-config-manager --enable mysql57-community
> yum install -y mysql-community-server
> yum install -y mysql-devel

mariadb没有安装过哈 这个方法试过了也不行

**Comment by qiuxin** [comment]
我在CentOS上刚实验过，安装成功， 没有任何问题

**Comment by qiuxin** [comment]
你把你的操作日志，提供一下?

**Comment by qiuxin** [comment]
> > 如果是学习或者验证环境，建议格式化系统。
> > 然后通过如下几行命令，就可以成功安装MySQL
> > ## install mysql 5.7
> > wget https://repo.mysql.com//mysql80-community-release-el7-3.noarch.rpm
> > rpm -ivh mysql80-community-release-el7-3.noarch.rpm
> > yum-config-manager --disable mysql80-community
> > yum-config-manager --enable mysql57-community
> > yum install -y mysql-community-server
> > yum install -y mysql-devel
> 
> mariadb没有安装过哈 这个方法试过了也不行

你需要重装系统，选择一个干净的环境重试。 另外，看你的使用的系统是否默认安装了mariadb

**Comment by MrTuesday1020** [comment]
@qiuxin 
从源码安装MySQL就避开了这个问题。

Anyway, thanks.
