### ISSUE TITLE
求服务端自定义上报demo

### ISSUE THREAD

**Issue by hypeaches** [TarsCloud/Tars#468]
### What language are you using?
 C++
 
### What operating system (Linux, Ubuntu, …) and version?
 centos7
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
 
默认的服务监控只有总流量和平均耗时、超时率、异常率等信息，但是还想看到每个接口的qps、异常信息等，这些需要自定义上报吧。

如何在服务中上报信息，求详细一点的demo及说明文档，比如，示例程序
https://github.com/TarsCloud/TarsCpp/blob/13c01023ae8df34159549ce88546bbd84159855b/examples/QuickStartDemo/HelloServer/HelloImp.cpp
int HelloImp::testHello(const std::string &sReq, std::string &sRsp, tars::TarsCurrentPtr current)
{
    TLOGDEBUG("HelloImp::testHellosReq:"<<sReq<<endl);
    sRsp = sReq;
    return 0;
}
在testHello接口中，该如何上报自定义数据？

**Comment by bartdong** [comment]
你好请问是否这个问题已经解决，是的话您可以分享一下您的经验，然后关闭这个issue，方便其他人更容易解决这个问题。十分感谢~

**Comment by ruanshudong** [comment]
https://tarscloud.github.io/TarsDocs/an-li/tarscpp/tars_cpp_user_guide.html

请参考这个文档中的统计上报这部分.
