### ISSUE TITLE
 How to view user-defined submission information

### ISSUE THREAD

**Issue by hypeaches** [TarsCloud/Tars#469]
User defined escalation information has been written to MySQL Library
![图片](https://user-images.githubusercontent.com/35215878/65748454-8fe2cd80-e136-11e9-8a50-86989e0a7923.png)
But how to view the reported information on the management platform?
My services, such as echoserver (reported service), tarsproperty and tarsstat, cannot be seen. How can I filter out these customized reported information?
![图片](https://user-images.githubusercontent.com/35215878/65748523-c15b9900-e136-11e9-8ad9-476a7138bff3.png)

**Comment by bartdong** [comment]
看一下EchoServer服务下，特性监控页，有没有你想要的结果

**Comment by hypeaches** [comment]
![图片](https://user-images.githubusercontent.com/35215878/65826017-a4e36c00-e2b0-11e9-9abd-67a940b34090.png)
特性过滤”test1“有数据了，但是我的test1上报的数据是6个，但是特性监控里面过滤出来的test1只有总流量，没有其他。而且总流量应该是服务器整机的流量吧，就是服务没有流量但是yum安装程序，总流量也会上升的。
以及特性监控里的特征值是什么意思？还有就是过滤字段中的”策略“对应于上报数据的什么？

**Comment by bartdong** [comment]
策略对应你上报里的policy，也就是Avg、Count、distr那些，看你上面的表count这个值也蛮大的，可以确认一下这个策略上报的数据是否正确。

**Comment by hypeaches** [comment]
之所以Count很大，是因为这是一个简单的Echo服务，服务中对支持的六个统计值进行了上报，所以很大。代码大概是这样的
`
int EchoImp::testHello(const std::string & sReq,std::string &sRsp,tars::TarsCurrentPtr current)
{
    TLOGDEBUG("EchoImp::testHello:"<<sReq<<endl);
    sRsp = "hello: " + sReq;

    PropertyReporter::instance()->report(1);
    TARS_NOTIFY_NORMAL("testHello-test1 info");
    TARS_NOTIFY_WARN("testHello-test1 warning");
    TARS_NOTIFY_ERROR("testHello-test1 error");
    return 0;
}
`
PropertyReporter代码
`
PropertyReporter* PropertyReporter::instance() {
    static PropertyReporter reporter;
    return &reporter;
}
void PropertyReporter::init() {
    std::vector<int> v;
    v.push_back(10);
    v.push_back(30);
    v.push_back(50);
    v.push_back(80);
    v.push_back(100);
    reporter_ptr_ = Application::getCommunicator()->getStatReport()->createPropertyReport("test1",
        PropertyReport::sum(),
        PropertyReport::avg(),
        PropertyReport::count(),
        PropertyReport::max(),
        PropertyReport::min(),
        PropertyReport::distr(v));
}
void PropertyReporter::report(int val) {
    reporter_ptr_->report(val);
}
`
按照我的理解，六个统计量的含义分别是
avg()   上报的所有数据求算数平均
min()   上报的所有数据中的最小值
max()  上报的所有数据中的最大值
distr()  上报的所有数据中，按照v进行分布统计
sum()  上报的所有数据求和
count()上报的总次数
请问我的理解对吗？还有，如果想知道一个接口的qps，监控上怎么看？支持的六个统计量好像没有支持qps监控的

**Comment by ruanshudong** [comment]
特性监控页面, 点击特性就可以看到上报的数据和曲线了
