### ISSUE TITLE
建议提示语改一下位置

### ISSUE THREAD

**Issue by hypeaches** [TarsCloud/Tars#471]
web管理平台的提示语放的位置实在是太碍事了
![图片](https://user-images.githubusercontent.com/35215878/65830178-b98b2880-e2df-11e9-9d06-f03b7dd6ff33.png)
像一贴膏药一样贴在了上方，且覆盖了“服务管理”、“运维管理”两个功能，建议在底端或者右侧专门放一个区域，显示操作提示

**Comment by KatharineOzil** [comment]
感谢 hypeaches 的提问。该问题为非功能性需求，已转达给相关研发团队决策，请持续关注后续版本更新。
同时，我们非常欢迎您提交PR贡献代码，一起构建更好的 TarsCloud 社区。
