### ISSUE TITLE
安装文档缺少导入web表db_tars_web.sql的步骤

### ISSUE THREAD

**Issue by ShowYouShowme** [TarsCloud/Tars#474]
### What language are you using?
 C++
 
### What operating system (Linux, Ubuntu, …) and version?
 
 centos7
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
 gcc version 4.8.5
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

Install.zh.md 安装web管理系统 部分，缺少了导入web的表db_tars_web.sql

**Comment by ETZhangSX** [comment]
需要使用的模型都在`TarsCloud/TarsWeb/app/dao/db`下的`db_tars_models`和`db_tars_web_models`中定义了，在`TarsCloud/TarsWeb/app/dao/db/index.js`中使用了`sequelize`模块，通过调用`sequelize.sync()`，如下，将模型同步到数据库，会自动建立对应的表，无需在安装时导入

[TarsWeb/app/dao/db/index.js](https://github.com/TarsCloud/TarsWeb/blob/2f01316db6d51d0c6c6410a212c51d550a529373/app/dao/db/index.js#L77)

```js
77 let tableObj = {}; 
78 let dbModelsPath = __dirname + '/' + database + '_models'; 
79 let dbModels = fs.readdirSync(dbModelsPath); 
80 dbModels.forEach(function (dbModel) { 
81 	let tableName = dbModel.replace(/\.js$/g, ''); 
82 	tableObj[_.camelCase(tableName)] = sequelize.import(dbModelsPath + '/' + tableName); 
83 	// tableObj[_.camelCase(tableName)].sync({ alter: true }); 
84 	tableObj[_.camelCase(tableName)].sync(); 
85 }); 
```
