### ISSUE TITLE
tc_timeout_queue_new.h中的class类没有继承taf::TC_ThreadMutex等锁类。编译不过。

### ISSUE THREAD

**Issue by daisyl0** [TarsCloud/Tars#475]
### What language are you using?
 
 cpp
### What operating system (Linux, Ubuntu, …) and version?
 
 linux
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

tc_timeout_queue_new.h中的class类没有继承taf::TC_ThreadMutex等锁类。但用到了TC_LockT<TC_ThreadMutex> lock(*this);。编译不过。

**Comment by ruanshudong** [comment]
这个类故意是无锁的, 为了提高效率, 你可以用tc_timeout_queue代替, 这个带锁

**Comment by daisyl0** [comment]
> 这个类故意是无锁的, 为了提高效率, 你可以用tc_timeout_queue代替, 这个带锁

东爷好。我想用一个tc_timeout_queue没有的功能，又用了generateId。模板就编不过啦。我后来自己改了改。
