### ISSUE TITLE
tar 上次的发布版本还是去年发布的，我应该用哪一个tar版本部署呢？

### ISSUE THREAD

**Issue by Jamlee** [TarsCloud/Tars#478]
tar 上次的发布版本还是去年发布的，我应该用哪一个tar版本部署呢？去年发布的v1.6.0. 想把 tar 用于生产，如何进行tar发行版本选择呀？

**Comment by ruanshudong** [comment]
https://github.com/TarsCloud/TarsDocker/blob/master/README.zh.md

**Comment by ruanshudong** [comment]
可以直接用docker部署, 以后框架升级简单一些
