### ISSUE TITLE
Tars和k8s结合的问题

### ISSUE THREAD

**Issue by TCZWJ** [TarsCloud/Tars#481]
想请问下，Tars的容器在k8s中发布，因为Tars不支持域名发布，如果想要扩容，有何方便的办法？

**Comment by ruanshudong** [comment]
啥叫不支持域名发布?

**Comment by TCZWJ** [comment]
> 啥叫不支持域名发布?

在tars的发布页面上，只能填写ip地址啊，填写其他字符串就报非法。

**Comment by ruanshudong** [comment]
是nodejs的版本web管理平台吧?

**Comment by TCZWJ** [comment]
> 是nodejs的版本web管理平台吧?
是的，有什么好办法吗？之前好像是说tars会向k8s做适配，不知道下个版本能不能见到？

**Comment by ruanshudong** [comment]
你们现在是怎么使用的,能大概描述一下么, 才知道怎么修改更合适

**Comment by ruanshudong** [comment]
如果只是说这里改成域名, 其实很容易修改, 试着改了一下, 貌似跑起来没啥问题了, 如果能满足的需求, 可以先push一个版本你用着

**Comment by ruanshudong** [comment]
新版本web已经支持域名了, 有需要可以试一试.
