### ISSUE TITLE
Percona mysql编译不通过

### ISSUE THREAD

**Issue by myuid** [TarsCloud/Tars#483]
我在Centos7通过yum安装了percona mysql，在进行第二步Tars C++开发环境(源码安装框架必备)编译到Linking CXX executable ../servers/tarsconfig/bin/tarsconfig时，会出现与libmysqlclient.a相关的许多错误，例如undefined reference to `SSL_get_current_cipher\'，安装oracle mysql-community的就没有问题。

**Comment by Jamlee** [comment]
文档提供了一个mysql的安装例子, 如果不想自己编译的话。不知道是否对您有帮助
```
wget -i -c http://dev.mysql.com/get/mysql57-community-release-el7-10.noarch.rpm \
  && yum -y install mysql57-community-release-el7-10.noarch.rpm \
  && yum -y install  mysql-devel mysql-community-client

mkdir /usr/local/mysql && ln -sf /lib64/mysql /usr/local/mysql/lib && ln -sf /usr/include/mysql  /usr/local/mysql/include
```

**Comment by myuid** [comment]
按照文档我把CMakeLists在${source_folder}/TarsFramework/和${source_folder}/TarsFramework/tarscpp/ 目录下同名文件修改文件中上述路径为本机mysql开发库的路径，也没有用。Percona mysql不可以，删除后重装的oracle mysql57-community就可以。

**Comment by ETZhangSX** [comment]
因为`Percona mysql`中对应的库改名了，为`libperconaserverclient.so`，可以创建一个软链接来修复

**Comment by myuid** [comment]
yum install -y Percona-Server-server-57 Percona-Server-client-57 Percona-Server-devel-57
find / -name libperconaserverclient.so没找到
libmysqlclient.a在/usr/lib64/mysql/里
还是安装mysql57-community好了。
谢谢各位。
