### ISSUE TITLE
当spring 容器启动出错时，需要jvm退出

### ISSUE THREAD

**Issue by zhangyaoshu** [TarsCloud/Tars#489]
###  jdk1.8

 
在spring boot启动中增加SpringApplicationRunListener，代码片段如下：
 ```
    public void failed(ConfigurableApplicationContext context, Throwable exception) {
            //todo xxxx   
            System.exit(-1);
    }
   ```

增加META-INF/spring.factories 文件
内容如下：
org.springframework.boot.SpringApplicationRunListener=com.tars.spring.xxx.SpringApplicationRunListener

**Comment by ruanshudong** [comment]
是需要修改代码?可以直接发一个pull request?

**Comment by TimmyYu** [comment]
tarsJava1.7的版本已经合并这个提升了
