### ISSUE TITLE
docker部署tarsweb失败，镜像源有问题

### ISSUE THREAD

**Issue by TomatoMr** [TarsCloud/Tars#492]
![image](https://user-images.githubusercontent.com/15191500/72047551-c0213700-32f5-11ea-978f-f3799f921b66.png)

**Comment by ruanshudong** [comment]
已经更新, 请再试一试, 可以参考文档
https://github.com/TarsCloud/TarsDocs/blob/master/rumen/an-zhuang/docker.md

**Comment by TomatoMr** [comment]
> 已经更新, 请再试一试, 可以参考文档
> https://github.com/TarsCloud/TarsDocs/blob/master/rumen/an-zhuang/docker.md

感谢，但我按照这个文档部署之后，没有基础服务，发布不了服务。https://github.com/TarsCloud/Tars/issues/494

**Comment by ruanshudong** [comment]
没太理解 你可以加我qq: 39067484, 我看看啥原因


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TomatoMr"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月14日(星期二) 中午11:05
收件人:&nbsp;"TarsCloud/Tars"<Tars@noreply.github.com&gt;;
抄送:&nbsp;"Jarod"<ruanshudong@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [TarsCloud/Tars] docker部署tarsweb失败，镜像源有问题 (#492)



 
已经更新, 请再试一试, 可以参考文档
 https://github.com/TarsCloud/TarsDocs/blob/master/rumen/an-zhuang/docker.md
  
感谢，但我按照这个文档部署之后，没有基础服务，发布不了服务。#494
