### ISSUE TITLE
mysql5.7安装遇到问题

### ISSUE THREAD

**Issue by qq690712575** [TarsCloud/Tars#493]
用的是腾讯云的mysql5.7,安装框架的时候执行到/usr/local/tars/cpp/deploy/tars-install.sh 这个脚本的时候就出错了，
下面如果是mysql5.7版本，但是不执行创建用户，再执行授权会出错啊；
exec_mysql_script "grant all on *.* to 'tars'@'%' identified by 'tars2015' with grant option;"

mysql version is: 5.7.18-txsql-log
 2020-01-10 18:24:13 5.7版本224行 
 2020-01-10 18:24:13 5.+版本228行 
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000) at line 1: Access denied for user 'root'@'%' (using password: YES)
 2020-01-10 18:24:13 exec_mysql_script grant all on db_cache_web.sql db_tars.sql db_tars_web.sql db_user_system.sql tars_node_init.sql tars_servers_master.sql tars_servers.sql upgrade2IPv6.sh to 'tars'@'%' identified by 'tars2015' with grant option;, ret: 1 
 2020-01-10 18:24:13 grant error, exit. 

===========================
echo "mysql version is: $MYSQL_VER"

if [ `echo $MYSQL_VER|grep ^8.` ]; then
    exec_mysql_script "CREATE USER 'tars'@'%' IDENTIFIED WITH mysql_native_password BY 'tars2015';"
    exec_mysql_script "GRANT ALL ON *.* TO 'tars'@'%' WITH GRANT OPTION;"
    exec_mysql_script "CREATE USER 'tars'@'localhost' IDENTIFIED WITH mysql_native_password BY 'tars2015';"
    exec_mysql_script "GRANT ALL ON *.* TO 'tars'@'localhost' WITH GRANT OPTION;"
    exec_mysql_script "CREATE USER 'tars'@'${HOSTIP}' IDENTIFIED WITH mysql_native_password BY 'tars2015';"
    exec_mysql_script "GRANT ALL ON *.* TO 'tars'@'${HOSTIP}' WITH GRANT OPTION;"
fi

if [ `echo $MYSQL_VER|grep ^5.7` ]; then
    #exec_mysql_script "set global validate_password_policy=LOW;"
    LOG_INFO "5.7版本224行" 
fi

if [ `echo $MYSQL_VER|grep ^5.` ]; then
    LOG_INFO "5.+版本228行" 
    exec_mysql_script "grant all on *.* to 'tars'@'%' identified by 'tars2015' with grant option;"
    if [ $? != 0 ]; then
        LOG_DEBUG "grant error, exit." 
        exit 1
    fi

    exec_mysql_script "grant all on *.* to 'tars'@'localhost' identified by 'tars2015' with grant option;"
    exec_mysql_script "grant all on *.* to 'tars'@'$HOSTIP' identified by 'tars2015' with grant option;"
    exec_mysql_script "flush privileges;"
fi

**Comment by ruanshudong** [comment]
我回头买个cdb试一试

**Comment by ruanshudong** [comment]
已经改了, 支持腾讯云cdb了
