### ISSUE TITLE
docker部署之后没有基础服务

### ISSUE THREAD

**Issue by TomatoMr** [TarsCloud/Tars#494]
你好，我按照这个文档[https://github.com/TarsCloud/TarsDocs/blob/master/rumen/an-zhuang/docker.md](https://github.com/TarsCloud/TarsDocs/blob/master/rumen/an-zhuang/docker.md)部署，之后部署成功，没有那些基础服务，发布不了应用和服务。
![image](https://user-images.githubusercontent.com/15191500/72310672-44403980-36bd-11ea-82b8-5651a8b27785.png)

**Comment by ruanshudong** [comment]
docker已经更新.
