### ISSUE TITLE
zombie process,no keep alive msg for 60 seconds

### ISSUE THREAD

**Issue by wangqingfan** [TarsCloud/Tars#498]
### What language are you using?
 Java
 
### What operating system (Linux, Ubuntu, …) and version?
 1.0.1
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 1.8.0_65
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
Every once in a while, the tars console will report an error and restart my project. The error message is as follows:
[alarm] zombie process,no keep alive msg for 60 seconds

**Comment by ruanshudong** [comment]
this message means: 
All servant threads in your server have been block(you should check what happened?), they can't report heartbeat to tarsnode , so after 60 seconds, tarsnode kill the server.
