### ISSUE TITLE
mysql 权限问题 -- 需增加grant权限

### ISSUE THREAD

**Issue by pingfang-tx** [TarsCloud/Tars#502]
https://tarscloud.gitbook.io/tarsdocs/rumen/installation/source#3-5-mysql-quan-xian-wen-ti

这里不光是需要有文档中列出的权限，还需要有grant权限，既带上 with grant option， 因为脚本中会给tars用户执行grant

**Comment by ruanshudong** [comment]
文档增加了grant权限说明, thx!
