### ISSUE TITLE
docker 虚拟网络问题

### ISSUE THREAD

**Issue by pingfang-tx** [TarsCloud/Tars#503]
https://tarscloud.gitbook.io/tarsdocs/rumen/installation/docker
这里使用虚拟网络启动docker的方式，是不是不能支持多个物理机node的场景，因为其它物理机无法联通此虚拟网络
文档中可以增加通过host方式启动docke的操作说明

**Comment by ruanshudong** [comment]
可以docker使用--net=host启动, 物理机使用tarsnode的模式, 这样方便框架升级
