### ISSUE TITLE
接口测试报错

### ISSUE THREAD

**Issue by pingfang-tx** [TarsCloud/Tars#504]
接口测试报错，提示 Cannot read property 'response' of undefined
接口响应结构体为：
struct TBAcctAssetProofGetListRsp
{
    0 require string offset;      
    1 require vector<TAcctAssetProofItem> acct_asset_proof_list;  
};

 struct TAcctAssetProofItem
{
    0 require int proof_id;                    
    1 require double valid_amount;             
    2 require string check_time;               
    3 require string valid_date_end;           
    4 require string valid_date_begin;         
    5 require string file_url;                 
    6 require string reason_desc;              
    8 require EAcctAssetProofState state;      
};

web日志：
InfTestController.js:43|[interfaceDebug]: TypeError: Cannot read property 'response' of undefined\n    at Object.InfTestService.debug (/usr/local/app/web/app/service/infTest/InfTestService.js:43:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Object.InfTestController.interfaceDebug (/usr/local/app/web/app/controller/infTest/InfTestController.js:32:14)\n    at async /usr/local/app/web/app/router/index.js:36:4\n    at async module.exports (/usr/local/app/web/app/midware/noCacheMidware.js:24:2)\n    at async /usr/local/app/web/app/midware/paramsMidware.js:86:4\n    at async /usr/local/app/web/app/midware/paramsMidware.js:45:3\n    at async /usr/local/app/web/app/midware/apiMidware.js:26:4\n    at async /usr/local/app/web/app.js:115:3\n    at async static (/usr/local/app/web/node_modules/koa-static-router/index.js:70:13)\n    at async pathname (/usr/local/app/web/node_modules/yami-sso-client/lib/koa.js:52:13)\n    at async /usr/local/app/web/app.js:100:2\n    at async module.exports (/usr/local/app/web/app/midware/localeMidware.js:49:2)  ","timestamp":"2020-03-22 13:46:00.195"}

**Comment by ruanshudong** [comment]
@zouchengzhuo check this bug

**Comment by zouchengzhuo** [comment]
问题的原因是接口测试调用失败， 返回错误提示时失败，已在tars-web 最新master分支中修复。
