### ISSUE TITLE
 3001 port problem

### ISSUE THREAD

**Issue by Douwanna** [TarsCloud/Tars#508]
_(Here's today's Q&A)_
### Q:
I installed the framework according to the documentation.
![图片](https://user-images.githubusercontent.com/33800612/78383910-cc264780-760b-11ea-9e69-dd8c51953072.png)
![图片](https://user-images.githubusercontent.com/33800612/78383916-cdf00b00-760b-11ea-93e7-55059fc701c4.png)
But there is something wrong with http://172.31.154.218:3000/ . This is the Ali's intranet IP address which can't be accessed directly through Internet IP.
### A:
You can use Nginx as a proxy web to bind all IP, the Internet can be turned around. Are you sure that there's port 3001 for Internet access?
### Q:
Oh,port 3000 is opened while port 3001 isn’t opened. It works!!!thx!
![图片](https://user-images.githubusercontent.com/33800612/78384136-350dbf80-760c-11ea-9944-587dc93eab7a.png)

**Comment by franklee0817** [comment]
Note: Tars web is already bound to 0.0.0.0. Nginx proxy is not necessary.
