### ISSUE TITLE
Script compatibility issues

### ISSUE THREAD

**Issue by Douwanna** [TarsCloud/Tars#509]
_(Here's today's Q&A)_
### Q：
When running tars on Ubuntu 16.04.I wanna know why the internal error of the tarslog package system exists. 
![图片](https://user-images.githubusercontent.com/33800612/78384771-62a73880-760d-11ea-96bc-6f0b0667b32b.png)
![图片](https://user-images.githubusercontent.com/33800612/78384774-65099280-760d-11ea-8610-a05eff6cfe3a.png)
![图片](https://user-images.githubusercontent.com/33800612/78384785-68048300-760d-11ea-8b61-f84e4a0d9246.png)
### A:
 Operation and maintenance management, which has a framework check, click to see.
### Q:
![图片](https://user-images.githubusercontent.com/33800612/78384833-7bafe980-760d-11ea-958f-7017690f1e9f.png)
### A:
The frame didn't start.Is the corresponding process of tar up under `ps grep`?
### Q:
There's something wrong with the script.
![图片](https://user-images.githubusercontent.com/33800612/78384913-a4d07a00-760d-11ea-9867-0e9a183efade.png)
![图片](https://user-images.githubusercontent.com/33800612/78384911-a306b680-760d-11ea-9c6f-e0f35aaddf0c.png)
I also useed bash to execute the startup script.It resulted the same.
![图片](https://user-images.githubusercontent.com/33800612/78385054-d5b0af00-760d-11ea-897d-406fe1727e68.png)
![图片](https://user-images.githubusercontent.com/33800612/78385051-d3e6eb80-760d-11ea-9dbb-c1584572fd78.png)
### A:
Try **centos7**,please.It runs more stable. There are still problems with script compatibility.

**Comment by franklee0817** [comment]
We will fix the problem in the install shell while running on ubuntu.
