### ISSUE TITLE
Tars服务下，C++服务模块可以直接通信C#服务模块吗？

### ISSUE THREAD

**Issue by lanyutc** [TarsCloud/Tars#51]
如果可以的话是否有样例可以参考？

**Comment by helloopenworld** [comment]
tars是个rpc框架，设计就是为了多种语言互通。只要使用的都是tars协议，是可以互通的。。

**Comment by lanyutc** [comment]
有Tars环境下，C#使用的简单example或者tutorial吗？

**Comment by ElderJames** [comment]
https://github.com/tarsnet 支持C#的开发工作已经开始
