### ISSUE TITLE
Question: ServantProxy::invoke timeout:3000,servant:tars.tarspatch.PatchObj

### ISSUE THREAD

**Issue by funkyLover** [TarsCloud/Tars#510]
每次部署等待3秒就会报错, 但是只找到页面上的报错信息, 在 tars.tarspatch.log 没有看到报错

还请看一下, 如果报错信息不足还请指导下该到哪里获取, 目前对 tars 了解比较有限

### What language are you using?
 
Nodejs
 
### What operating system (Linux, Ubuntu, …) and version?
 
```bash
MacOS 10.15.3 
Docker Desktop 2.2.0.3
Docker Engine 19.03.5

tars
- tarscloud/framework:stable
- tarscloud/tars-node:stable 
```

### What runtime / compiler are you using (e.g. jdk version or version of gcc)

```bash
node -v
v10.15.3
npm -v
6.4.1
```
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

子任务ID | 应用 | 服务 | 节点 | 命令 | 开始时间 | 结束时间 | 状态 | 执行信息
-- | -- | -- | -- | -- | -- | -- | -- | --
70429a44b12246a6a68b037b355e7b82 | JV | ICAdmin | 172.25.0.5 | patch_tars | 2020-04-06 16:58:34 | 2020-04-06 16:58:37 | EM_I_FAILED | [ServantProxy::invoke timeout:3000,servant:tars.tarspatch.PatchObj,func:preparePatchFile,adapter:tcp -h 172.25.0.3 -p 18793 -t 60000,reqid:16]

**Comment by ruanshudong** [comment]
可以在运维管理, 框架检查里面检查一下,看看框架服务状态是否都正常
