### ISSUE TITLE
接口测试报错

### ISSUE THREAD

**Issue by pingfang-tx** [TarsCloud/Tars#514]
struct TA
    {
        0   optional    string      extra = "{}";                       // 附加参数
        1   optional    string      create_at = "1001-01-01 00:00:00";  // 订阅时间
    };

接口测试上传tars文件时，如果字段设置了默认值，会报错，去掉默认值就ok了，麻烦看下~

**Comment by zouchengzhuo** [comment]
协议解析代码问题，已修复
