### ISSUE TITLE
类库以及相关函数的说明书有么

### ISSUE THREAD

**Issue by sjmr201107** [TarsCloud/Tars#521]
### What language are you using?
 
 C++
### What operating system (Linux, Ubuntu, …) and version?
 
 linux
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 gcc 4.8
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
没有错误，只是没有找到c++中关于tars类库以及相关函数的说明书，用起来还不是很方便。

**Comment by ruanshudong** [comment]
一直没有时间写,  基础类都在util目录下,  rpc相关的都在servant下

**Comment by sjmr201107** [comment]
好的
