### ISSUE TITLE
tars-java中上报property信息时req.queue.waitingtime这个属性默认是-2147483648

### ISSUE THREAD

**Issue by itcheng2019** [TarsCloud/Tars#537]
tars-java中上报property信息时req.queue.waitingtime这个属性默认是-2147483648，这样的话在tars-web中访问特性监控时就会显示失真，永远都看不到数据
![image](https://user-images.githubusercontent.com/47874255/81649353-c28dcc00-9462-11ea-81ff-3661c267e6b5.png)

**Comment by TimmyYu** [comment]
这一部分是求最大值时，默认的一个最小值 。可以把数据单独按策略查看即可（max,min），后续java的property上报若是没有符值的情况下。不会再上报这个值
