### ISSUE TITLE
[proposal] TARS+K8S方案

### ISSUE THREAD

**Issue by defool** [TarsCloud/Tars#539]
## 问题与思考
目前TARS服务部署到k8s暂时还没稳定可靠的方案，主要问题是TARS框架的部分模块偶合度较高，且TARS的部分能力与k8s重合，不利于整合，以下列出了重合的功能：
- 名字服务：相比于k8s的service/ingress方式，TARS在客户端容灾/SET模型功能上有更强的能力，考虑TARS的能力更强，而使用k8s的名字服务会给TARS带来一定的改造成本，建议保留TARS的名字服务能力。
- 服务上线与注册：k8s使用yaml文件来描述服务，k8s需要在TARS-web平台上操作，k8s的方式更方便与第三方平台对接。
- 节点管理：TARS目前使用人工管理方式，比较落后，应尽量用于k8s的自动扩缩容能力。
- 版本发布与管理：TARS使用发布包方式，k8s使用docker镜像方式，前者依赖TARSnode，k8s依赖kubelet和docker仓库。如果在k8s+TARS方方案中还使用发布包方式，需要在容器里安装TARSnode，还要同时使用2套版本管理系统，所以最好是将TARS程序打包到镜像中，使用镜像发布TARS服务。
- 服务重启。k8s使用重建容器方式来重启服务，TARS使用重启进程方式，k8s的方式会导致容器内新增或变更文件丢失，但是也提倡了无状态容器的理念，所以2种方式各有优缺点。
- 关流量。k8s不支持关流量但是不停止服务，TARS的这个能力应该保留，方便快速屏蔽问题节点再排查问题的场景。

### 方案目标
- 保持TARS原生的开发框架能力
- 保留TARS的名字服务能力
- 尽量使用原生k8s/docker的能力
- 支持TARS的名字服务自动注册和配置删除
- 支持原有TARS服务平滑迁移到k8s等容器平台
- 无侵入性设计，与运行环境无偶合关系
  
### 实现方案
- 在TARSregistry增加了3个接口，用于TARS名字的自动注册/心跳上报和节点下线。对于长期未上报心跳的节点自动删除。
- 提供一个TARScli命令行工具，用于支持TARS服务的自动化部署，工具具备以下能力：
  - 生成服务启动配置：可指定配置模板文件，并将配置合并到服务的启动配置文件中，配置模板可通过k8s的configmap来管理和发布到容器中。这个命令可以在服务启动前运行。
  - 监控服务状态和上报心跳：第一次检测成功会自动注册服务（registry新接口），可以通过端口监控或TARS_ping方式检查服务状态，然后上报服务的状态（registry新接口）。这个命令可以在k8s的readinessProbe中指定。
  - 服务退出命令：删除在registry对应的配置（registry新接口）。可指定删除服务后的等待时间，实现无损变更。这个命令可以在k8s的prestop脚本中运行，实现节点的自动下线。
  - 执行notify命令，结合k8s的exec命令可远程执行自定义命令等。
  
## TarsWeb

需要新开发一个版本，在原有基础上，去掉服务重启/下线等功能，仅保留关流量/配置管理和监控等功能。

## 与Service Mesh/Istio

因为TARS已具备service mesh的很多能力，将原有TARS服务改成mesh方式意义不大。Istio中的可以基于指定规则来灰度新版本是不错的功能，TARS后续的版本可以考虑支持这样的能力。

**Comment by ruanshudong** [comment]
我们有一个内部的方案,和你这个proposal基本一致,  等这阶段网关等搞完, 我拉个群, 可以一起讨论一下, 把这个方案贡献出来

**Comment by YMChenLiye** [comment]
这个方案是不是就将tarsnode给干掉了？
没有tarsnode好像就没法通过管理平台给AdminServant发`自定义命令`，`设置日志级别`这些功能了吧？

是不是可以把tarsnode作为sidecar和业务进程一起部署，这样tarsRegister也不需要修改了。

**Comment by adugeek** [comment]
> 这个方案是不是就将tarsnode给干掉了？
> 没有tarsnode好像就没法通过管理平台给AdminServant发`自定义命令`，`设置日志级别`这些功能了吧？
> 
> 是不是可以把tarsnode作为sidecar和业务进程一起部署，这样tarsRegister也不需要修改了。

目前的方案 是 对 tarsnode 做了轻量化改造(还不够轻), 与业务进程放在一个 镜像里面作为守护进程，以及自定义命令传输通道

**Comment by defool** [comment]
已开源：https://github.com/TarsCloud/K8STARS
