### ISSUE TITLE
stat上报监控问题

### ISSUE THREAD

**Issue by marklightning** [TarsCloud/Tars#54]
issue from 友缘@QQ

comm.setProperty("stat", "tars.tarsstat.StatObj");
            StatReport * pReport = comm.getStatReport();
            if (pReport)
            {
                statPrx = pReport->getStatPrx();
            }

                   std::vector<tars::StatSampleMsg> vecMsg;
                    tars::StatSampleMsg msg;
                    msg.interfaceName = "test_stat";
                    iRet = statPrx->reportSampleMsg(vecMsg);
                    cout << "stat|iRet[" << i << "]:" << iRet << endl;
我客户端在通信器设置了stat，但并没有在管理页面上看到服务端被调用过的监控记录。上面是我测试通信器的统计上报，通过查看打印出来的日志和stat的日志，可以确认stat是可以连上的，还需要设置什么才能成功让我的客户端上报调用服务端的统计呢？

**Comment by jokenchang** [comment]
感谢Mark帮我整理的问题，希望尽快答复哈。。。
以下是我的客户端的源代码，我希望能在页面上看到JokenTestServer被调用的监控数据,目前是没有任何上报数据的：
       comm.stringToProxy("Office.JokenTestServer.HelloObj", prx);
        comm.setProperty("stat", "tars.tarsstat.StatObj");
        StatFPrx statPrx;
        try
        {
            StatReport * pReport = comm.getStatReport();
            if (pReport)
            {
                statPrx = pReport->getStatPrx();
            }

            string sReq("hello world");
            string sRsp("");

            int i = 0;
            while (i++ < 10)
            {
                try
                {
                    int iRet = prx->test(sReq, sRsp);
                    cout << "iRet[" << i << "]:" << iRet << ", sReq:" << sReq << ", sRsp:" << sRsp << endl;

                    /* 这块代码测试是可以连上stat服务的
                    if (statPrx)
                    {
                        std::vector<tars::StatSampleMsg> vecMsg;
                        tars::StatSampleMsg msg;
                        msg.interfaceName = "test_stat";
                        iRet = statPrx->reportSampleMsg(vecMsg);
                        cout << "stat|iRet[" << i << "]:" << iRet << endl;
                    }
                    */
                }
                catch (exception &ex)
                {
                    cerr << "ex:" << ex.what() << endl;
                }
                catch (...)
                {
                    cerr << "unknown exception." << endl;
                }
            }

        }
        catch (exception &ex)
        {
            cerr << "ex:" << ex.what() << endl;
        }
        catch (...)
        {
            cerr << "unknown exception." << endl;
        }
    }
    catch (exception& e)
    {
        cerr << "exception:" << e.what() << endl;
    }
    catch (...)
    {
        cerr << "unknown exception." << endl;
    }

**Comment by louishlz** [comment]
首先你的comm 设置了主控地址了吗？ com.setProperty("locator","locator","tars.tarsregistry.QueryObj@tcp -h 10.30.x.x -p 17890")
其次：tars请求根本不需要业务主动调用stat接口上报的，业务客户端发送完请求之后，框架内部会自动上报统计信息的（框架内部会有个1分钟的缓存间隔才上报）

请确保你的测试进程维持1分钟以上的时间再退出。
