### ISSUE TITLE
为什么使用集群MySQL会报错？

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#540]
```
2020-05-05 19:50:05|139781505799936|ERROR[StatDbManager::updateEcsStatus exception:
[TC_ Mysl::execute]: mysql query:
update 't ecstatus' set lasttime' = '20200505 1950' where appname='tars_ stat_ 172.16.68.159' and action=0 ] :
Percona-XtraDB- Cluster prohibits use of DML command on a table (tars_ _stat.t ecstatus) that resides in
non-transactional storage engine with pxc_ strict_ mode = ENFORCING or MASTER
2020-05-05 19:50:05|139781505799936|DEBUG|IsdbTableExistishow tables like '%t ecstatus%|affected:1
2020-05-05 19:50:05|139781505799936|ERRORITARS NOTIFY ERROR ERROR:172.16.68.159lupdateEcsStatus ip:47.99.135.112|por:3306:
统计入库失败，请及时处理!

```
_```
sqlStatus = "CREATE TABLE ‘t_ ecstatus' ("
"  'id' int(11) NOT NULL auto_ increment, "
"  'appname' varchar(64) NOT NULL default ' ', "
"  'action' tinyint(4) NOT NULL default '0', "
"  'checkint' smallint(6) NOT NULL default '10', "
"  'lasttime' varchar(16) NOT NULL default ' ', "
"   PRIMARY KEY ( 、appname , action ), "
"   UNIQUE KEY 'id' ('id') "
")  ENGINE=HEAP DEFAULT CHARSET=utf8";
```

>

**Comment by TARS-Answer** [comment]
A:The cluster version of percona xtradb cluster aims to solve a large number of transactions and calculations. Percona xtradb cluster prohibits DML and other operations on a table. If you want to use this version of the storage engine, you need to manually handle some of the table types.
