### ISSUE TITLE
Why is it wrong to use MySQL Cluster?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#541]
![图1](https://user-images.githubusercontent.com/66677505/84387285-5b139980-ac25-11ea-8a10-d99b9f74bd01.png)_
![问题1(2)](https://user-images.githubusercontent.com/66677505/84391146-273b7280-ac2b-11ea-8638-c7d983c04ddb.jpg)

**Comment by TARS-Answer** [comment]
The cluster version of percona xtradb cluster aims to solve a large number of transactions and calculations. Percona xtradb cluster prohibits DML and other operations on a table. If you want to use this version of the storage engine, you need to manually handle some of the table types.
![QQ图片20200611211005](https://user-images.githubusercontent.com/66677645/84388990-045b8f00-ac28-11ea-9477-53a978577ab4.jpg)
