### ISSUE TITLE
Why add a servant to the tars registry, which can find data in the database, but the registry does not?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#543]

**Comment by TARS-Answer** [comment]
E：Because the time of the tars registry is inconsistent with that of the database, the cache is always read and will not be updated. Kill the process of the registry, and the registry will restart.

C：因为Tars注册中心的时间和数据库的时间不一致，导致一直读的是缓存，不会更新。把注册中心的进程kill掉，注册中心重启后就有了。
