### ISSUE TITLE
Which shell script will be called to execute by clicking the restart button indicated by the red arrow in the figure?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#546]
![#546](https://user-images.githubusercontent.com/66677505/84394360-6966b300-ac2f-11ea-8604-c23d0a9abbf3.jpg)

**Comment by TARS-Answer** [comment]
E：Restart will call the service interface, each tars has an admin management port for tarsnode.

C：重启调用服务的接口，每个tars有一个admin的管理端口给tarsnode调用。
