### ISSUE TITLE
What is the unit in the box in the picture?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#547]
![#547](https://user-images.githubusercontent.com/66677505/84395032-48eb2880-ac30-11ea-9b23-c1cf10bc7142.jpg)

**Comment by TARS-Answer** [comment]
E：Physical MEM size in the file "/proc/" + spid + "/statm"  Unit: K (to be examined)

C："/proc/" + spid + "/statm"这个文件里面的, physical mem size，单位为K（待考证）
