### ISSUE TITLE
The CentOS of VMware, the host of docker container, can connect mysql of windows, but it can not connect mysql when it is started in the container. How to solve this problem?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#548]
![#548(1)](https://user-images.githubusercontent.com/66677505/84398285-5a353480-ac32-11ea-85b4-ef0af31ac2eb.png)

CentOS can connect to MySQL service under win with MySQL command, and run VMware under win. CentOS is installed in VMware, and mysql-h 192.168.8.109-uroot-p under CentOS can be connected.

![#548(2)](https://user-images.githubusercontent.com/66677505/84398322-615c4280-ac32-11ea-9775-9cdcbd10f7f9.png)

**Comment by TARS-Answer** [comment]
E：This mode doesn't work, "docker network create - D bridge -- subnet = 192.168.8.0/16 -- gateway = 192.168.8.1 tars". This is just that IP looks like a subnet, and communication can't be done.

C：这种模式行不通，"docker network create -d bridge --subnet=192.168.8.0/16 --gateway=192.168.8.1 tars"，这个只是ip看起来是一个子网的，通信做不到。

**Comment by TARS-Question** [comment]
What is this docker0?

![#548(3)](https://user-images.githubusercontent.com/66677505/84398955-260e4380-ac33-11ea-9e10-d8f6822d0c6b.png)

**Comment by TARS-Answer** [comment]
E：The gateway address of the container bridge.

C：容器网桥的网关地址。

**Comment by TARS-Question** [comment]
Is there any problem with this docker 0 172? 

![#548(4)](https://user-images.githubusercontent.com/66677505/84399796-da0fce80-ac33-11ea-96f7-257f8f5bd160.png)

**Comment by TARS-Answer** [comment]
E：No problem. Go to the container, or check the container. Maybe the network is not matched.

C：没问题，进容器看看，或者inspect下容器，可能是网没配对。

**Comment by TARS-Question** [comment]
[#548.txt](https://github.com/TarsCloud/Tars/files/4765497/548.txt)

Who can help to read this document?

**Comment by TARS-Answer** [comment]
E：Gateway ip172.17.0.1/8 and container IP 192.168.8.109 may have problems.

C：网关IP172.17.0.1/8，容器IP 192.168.8.109，可能会有问题。

**Comment by TARS-Question** [comment]
Do you mean doker0?

**Comment by TARS-Answer** [comment]
E：The gateway is 172.17.0.1/16, but the same is not true. You can understand it by entering the container ifconfig.

C：网关是172.17.0.1/16，不过一样不通，进容器ifconfig就懂了。

**Comment by TARS-Question** [comment]
After the docker is started, it exits. Can it enter the container?

![#548(5)](https://user-images.githubusercontent.com/66677505/84400991-51922d80-ac35-11ea-89d6-d5f5a50df8dc.png)

**Comment by TARS-Answer** [comment]
E：Remove the - d parameter at startup to see the running log, and you will know why you quit.

C：启动的时候去掉-d参数可以看到运行日志，就知道为什么会退出了。

**Comment by TARS-Question** [comment]
The above MySQL failure is the logs of docker, which is the connect failure.

**Comment by TARS-Answer** [comment]
E：IP is not matched. It is recommended to follow the tutorial.

C：ip没配对，建议跟着教程做。

**Comment by TARS-Question** [comment]
The tutorial begins with 172. Do you want to keep it the same? It can be changed to 192.168.

**Comment by TARS-Answer** [comment]
E：If you do not have the ability to distribute network, try to modify only the last segment of IP, and the IP network segment should be the same. There is also a bridge network in the tutorial. Don't leave it behind. (see remark Figure)

C：如果没有配网能力的话，尽量只修改IP的最后一段，IP的网段要一样。教程里还有个创建桥接网络的，别落下了。(见备注图)
![#548（6）](https://user-images.githubusercontent.com/66677645/84401685-22c88700-ac36-11ea-9c83-01445a2f986a.png)

**Comment by TARS-Question** [comment]
MySQL in the container can't be connected. Another MySQL service, does the container exit?

**Comment by TARS-Answer** [comment]
E：When starting the container, there will be an automatic framework installation process. If you fail to connect mysql during installation, you will automatically exit.

C：启动容器的时候会有个框架自动安装过程，如果安装的时候连接MySQL失败会自动退出。

**Comment by TARS-Question** [comment]
Is the IP of the container the same as that of the host when it is started? The container cannot connect to the MySQL of the host, so the container exits. How to locate it?

**Comment by TARS-Answer** [comment]
E：This is the problem of the network. It is recommended to follow the document completely first, and observe it after success. If you need to change Mysql to the host mysql, you don't need to change anything except the environment variables related to MySQL.

C：这个是网络的问题，建议先完全按照文档进行一遍，成功之后观察一下。如果需要更换MySQL为宿主机MySQL的话，除了MySQL 相关的环境变量需要更改，别的都不用动。
