### ISSUE TITLE
According to the installation instructions, the MAC automatic deployment can download node NPM automatically, but it seems that it cannot be installed automatically in the actual installation process.

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#549]
![#549](https://user-images.githubusercontent.com/66677505/84516959-29700080-ad01-11ea-8004-646141cd67e8.png)

**Comment by TARS-Answer** [comment]
E：It shouldn't be, MAC and Linux are the same.

C：不应该, mac和linux是一样的。

**Comment by TARS-Answer** [comment]
E：It shouldn't be, MAC and Linux are the same.

C：不应该, mac和linux是一样的。

**Comment by TARS-Question** [comment]
Open install.sh and there is no place to download and install node.

**Comment by TARS-Answer** [comment]
E：Download the node installed by NVM with NVM.

C：下载nvm，用nvm安装的node。
