### ISSUE TITLE
Hellogo is written according to the document. It can't run after publishing. What's the reason? What's the place that didn't do well? 

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#552]
![#552(1)](https://user-images.githubusercontent.com/66677505/84518235-faf32500-ad02-11ea-8bfc-c1199c0f4192.png)

![#552(2)](https://user-images.githubusercontent.com/66677505/84518247-ff1f4280-ad02-11ea-8389-ebef1853fc00.png)

**Comment by TARS-Answer** [comment]
E：Unpack the uploaded package to see if hellogo is right or Linux program.

C：将上传的压缩包解开看看HelloGo是否是对的, 是否是linux的程序。

**Comment by TARS-Question** [comment]
I forget that I use MacOS, and go is easy to make this kind of error. In windows, I build in go and then manually package and publish. This kind of error is also common. This kind of error is easy to occur when the production package is not released in a period of time. It is easy to ignore the Linux problem when debugging locally.
