### ISSUE TITLE
Will the two locks be locked as shown in the remark drawing?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#554]
![#554](https://user-images.githubusercontent.com/66677505/84518587-7e147b00-ad03-11ea-9e5f-c35597825a5c.png)

**Comment by TARS-Answer** [comment]
No, the two places marked in the figure generally do not need to be locked. The mark at the end of Recv MessageQ is the request distribution of the message queue, and the untimed requests are distributed to the handle threads. The second place is marked as Send MessageQ to return the request via network IO. Where there is a lock, it is usually the handle threads that put the returned result into the Send MessageQ process, and multiple processing threads safely send the operation to the queue.

**Comment by TARS-Answer** [comment]
不会，图中标注的两处地方一般情况下不需要锁，Recv MessageQ末端的标记处为消息队列的请求分发，将未超时的请求分发到handle threads中。第二处标记为Send MessageQ通过网络IO返回请求。有锁的地方一般为handle threads将返回结果放入Send MessageQ的过程中，多个处理线程线程安全地将操作发送队列
