### ISSUE TITLE
After the master branch of Tarsramework is compiled, if I need to upgrade the tarsnode, will I just replace the tarsnode execution file or allthe tarsnodes be replaced?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#556]

**Comment by TARS-Answer** [comment]
E：The result of tarsnode compilation is a binary file, just replace the tarsnode executable file.

C：tarsnode编译的结果就是一个bin，只替换这个tarsnode的执行文件即可。

**Comment by TARS-Question** [comment]
After restarting the service, tarsnode restarted.

![#556(1)](https://user-images.githubusercontent.com/66677505/84518860-e6635c80-ad03-11ea-8245-be35addbcb85.jpg)

But the management page shows off, and there is no log.

![#556(2)](https://user-images.githubusercontent.com/66677505/84518899-f54a0f00-ad03-11ea-9eae-7b8b9d8dc276.jpg)

**Comment by TARS-Answer** [comment]
E：Check the operation and maintenance management, node management, and check whether the node is normal. If inactive is displayed（see note Figure 3）, the node is not connected to the frame.

C：查看运维管理，节点管理，检查节点是否正常。如果显示inactive（见备注图三），说明节点没有连接到框架。
![556(3)](https://user-images.githubusercontent.com/66677645/84519011-14e13780-ad04-11ea-9f91-410961eab26a.jpg)

**Comment by TARS-Answer** [comment]
E：Check whether the node configuration file exists (see note Figure).

C：检查节点配置文件是否存在（见备注图）。
![557(2)](https://user-images.githubusercontent.com/66677645/84519268-70abc080-ad04-11ea-9334-1c1c04725184.jpg)
![557(3)](https://user-images.githubusercontent.com/66677645/84519276-743f4780-ad04-11ea-8e72-bdbb2ba1ccf3.jpg)
