### ISSUE TITLE
How to solve the following configuration problems?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#557]
- The following figure shows the startup log of tarsnode.

- ![#557(1)](https://user-images.githubusercontent.com/66677505/84519209-540f8880-ad04-11ea-9c26-3936176e2a0a.jpg)

**Comment by TARS-Answer** [comment]
E：Check whether the node configuration file exists (see note Figure ).

C：检查节点配置文件是否存在（见备注图
![557(2)](https://user-images.githubusercontent.com/66677645/84519537-d5ffb180-ad04-11ea-952d-7b6ff76e605c.jpg)
![557(3)](https://user-images.githubusercontent.com/66677645/84519558-dbf59280-ad04-11ea-8286-0359557ee60c.jpg)

）。

**Comment by TARS-Question** [comment]
Here is RM's history. Under what circumstances will the contents of “ /usr/local/app/tars/tarsnode/conf/tars.tarsnode.config.conf ” be cleared?

![#557(4)](https://user-images.githubusercontent.com/66677505/84519835-3131a400-ad05-11ea-994a-2340d82158d0.jpg)

![#557(5)](https://user-images.githubusercontent.com/66677505/84519843-34c52b00-ad05-11ea-86b0-ce9a087b0925.jpg)

**Comment by TARS-Answer** [comment]
E：tarsnode will update this file regularly,When the update happens, the file will be cleared when the power is cut off.

C：tarsnode会定时更新这个文件，当更新的时候正好断电这个文件内容会被清掉。

**Comment by TARS-Question** [comment]
Copy this configuration file from another node, can I continue to use this node?

**Comment by TARS-Answer** [comment]
E：Yes, just replace the ip inside.

C：可以，注意替换里面的ip即可。
