### ISSUE TITLE
As shown in the remarks, according to the documentation, write HelloServer, but this configuration file is not found. Is the configuration file for this service generated manually or automatically generated by a tool?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#558]
![#558](https://user-images.githubusercontent.com/66677505/84519936-5a523480-ad05-11ea-8a61-0ce7ae55c338.png)

**Comment by TARS-Answer** [comment]
E：Automatically generated, use the ps and grep instructions to find and display this process path. There is a conf directory under the corresponding directory, which contains this configuration file.

C：自动生成，使用ps和grep指令查找显示这个进程路径。对应目录下有个conf目录，里面含有这种配置文件。
