### ISSUE TITLE
As shown in the figure,main.cpp is the client code, which refers to the header file "servant / Communicator.h", and "Communicator.h" refers to the header file "util / tc_ex.h", so each time you compile, do I need to copy the servant directory and util directory to the project Under the catalog?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#559]
- ![#559(1)](https://user-images.githubusercontent.com/66677505/84520023-7e157a80-ad05-11ea-9ad3-a0b98969e1a9.png)

- ![#559(2)](https://user-images.githubusercontent.com/66677505/84520039-82da2e80-ad05-11ea-83f9-0865e4d82bea.png)

- ![#559(3)](https://user-images.githubusercontent.com/66677505/84520053-87064c00-ad05-11ea-81cb-1f1f710c0ef3.jpg)

**Comment by TARS-Answer** [comment]
E：Answer one ：No, just include applaction.h directly.
      Answer two：No,directly include: / usr / local / tars / cpp / include

C：回答1：不需要，直接include applaction.h即可。
      回答2：不需要，直接include: /usr/local/tars/cpp/include
