### ISSUE TITLE
As shown in the figure, I execute “make release” in the HelloServer / bin directory, and finally I only see hello.h in the / home / tarsproto / TestApp / HelloServer directory, without tars and mk files?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#561]
- ![#561(1)](https://user-images.githubusercontent.com/66677505/84520309-f0865a80-ad05-11ea-9966-4f388bfb8d39.png)

- ![#561(2)](https://user-images.githubusercontent.com/66677505/84520319-f419e180-ad05-11ea-8558-b8d3aa4b746d.png)

**Comment by TARS-Answer** [comment]
E：The new version only has .h file, so you only need to include this directory.

C：新版本只有.h, 所以只需要include这个目录就可以了
