### ISSUE TITLE
Many functions of cstring null terminator are used in http parsing. Do you need to add '\ 0' to the buffer after parsing? 

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#564]
- ![#564(1)](https://user-images.githubusercontent.com/66677505/84520851-c1bcb400-ad06-11ea-9c91-bda25fe8c15e.png)

- ![#564(2)](https://user-images.githubusercontent.com/66677505/84520861-c4b7a480-ad06-11ea-9e2e-b9c0d5e17352.png)

**Comment by TARS-Answer** [comment]
E：It is better to use strnstr.

C：使用strnstr更好。
