### ISSUE TITLE
Stringtoproxy in Java will trigger the dead loop bug of concurringhashmap computeifabsent. (JDK version is 1.8)

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#566]
> 1. During system initialization, stringtoproxy notifyhelper's proxy, computeifabsent will lock.
> 2. Next, when initializing any proxy for the first time, updateservantendpoints will find available nodes,
> 3. At this time, stringtoproxy queryhelper's proxy will be added internally
> 4. The same communicator, the same concurringhashmap, the same cache, and the same computeifabsent are in infinite CAS loop.

> When different objs happen to bump into a hashcode, and they are all in computeifabsent, there is a dead cycle.

- ![#566(1)](https://user-images.githubusercontent.com/66677505/84524170-1adb1680-ad0c-11ea-9756-b93ffd4bf989.jpg)

- ![#566(2)](https://user-images.githubusercontent.com/66677505/84524188-23335180-ad0c-11ea-9ef4-d03b45853848.jpg)

**Comment by TARS-Answer** [comment]
What is the small version?

**Comment by TARS-Answer** [comment]
小版本是多少？

**Comment by TARS-Question** [comment]
https://stackoverflow.com/questions/43861945/deadlock-in-concurrenthashmap

This should be OK. It seems that in jdk8, this is the problem. As long as we avoid the use of computeifasent, we can avoid the nesting of computeifasent in computeifasent for the same map. If we simply change it, we don't need computeifasent. Once we have a solid container, null will be put into the new one, which should be no problem. Anyway, a reentrant lock is added before computeifabsent in getservantfactory.

**Comment by TARS-Question** [comment]
https://stackoverflow.com/questions/43861945/deadlock-in-concurrenthashmap

这个应该还好。好像jdk8里，这个是问题。只要避免computeIfAbsent这个用法就好，同一个map，避免computeIfAbsent里嵌套computeIfAbsent，简单改的话，不用computeIfAbsent，老老实实contains一把，null就new一个put进去，应该就没问题。反正getServantFactory里computeIfAbsent前是加了一把可重入锁的。

**Comment by TARS-Answer** [comment]
This part has been modified in 1.7, but it will not have this problem in 1.6. After the problem is confirmed, it will be changed back.

**Comment by TARS-Answer** [comment]
这一部分1.7有修改，1.6不会有这个问题，后面问题确认后，就改回去。

**Comment by TARS-Question** [comment]
What is the version of JDK used for reading? Haven't you met this problem?

**Comment by TARS-Question** [comment]
阅文用的jdk版本是啥，没遇到这个问题么？

**Comment by TARS-Answer** [comment]
1.7 is a new one now, using version 1.8. This bug only exists when the reservationnode is expanded and operated by other threads. When spring operation is used, because tarsclient was initialized before. proxy.get When it is running, it must be. It will not be created when it is running.

When this part of API is in 1.7, it's true that some of the code uses the new API. When this part is updated later, we need to look at the overall processing mode of JDK to have a controllable risk.

**Comment by TARS-Answer** [comment]
一部分是1.6的版本， 所以不产生这个问题
1.7的是现在新上的一部，使用的是1.8的版本。这个bug也就是在ReservationNode 在扩且被其他的线程操作的时候 才会有，使用的是spring操作的时候 ，因为tarsclient是在之前初始化掉了。proxy.get的时候，必然是有的，不会在运行的时候会有创建这种操作了。

这一部分api 在1.7的时候 ，确实一部分代码使用了新的api了，这一部后面在更新的时候，也要再看一下jdk的整体的一个处理的模式才可以有个可控的风险。
