### ISSUE TITLE
Is the timeout period of tars2.3 service startup dead two seconds? After switching to the new framework and compiling, the services in the k8s container cannot be available. Directly start manually with the tars_start.sh script, it can be normal. I observed that timeout is written in two seconds.

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#568]
> ![#568(1)](https://user-images.githubusercontent.com/66677505/84649154-97523d00-af38-11ea-9e2e-ea2facce27e9.jpg)

> ![#568(2)](https://user-images.githubusercontent.com/66677505/84649167-9faa7800-af38-11ea-99af-5a158ea98e9c.jpg)

**Comment by TARS-Answer** [comment]
E：This time can be configured in the template.

C：在模板里可以配置这个时间。
