### ISSUE TITLE
Is the logic here normal? I feel that _interval cannot take effect, and the log does not see the logic in loadData () is executed regularly.

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#569]
![#569](https://user-images.githubusercontent.com/66677505/84649342-f3b55c80-af38-11ea-8bce-d4685ef5654d.jpg)

**Comment by TARS-Answer** [comment]
E：Not normal, this is actually useless. This piece of logic seems to be useless in the current version. Before the internal version, it was loaded into memory for easy viewing. The current version can be checked directly on the web.

C：不正常，这个其实没用。 这个段逻辑在目前版本好像是没用的, 内部版本之前是加载内存里面, 方便查看, 现在的版本可以直接用web查db了。
