### ISSUE TITLE
如何快速迭代更新tars

### ISSUE THREAD

**Issue by LinBoLen** [TarsCloud/Tars#57]
据我所知, Tars在腾讯内部使用叫taf. 开源出来是出于各种原因的考虑.

那么现在问题来了, 如何做到tars的快速迭代新功能. 
- [ ] 有些issue, 可能已经在内部系统里解决了, 或都实现方式不一样. 
- [ ] 新功能社区发现了, 而内部系统未发现
- [ ] 是否可参考众多开源软件, 内部是基于开源的tars. (如docker 分离出mobi)

**Comment by yuansx** [comment]
tars更新，你需要注意关注GitHub上Tars的动态
