### ISSUE TITLE
What's wrong with the picture?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#570]
![#570](https://user-images.githubusercontent.com/66677505/84649407-0def3a80-af39-11ea-8e68-611c93a08831.jpg)

**Comment by TARS-Answer** [comment]
E： Check whether the tarsAdminRegistry is started. If it is started, there is a framework check function on the web platform to check if there is a service configuration error.

C：检查tarsAdminRegistry是否启动，如果启动了，在web平台上有一个框架检查功能, 检查一下，是否存在服务配置的错误。
