### ISSUE TITLE
What is the reason for this error when uploading the package to the service as shown in the figure?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#571]
![#571](https://user-images.githubusercontent.com/66677505/84649697-8c4bdc80-af39-11ea-8a9c-e1969cfa3c4d.jpg)

**Comment by TARS-Answer** [comment]
E：The node is not up.You can add a monitor script to monitor it, there is written in the document.

C：节点没有起来。可以加一个monitor脚本, 监控一下, 文档里面有写。
