### ISSUE TITLE
The two states shown in the figure are inconsistent, is it a success or failure?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#572]
![#572(1)](https://user-images.githubusercontent.com/66677505/84657018-3467a280-af46-11ea-9fa6-b9b839680fee.jpg)

**Comment by TARS-Answer** [comment]
E：This means that the release was successful, and it does not mean that the service started successfully. You can check the service log for detailed reasons (see note Figure)

C：这表示发布成功, 不代表服务启动成功。可以查看服务日志查看详细原因（见备注图）
<img width="52" alt="QQ图片20200617235203" src="https://user-images.githubusercontent.com/66677645/84920346-9b778980-b0f5-11ea-9eea-b66bc9dbc184.png">
