### ISSUE TITLE
After the computer is turned off, an error occurs after turning on,but it will be fine after restarting it twice. what is the reason?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#573]
> ![#573(1)](https://user-images.githubusercontent.com/66677505/84657056-46494580-af46-11ea-92bd-51c2703684fd.jpg)`

> ![#573(2)](https://user-images.githubusercontent.com/66677505/84657067-48ab9f80-af46-11ea-8acc-e0d6633b8c34.jpg)

**Comment by TARS-Answer** [comment]
E：The reason for the error is that it hasn’t gotten up yet.

C：报错的原因是服务还没起来。
