### ISSUE TITLE
After I went online and packaged and uploaded the package, I was prompted with an error. The log indicated that the port was occupied, and I changed a lot of free ports. This error is still displayed. Why?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#574]
> ![#574(1)](https://user-images.githubusercontent.com/66677505/84657288-a3dd9200-af46-11ea-9e02-98ead9c0719e.jpg)

-  Below is a list of service status and feedback information.

> ![#574(2)](https://user-images.githubusercontent.com/66677505/84657301-a9d37300-af46-11ea-8656-a2f727eae01b.jpg)

**Comment by TARS-Answer** [comment]
E：It is very likely that your application will try to listen to this port twice before and after. For example, tarsphp will listen to 10002 when it is started, and it will also try to listen to this port when hyperf is initialized.

C：很有可能你的应用前后两次尝试监听这个端口，比如tarsphp启动的时候监听了10002，hyperf初始化的时候也在尝试监听这个端口。

**Comment by TARS-Question** [comment]
How can I check which ports are monitored by tarsphp?

**Comment by TARS-Question** [comment]
如何查看tarsphp监听了哪些端口？

**Comment by TARS-Answer** [comment]
It is very likely that your application will try to listen to this port twice before and after. For example, tarsphp will listen to 10002 when it is started, and it will also try to listen to this port when hyperf is initialized.

**Comment by TARS-Answer** [comment]
tarsphp只监听你配置的应用端口。

**Comment by TARS-Question** [comment]
After replacing the port, it is found that the current status is off when it is just started. After two minutes, I refresh the page and the service status becomes active. Does this phenomenon indicate that the service is normal? When you click Restart or Stop, the error is reported again, and it still prompts that the port is occupied. why?

**Comment by TARS-Question** [comment]
更换了端口后，发现刚刚启动的时候，当前状态显示off。两分钟后，我刷新页面，服务状态变成active，这个现象说明服务正常了吗？当点击重启或者停止，再次报错，日志中依然提示端口被占用。这是什么原因？

**Comment by TARS-Answer** [comment]
Observe how long it took to start the service and fail to start it. It may have been started for a long time, and the heartbeat report was reported normally. For example, tarsphp starts the relevant registration first, and then starts the first detection and reporting of the heartbeat ten seconds later. In these 10 seconds, the hyperf is still initializing, and the hyperf hangs after the heartbeat is triggered. It is recommended to track the startup process code.

**Comment by TARS-Answer** [comment]
看刚启动服务到启动失败全程经历了多久，有可能中间启动了很久，心跳上报正常上报了。比如tarsphp先启动执行相关注册，然后十秒以后开始第一次检测和上报心跳，在这10秒里hyperf还在初始化中，心跳触发之后hyperf才挂掉，建议跟踪一下启动过程的代码。
