### ISSUE TITLE
Is the tc_mysql library thread-safe?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#575]

**Comment by TARS-Answer** [comment]
E：Thread is not safe.

C：线程不安全。

**Comment by TARS-Question** [comment]
If using the tc_mysql library, does each servant need to instantiate an object?

**Comment by TARS-Question** [comment]
如果使用tc_mysql的库，每个servant都需要实例化一个对象吗？

**Comment by TARS-Answer** [comment]
yes

**Comment by TARS-Answer** [comment]
是的

**Comment by TARS-Question** [comment]
Generally mysql has limited links, multiple server deployment, each server has N servants, there will be many links, is it easy to exceed the number of links?

**Comment by TARS-Question** [comment]
一般mysql有限定链接，多server部署，每个server有N个servant，便会有很多链接，链接数容易超限吗？

**Comment by TARS-Answer** [comment]
Not all services need to connect to the datebase, or you can have one mysql per partition. If it is a global service, you can have a proxy service to specifically communicate with mysql, so that the number of links will not exceed the limit

**Comment by TARS-Answer** [comment]
不是所有的服务都要连接datebase，或者可以每个分区一个mysql。如果是全局服务，可以做个代理服务专门去和mysql通讯，这样链接数就不会超限了
