### ISSUE TITLE
Based on the docker production environment example provided on the official website, can you successfully access port 3000 after deployment using the host network?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#578]
![#578](https://user-images.githubusercontent.com/66677505/85204359-8f363b00-b346-11ea-8925-2e2cde7f7c55.jpg)

**Comment by TARS-Answer** [comment]
If you have any questions, please refer to the relevant documents in the documentation, check the issues in the web section.

**Comment by TARS-Answer** [comment]
有问题可以参考说明文档里，关于web的部分中检查问题的相关内容。
