### ISSUE TITLE
Why can't it run after packaging as shown in the picture?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#579]
![#579](https://user-images.githubusercontent.com/66677505/85204385-b3921780-b346-11ea-9979-c5ca252989c3.jpg)

**Comment by TARS-Answer** [comment]
There may be problems with the business code, configuration errors in the service deployment process, etc. There are many possible reasons, and you need to check the error log for troubleshooting

**Comment by TARS-Answer** [comment]
可能是业务代码存在问题、服务部署过程配置错误等，可能的原因很多，需要查阅错误日志进行排查
