### ISSUE TITLE
The database problem shown in the figure, why there is no data?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#580]
![#580](https://user-images.githubusercontent.com/66677505/85204561-d7099200-b347-11ea-9a5e-0458b29242e4.jpg)

**Comment by TARS-Answer** [comment]
There is no data for the day, and the data will be displayed the next day.

**Comment by TARS-Answer** [comment]
当天没有数据，第二天就会有数据显示。
