### ISSUE TITLE
As shown in the figure, the virtual machine docker is installed with 4G memory allocated. What is the reason for the error?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#581]
![#581](https://user-images.githubusercontent.com/66677505/85204567-f30d3380-b347-11ea-8bc6-5df725920bb0.jpg)

**Comment by TARS-Answer** [comment]
The allocated virtual memory is not large enough.

**Comment by TARS-Answer** [comment]
分配的虚拟内存不够大。
