### ISSUE TITLE
This place is set to false. Why still visit 3001?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#583]
> ![#583(1)](https://user-images.githubusercontent.com/66677505/85204595-1afc9700-b348-11ea-9699-497a513eb0b4.jpg)

> ![#583(2)](https://user-images.githubusercontent.com/66677505/85204596-1c2dc400-b348-11ea-8e4a-8da7ebc28019.jpg)

> ![#583(3)](https://user-images.githubusercontent.com/66677505/85204597-1e901e00-b348-11ea-83a6-352a257932ef.jpg)

**Comment by TARS-Answer** [comment]
There is a bug. It usually has permissions.

**Comment by TARS-Answer** [comment]
有bug，一般都带了权限。
