### ISSUE TITLE
What should I do if I forget the tars-framework password?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#588]
![#588](https://user-images.githubusercontent.com/66677505/85220580-4c747180-b3df-11ea-8d0b-12dca91d8ffd.jpg)

**Comment by TARS-Answer** [comment]
If the password of admin is forgotten, currently only the fields of related tables in the database can be reset to solve:
- Log in to mysql
- View db: db_user_system
- Modify the table: t_user_info
- Reset admin user record, reset password to empty
- When logging in to the web, you will be prompted to set the admin password.
(Please refer to https://tarscloud.github.io/TarsDocs/installation/web.html#chapter-7 for password forgetting related content.)

**Comment by TARS-Answer** [comment]
如果admin的密码遗忘, 目前只能重置数据库中相关表的字段来解决:
- 登录mysql
- 查看db: db_user_system
- 修改表: t_user_info
- 重置admin用户记录, 将password重置为空
- 登录web时, 将会提示设置admin密码.

（可参照 https://tarscloud.github.io/TarsDocs/installation/web.html#chapter-7中的密码遗忘处理相关内容。）
