### ISSUE TITLE
The tars development environment is deployed locally. The local IP comes from DHCP and will change frequently. Where can I change this?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#589]

**Comment by TARS-Answer** [comment]
When writing a script to start, set a domain name corresponding to your current ip, to your /etc/hosts, and then set the environment variable: export DOMAIN = this domain name, and then use docker to start the framework, this should avoid this problem .

**Comment by TARS-Answer** [comment]
写脚本启动时, 设置一个域名名称对应你当前的ip, 到你的/etc/hosts，然后设置环境变量: export DOMAIN = 这个域名名称，再用docker方式启动framework，这样应该可以规避这个问题。
