### ISSUE TITLE
setProperty参数怎么设置？

### ISSUE THREAD

**Issue by ramosyang** [TarsCloud/Tars#59]
issues from QQ群579079160   友缘

自己写的一段demo程序，需要在通信器里主动设置下tarsstat的地址
这个接口是setProperty，参数是怎样设置的？

**Comment by ramosyang** [comment]
comm->setProperty("stat", "taf.tafstat.StatObj");
这个函数有重载，你可以从头文件查看：
servant/Communicator.h

**Comment by jokenchang** [comment]
这个问题引出的相关问题，https://github.com/Tencent/Tars/issues/54
希望帮忙回答一下

**Comment by yuansx** [comment]
这个问题已经在https://github.com/TarsCloud/Tars/issues/54解答，close
