### ISSUE TITLE
Does MDC support cross service link tracking?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#590]

**Comment by TARS-Answer** [comment]
Cross service link tracking is a simple point, which can be transferred by setting its own value in context; for mature points, opentracing can be introduced. MDC is just a storage tool in a process or thread. It is convenient to pass some variables. Now it supports Zipkin. You can have a look at the document.

**Comment by TARS-Answer** [comment]
跨服务链路追踪，简单点，可以通过context自己赋值传递；成熟点，可以引入opentracing。mdc只是一个进程或者线程内的存储工具，方便传递一些变量，现在支持zipkin，可以看一下文档。
