### ISSUE TITLE
Does the latest version of server support asynchronous processing of requests? Note the code in the figure. The writeresult method here does not trigger the call.

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#593]
Note the code in the figure. The writeresult method here does not trigger the call.

> <img width="959" alt="#592" src="https://user-images.githubusercontent.com/66677505/85274956-3e435580-b4b2-11ea-9986-c43da6f69b7a.png">

**Comment by TARS-Answer** [comment]
This is triggered by its own business, just like the 3.1 asynccontext of servlet, which is called after the end of its async business.

**Comment by TARS-Answer** [comment]
这个是自己业务触发的，和servlet的3.1的asynccontext一样，在自己的业务async事件结束后调用就好。

**Comment by TARS-Question** [comment]
In the internal implementation, the type of completefuture is returned. It is triggered in the framework layer. Is the implementation of spring MVC the same?

**Comment by TARS-Question** [comment]
在内部实现的时候，是返回了CompleteFuture的类型，在框架层去触发的，spring mvc的实现也是这样的吗？

**Comment by TARS-Answer** [comment]
Yes, that's spring encapsulation, but that's for HTTP, and the tars protocol now uses this API temporarily.

**Comment by TARS-Answer** [comment]
对，那个就是spring封装掉了，不过那个是针对http的，tars的协议现在暂时使用的是这个api。

**Comment by TARS-Question** [comment]
Does this feature use demo in some examples?

**Comment by TARS-Question** [comment]
这块的特性在example中有一些使用demo吗？

**Comment by TARS-Answer** [comment]
See the figure and link （https://github.com/TarsCloud/TarsJava/blob/master/docs/tars_java_user_guide.md）
![QQ图片20200622182602](https://user-images.githubusercontent.com/66677645/85277352-e4dd2580-b4b5-11ea-8de3-a42b892800ff.jpg)

**Comment by TARS-Answer** [comment]
见图并参考链接（https://github.com/TarsCloud/TarsJava/blob/master/docs/tars_java_user_guide.md）。
![QQ图片20200622182528](https://user-images.githubusercontent.com/66677645/85277464-08a06b80-b4b6-11ea-8884-667f5b75d19c.jpg)
