### ISSUE TITLE
What are the hardware requirements for each component when the tars framework is deployed?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#594]

**Comment by TARS-Answer** [comment]
tarslog requires a large hard disk, it is best to deploy independently; tarsstat&tarsproperty, at least 2G memory is recommended; other components do not have too many requirements.

**Comment by TARS-Answer** [comment]
tarslog需要大硬盘, 最好独立部署；tarsstat&tarsproperty, 建议至少2G内存；其他组件没有太大要求。
