### ISSUE TITLE
Does remote log support distributed printing to multiple remote services?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#595]
It refers to multiple server addresses, and then the logs are distributed to different servers according to a certain rule.

**Comment by TARS-Answer** [comment]
You can configure more than one here. At present, it is loop (rotation training). The server address is configured as xxxobj@tcp -H XXX - P 333: TCP - H XXX - P 222, so the remote log server can be configured for high availability.

**Comment by TARS-Answer** [comment]
这里配置多个就可以了，目前就是loop(轮训)了，服务器地址配置为xxxobj@tcp -h xxx -p 333:tcp -h xxx -p 222，这样配置远程日志服务器可以实现高可用。
