### ISSUE TITLE
 I encountered a problem during deployment using tars.

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#596]
When tars are deployed with k8s, each pod has a tarsnode and service. When the service needs to be replaced, use k8s to republish. k8s will pull up a pod again, and the original pod will be deleted. There will be tarsnode information remaining in the main control, and the endpoint information is not deleted for the deleted node, resulting in the inaccessibility of the newly released service. It will not be accessible until the full load time reaches 1 hour later. Is there any way to circumvent this problem?

**Comment by TARS-Answer** [comment]
You can use statefullset, refer to the document https://doc.tarsyun.com/adminer/start/index.html#/tarsdoc/installation/k8s-docker-1.md, but the biggest problem with this deployment method is data Sharing needs to be solved by yourself. The performance of nfs is too slow. If it is deployed on the cloud, you may need to write the CSI plug-in yourself, and then hang the cloud disk in the container.

**Comment by TARS-Answer** [comment]
可以用statefullset，参照文档https://doc.tarsyun.com/adminer/start/index.html#/tarsdoc/installation/k8s-docker-1.md，但这种部署方式最大的问题就是, 数据共享需要自己解决, 用nfs性能太慢, 如果部署在云上, 可能需要自己写CSI插件, 然后把云盘挂在到容器里面。
