### ISSUE TITLE
创建的应用怎么删除？

### ISSUE THREAD

**Issue by ramosyang** [TarsCloud/Tars#60]
issues from QQ群579079160   生生

创建的应用怎么删除？

**Comment by ramosyang** [comment]
![image](https://user-images.githubusercontent.com/30852765/29237892-84cf929c-7f5a-11e7-9252-a7af769fe6f0.png)

**Comment by UsrNameOccupied** [comment]
表示不會刪

**Comment by yuansx** [comment]
先停掉服务，然后下线即可
