### ISSUE TITLE
See below for details.

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#600]
The firewall is turned off and the configuration file is also configured. How to solve the problem shown in Remarks Figure 1? CPU usage is shown in Remarks Figure 2.

![#600(1)](https://user-images.githubusercontent.com/66677505/85869621-86d67800-b7fe-11ea-877c-65d050398658.png)

![#600(2)](https://user-images.githubusercontent.com/66677505/85869626-88a03b80-b7fe-11ea-9398-357000a5917e.jpg)

**Comment by TARS-Answer** [comment]
TarsWeb enables authentication by default, and port 3001 needs to be opened. The RetHat7 system has the problem of only opening port 22 even if the firewall is turned off. You need to use the firewall command firewall-cmd to open the corresponding port access. TarsWeb can also be updated to the latest version, the latest version has merged the authentication module, no need to open more ports.

**Comment by TARS-Answer** [comment]
TarsWeb默认开启鉴权，需要开启3001端口。RetHat7的系统存在即便关闭防火墙也只开放22端口的问题，需要使用防火墙命令firewall-cmd开启相应端口的访问权限。也可将TarsWeb更新到最新的一个版本，最新版本已经将鉴权模块合并，无需多开端口。
