### ISSUE TITLE
Why does this log directory generate so many core files?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#602]
> ![#602(1)](https://user-images.githubusercontent.com/66677505/85871070-7de6a600-b800-11ea-9954-8dca9b9ef8c2.png)

> ![#602(2)](https://user-images.githubusercontent.com/66677505/85871077-80490000-b800-11ea-8da0-39d5039f091b.png)

**Comment by TARS-Answer** [comment]
The service has crashed. You can use the file command to check which service has crashed.Memory is recommended to use 2 core 4G at least.

**Comment by TARS-Answer** [comment]
服务崩溃了，可以使用file命令检查是哪个服务崩溃了。内存建议至少使用2核4G。
