### ISSUE TITLE
Run the coroutinedemo use case testcoo under the example provided by tar, and throw such an exception. What's the reason?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#611]
callback_findObjectByIdInSameGroup_exception _objName:BServantObj
Deplo  learncpp.BServer.BServantObj ，then run：
./testCoro
usage: ./testCoro CallTimes sObj
use default parameter
num : 1
sObj : BServantObj
Serverb is deployed on the framework, and testcoo runs locally.

**Comment by TARS-Question** [comment]
callback_findObjectByIdInSameGroup_exception _objName:BServantObj
部署了  learncpp.BServer.BServantObj , 然后跑：
./testCoro
usage: ./testCoro CallTimes sObj
use default parameter
num : 1
sObj : BServantObj
ServerB部署在框架上了，testCoro在本地跑。

**Comment by TARS-Answer** [comment]
Take a look at the basic concepts of the documents(
https://doc.tarsyun.com/adminer/start/index.html#/tarsdoc/base/tars-concept.md) and understand them.

Simply put, after the service is deployed on the platform, it can be called as follows:

1. Testcoo directly connects to the port of obj object of this service;

2. Testcoo sets the locator to automatically obtain the port of obj through the master control (only the name of obj is needed at this time).

**Comment by TARS-Answer** [comment]
把文档（
https://doc.tarsyun.com/adminer/start/index.html#/tarsdoc/base/tars-concept.md ），基础概念看一下，理解一下。
简单的说，服务部署在平台上以后,，可以这样调用:
1、testCoro直连这个服务的obj对象的端口；
2、testCoro设置locator, 通过主控自动获取到obj的端口(这个时候只需要obj的名字)。
