### ISSUE TITLE
What is the problem when the diagram in the notes is installed on windows?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#612]
![#612](https://user-images.githubusercontent.com/66677505/85874621-7e357000-b805-11ea-8317-63c5b9710ea7.png)

**Comment by TARS-Answer** [comment]
This seems to have no connection to MySQL lib library. Upgrade cmake to the latest version (3.17)

**Comment by TARS-Answer** [comment]
这个感觉没有连接到mysql的lib库，将cmake升级到最新版本(3.17)
