### ISSUE TITLE
How to deal with the error during installation?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#613]
![#613](https://user-images.githubusercontent.com/66677505/85874801-c5bbfc00-b805-11ea-9b06-6d98bc6c3c26.jpg)

**Comment by TARS-Answer** [comment]
There is an error in compiling mysqlclient. Go directly to "/root/TarsFramework/build/src/mysql" to compile mysqlclient, and upgrade cmake to the latest version (3.17).

**Comment by TARS-Answer** [comment]
编译mysqlclient出错了, 直接到/root/TarsFramework/build/src/mysql下编译mysqlclient试一试，同时将cmake升级到最新版本(3.17)。
