### ISSUE TITLE
The node is deleted immediately after the offline cleaning service. The prompt prompts to suspend the node before deleting it. After logging in to the server to stop the node, the node still can not be deleted.

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#614]
![#614](https://user-images.githubusercontent.com/66677505/85874908-ec7a3280-b805-11ea-80b7-a6393c25691e.jpg)

**Comment by TARS-Answer** [comment]
After the node deploys the service, you need to delete the node, and you need to clear all the services deployed above.

**Comment by TARS-Answer** [comment]
节点部署服务后，需要删除node, 需要将部署上面的服务都下线清理掉。
