### ISSUE TITLE
Can a node only publish one service?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#615]
My service is tar.gz, where will my installation package be decompressed after publishing with tars?

**Comment by TARS-Answer** [comment]
Only one service can be published on the same node, and multiple different services can be published. tar.gz is the service release package, which is uploaded by calling the patch service through the TarsWeb page. The default path is /usr/local/app/patchs/tars.upload/, which contains all the uploaded release packages in the history. After the service is released, it is managed by the tarsnode node service, and the default decompression path is the node service tarsnode/data/.

**Comment by TARS-Answer** [comment]
相同节点同一服务只能发布一个，可以发布多个不同服务。tar.gz为服务发布包，通过TarsWeb页调用patch服务上传，默认保持路径为/usr/local/app/patchs/tars.upload/下，包含历史所有上传的发布包。服务发布后通过tarsnode节点服务管理，默认解压路径为节点服务tarsnode/data/下。
