### ISSUE TITLE
When I execute helloworld in quickServer in tarsJava, I want to pull the configuration in the configuration center, do I need to configure this?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#616]
![#616](https://user-images.githubusercontent.com/66677505/85875229-762a0000-b806-11ea-84ff-8f2302674483.jpg)

**Comment by TARS-Answer** [comment]
right.

**Comment by TARS-Answer** [comment]
对。

**Comment by TARS-Question** [comment]
Is it configured as a port?The tars framework I currently deploy is connected via VPN.

**Comment by TARS-Question** [comment]
是配置成端口吗？我目前部署的tars框架是通过VPN连接的 。
