### ISSUE TITLE
Cannot Deploy the service using Docker

### ISSUE THREAD

**Issue by JeffCX** [TarsCloud/Tars#619]
### What language are you using?
 nodejs
 
### What operating system (Linux, Ubuntu, …) and version?
 macOS
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 darwin
 
I follow the instruction on this documentation and build the env using docker. 
https://tarscloud.github.io/TarsDocs/installation/docker.html

And I follow the nodejs scaffold documentation to build the application,
https://tarscloud.github.io/TarsDocs_en/dev/tars.js/nodetools-cli.html

 but when I want to upload the application, I cannot access to the virtual network I created. I think 172.25.0.3 is not public IP, how can I solve this problem.

<img width="1438" alt="Screen Shot 2020-06-28 at 4 05 31 PM" src="https://user-images.githubusercontent.com/25846666/85957878-1a26bf00-b95f-11ea-8b9d-cf57f8788b1b.png">

<img width="1660" alt="Screen Shot 2020-06-28 at 4 10 14 PM" src="https://user-images.githubusercontent.com/25846666/85957881-1d21af80-b95f-11ea-83ec-e5835a54ab52.png">

**Comment by ETZhangSX** [comment]
You may use a public IP instead.
