### ISSUE TITLE
Why do I use tar, logback.xml Can't get the file?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#621]
- The file name is passed in the tars. Enter it from the following entry.

> ![#621(1)](https://user-images.githubusercontent.com/66677505/86010652-4705cf80-ba4e-11ea-8dc4-d7371871eac6.jpg)

- This is an error when updating the log level on the page.

> ![#621(2)](https://user-images.githubusercontent.com/66677505/86010743-63097100-ba4e-11ea-96ee-2407c5082a3a.jpg)

**Comment by TARS-Answer** [comment]
This part will still take effect. If the file is not found here, an exception will be output normally. However, the lower level will operate the log level again. Here (picture 3) you need to optimize and modify the output log level later.

This exception should be thrown here (picture 4), which does not affect the level of log processing in the current environment.

**Comment by TARS-Answer** [comment]
这一部分还是会生效的，这里文件没有找到的话，会正常的输出一个异常，不过下层会再次操作一次日志等级的，这里(图片三)后续需要优化一下，修改这个输出的日志等级。
应该是这里(图片四)抛的这个异常，这里并不影响它处理当前环境下的日志等级。

**Comment by amosJinCloudwise** [comment]
这个问题我想是logback.xml文件的位置, 有的java项目打包并不是把logback.xml与class文件放在一起, 所以logback.xml最好是能可以配置其路径
