### ISSUE TITLE
Can I view and retrieve the logs streaming on the web page after typing them into the tarslog?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#623]

**Comment by TARS-Answer** [comment]
No, the tarslog service J is just a remote log collection. To solve the problem that multiple node services need to find logs by one server, you can look at the access elk if you need web retrieval. This change is also a change in version 1.7. The log controller of 1.6 will continue to use HA in its original mode. In version 1.6, only bugs and problems will be fixed, and no new functions will be added, but this branch will always be.

**Comment by TARS-Answer** [comment]
没有的，tarslog服务j仅仅是远程日志收集，解决多个节点服务排查日志需要一台一台服务器找的问题，所以需要web检索的，可以看看接入elk。这个变更也是1.7版本中的变更哈。1.6的日志控制器还是会以原本的模式继续使用哈，1.6版本也是仅bug和问题修复，不会新增加功能，但是这个分支会一直都在。
