### ISSUE TITLE
Does the docker image have a java environment? 

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#624]
Do I need to configure java in docker environment to run java microservice?

docker refers to tarscloud / frameword 2.4.0

**Comment by TARS-Answer** [comment]
You can use the docker of tarsnode, the framework document writes only recommends deploying framework services and not deploying business services.

**Comment by TARS-Answer** [comment]
你可以使用tarsnode的docker，framework文档写了只建议部署框架服务 不要部署业务服务。

**Comment by TARS-Question** [comment]
If you want to deploy Java microservices, because Java depends on the environment, so this can't run, is there any solution?

**Comment by TARS-Question** [comment]
如果要部署Java微服，因为Java就依赖环境，所以这个跑不起来，有什么处理办法吗？

**Comment by TARS-Answer** [comment]
The node has docker in java environment, just use that.

**Comment by TARS-Answer** [comment]
节点有java环境的docker，使用那个就可以了。
