### ISSUE TITLE
 How do I create my own tcp in TarsCPP to connect to an external server (non-TAF)?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#626]

**Comment by TARS-Answer** [comment]
Use tcpclient in the tc library or socket_async (refer to https://doc.tarsyun.com/adminer/start/index.html#/tarsdoc/dev/tarscpp/tars-thirdparty-protocol.md)

**Comment by TARS-Answer** [comment]
用tc库里面的tcpclient，或者socket_async（可参考https://doc.tarsyun.com/adminer/start/index.html#/tarsdoc/dev/tarscpp/tars-thirdparty-protocol.md ）
