### ISSUE TITLE
  Using docker to create a virtual network, tarsframe work uses the host's IP, but an error will be reported when publishing.

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#627]
In tarsnode, I use docker to create a virtual network. In tarsframe-work, I use the host's ip. When tarsnode runs, I upload the package. When publishing, I get an error ("batchPatch err: NodeImp.cpp: patchPro: 111 | error: ip 172.25 .0.1 is invalid ") Is there a problem with the deployment process?

**Comment by TARS-Answer** [comment]
Use tcpclient in the tc library or socket_async (refer to https://doc.tarsyun.com/adminer/start/index.html#/tarsdoc/dev/tarscpp/tars-thirdparty-protocol.md)

**Comment by TARS-Answer** [comment]
用tc库里面的tcpclient，或者socket_async（可参考https://doc.tarsyun.com/adminer/start/index.html#/tarsdoc/dev/tarscpp/tars-thirdparty-protocol.md ）

**Comment by TARS-Question** [comment]
Is tarsnode directly bound to the host IP? I want to deploy a tarsnode with java environment on the same host. How should it be reasonable?

**Comment by TARS-Question** [comment]
tarsnode 直接绑定宿主 ip吗？我想在同一个主机上部署一个有java环境的tarsnode，应该如何部署才合理？

**Comment by TARS-Answer** [comment]
Start another tarsnode docker, and connect to tarframework in the mode of network bridge on the same machine. For example, in the tarsnode template, add: / tars / node <cmd_white_list_ip>, configuration, equal to framework ip, let go of the ip.

**Comment by TARS-Answer** [comment]
再启动一个tarsnode 的docker, 同一台机器上, 用网络桥接的模式和tarframework连接。例如在tarsnode模板里面, 增加: /tars/node<cmd_white_list_ip>, 配置, 等于framework ip，把ip放开一下。

**Comment by TARS-Question** [comment]
Is it as shown in the figure below?

> ![#627](https://user-images.githubusercontent.com/66677505/86152897-704c5b80-bb33-11ea-9b58-f60da3d30690.png)

**Comment by TARS-Question** [comment]
是否如下图所示？

> ![#627](https://user-images.githubusercontent.com/66677505/86152927-7c381d80-bb33-11ea-9058-023280f7f049.png)

**Comment by TARS-Answer** [comment]
If the corresponding position of the remark map is changed to cmd_white_list_ip = xx.xx.xx.xx, it needs to be restarted to take effect.

**Comment by TARS-Answer** [comment]
如备注图对应位置改为cmd_white_list_ip=xx.xx.xx.xx，需要重启后生效。

**Comment by TARS-Question** [comment]
After rebooting, this configuration will disappear, what should I do? The tarsnode node is configured with a whitelist of frameworks and cannot be released. In the tarsnode template, after I have set the ip to framword, the tarsnode still reports an error after restarting batchPatch err: NodeImp.cpp: patchPro: 111 | error: ip 172.25.0.1 is invalid.

**Comment by TARS-Question** [comment]
重启后这个配置就没了，怎么办？tarsnode 节点配置了framework的白名单还是发布不了。tarsnode模版里面我已经设置了ip为framword 的ip之后，tarsnode 重启后还是发布报错 batchPatch err:NodeImp.cpp:patchPro:111| error:ip 172.25.0.1 is invalid。

**Comment by TARS-Answer** [comment]
The docker restart framework is gone, don't restart. It is recommended to replace the IP bound to the framework with a virtual tar network, so that there is no problem in the unified network disconnection. But if the ip changes, you need to redeploy the microservice.

**Comment by TARS-Answer** [comment]
重启framework的docker是没了，别重启。推荐把 framework 绑定的ip 换成虚拟的tar网络，这样在统一网断里面就没有问题了。但ip变了就需要重新部署微服。
