### ISSUE TITLE
The tars framework now accesses http. Can it be changed to https?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#628]
Will this be supported in the future?

> ![#628(1)](https://user-images.githubusercontent.com/66677505/86153247-f2d51b00-bb33-11ea-9c3f-38e1b7ae92e1.jpg)

**Comment by TARS-Answer** [comment]
It can be changed so that the data is encrypted. The tup layer is re encrypted, and the benefit is not high. Some scenarios can be used.

**Comment by TARS-Answer** [comment]
可以改的，这样数据就是加密了。tup层再加密，收益不高，一些场景可以用。

**Comment by TARS-Question** [comment]
Do you only need to set the encryption mode when communicating between tar services? Is this the picture below? Is java supported now?

> ![#628(2)](https://user-images.githubusercontent.com/66677505/86154230-5b70c780-bb35-11ea-9a42-71dd80fd57b7.jpg)

**Comment by TARS-Question** [comment]
那tars服务间通讯时，是否只需要设置下加密方式就可以了？是下面这个图吗？java目前已经支持了吗？

> ![#628(2)](https://user-images.githubusercontent.com/66677505/86154283-6f1c2e00-bb35-11ea-928c-3ac53f5470f8.jpg)

**Comment by TARS-Answer** [comment]
This is tarscelint = > tarsserver uses the encryption mode when setting up scocket. HTTPS means that when your service needs to be used by your business side, you can use HTTPS to provide services, and the communication between tar services is the same.

**Comment by TARS-Answer** [comment]
这个是tarscelint => tarsServer在建立scocket的时候使用加密的模式；https是指你的服务要给你业务端使用的时候，可以使用https来提供服务 ，tars服务之间的通信不变。
现在这个版本还不支持。2.0.0的java版本会加上。

**Comment by TARS-Question** [comment]
No relevant configuration was found in the communicator config, or where did it need to be configured?

**Comment by TARS-Question** [comment]
在CommunicatorConfig里没有找到相关配置，还是说需要在哪里配置的？

**Comment by TARS-Answer** [comment]
Not all communications are encrypted through SSL channel, so the internal encryption support mentioned above is figure  in the remarks.
![6](https://user-images.githubusercontent.com/66677645/86154598-e05be100-bb35-11ea-94ca-b59db9e4dd31.jpg)

**Comment by TARS-Answer** [comment]
不是CommunicaotrConfig把所有的通信都走加密SSL通道，所以上面说的这个内部的加密支持是备注图所示。
![6](https://user-images.githubusercontent.com/66677645/86154657-f2d61a80-bb35-11ea-8ca7-11e8b57b09d4.jpg)

**Comment by TARS-Question** [comment]
Is group1 and group2 cross machine room? How to deal with the security of the communication between two tars background services across the computer room?

> ![#628(3)](https://user-images.githubusercontent.com/66677505/86154672-f7023800-bb35-11ea-8709-674cfef29593.jpg)

**Comment by TARS-Question** [comment]
请问group1与group2是跨机房吗？跨机房两个tars后台服务之间通讯的安全又该如何处理？

> ![#628(3)](https://user-images.githubusercontent.com/66677505/86154730-08e3db00-bb36-11ea-9e40-0571817fc1bb.jpg)

**Comment by TARS-Answer** [comment]
Group1 and group2 do not cross machine rooms. There is a unified agent service across machine rooms.

The above figure refers to the concept of application group set, and the meaning of group1 and group2. Even in multi-site computer rooms, the communication is also connected by VPN, so it is invisible on the tars platform.

From Shanghai computer room a to Nanjing computer room B, there is not a public network, but a special dedicated line or VPN. This part is also encrypted.

**Comment by TARS-Answer** [comment]
group1与group2不跨机房，跨机房有个统一的代理服务。
上面的这个图是指他的应用分组set的概念，group1和group2的意思。即使是多地的机房，通信也是使用的是vpn链接的，所以在tars平台上面，也是一个不可见的。
上海机房a到南京机房B，不是走的公网，是有专门的专线或者vpn相联的，这一部分是也是加密的。

**Comment by TARS-Question** [comment]
If business service 1 and business service 2 are both hung, will the request be transferred to business service 3 of another computer room?

**Comment by TARS-Question** [comment]
如果业务服务1与业务服务2都挂了的话，那会把请求转到另一个机房的业务服务3上吗？

**Comment by TARS-Answer** [comment]
If set is not configured, you can read the address in the notes carefully.

**Comment by TARS-Answer** [comment]
如果没有配置set，则轮训转发的，可以仔细读一下备注中地址这篇。
