### ISSUE TITLE
Is tars Java in 1.7.1 not supported for coloring logs?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#629]

**Comment by TARS-Answer** [comment]
(see https://github.com/TarsCloud/TarsJava/blob/master/docs/tars_java_user_guide.md  and note Figure) after 1.7, the dyeing log and MDC mode of logbook processing will be more flexible than the original, and cover more demand scenarios. You can combine MDC and tars documents to process according to specific scenario requirements.
![QQ图片20200701005001](https://user-images.githubusercontent.com/66677645/86153951-fcab4e00-bb34-11ea-9cf8-58ed86542d28.jpg)

**Comment by TARS-Answer** [comment]
(见  https://github.com/TarsCloud/TarsJava/blob/master/docs/tars_java_user_guide.md  与 备注图)1.7以后的染色日志和处理走LOGBACK的MDC的模式哈，会比原本的更灵活，且覆盖的需求场景更多一些，可以结合MDC和TARS的文档按具体的场景需求处理即可。
