### ISSUE TITLE
  As shown in the figure, to process remote logs, we need to make this jar package and put it in our project, or under Maven dependency?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#630]
> ![#630](https://user-images.githubusercontent.com/66677505/86153804-c1108400-bb34-11ea-8220-79379b0098fb.jpg)

**Comment by TARS-Answer** [comment]
Just pack it and put it under your project. Subsequent versions will be deployed to the official pom.

**Comment by TARS-Answer** [comment]
需要打包一下放到你的项目下就好。后续的版本会deploy到正式的pom上。
