### ISSUE TITLE
Are there any conflicts between tarsnode and framework docker installed on one host machine?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#632]
I encountered a problem. After restarting the node, the framework can run normally, but the node cannot run. Restart the framework, the node can run normally, but the framework service will hang.

**Comment by TARS-Answer** [comment]
You are all deployed with -net=host. In this case, the ports will conflict, and you need to create a virtual network to solve it.

**Comment by TARS-Answer** [comment]
你都是—net=host部署的吧, 这样做端口会冲突，需要创建虚拟网络解决。

**Comment by TARS-Question** [comment]
The net changed to a virtual one, or the previous error (see notes 1 and 2), how to solve it? There is no problem with php execution path determination. Manual execution of the script service can be up, and there is no problem with the output of environment variables, but when executed on the platform, it will overwrite the config and script every time. Is there a way not to overwrite the script? Restarting tarsnode will not work. The problem now is that business services cannot be started or restarted on the platform. Manual script execution is fine. If the service is started manually, Active on the platform has been changing.

**Comment by TARS-Question** [comment]
net换了虚拟的，还是出现和之前的错误（见备注图1和2），怎么解决？php执行路径确定没问题，手动执行脚本服务可以起来，输出环境变量也没问题，但在平台执行，每次都会覆盖config和脚本，有没有办法不覆盖脚本呢？重启tarsnode也不行。现在的问题是业务服务在平台启动不了，也重启不了，手动执行脚本可以。如果是手动启动的服务，平台上的Active一直在变动。
