### ISSUE TITLE
What is the reason why the local development server always reports errors, but the client can call it normally?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#633]
Local development, why does the server always report this error: com.qq.tars.rpc.exc.CommunicatorConfigException: |error occurred on create proxy, servant endpoint is empty! But the client can be called normally, what is the reason?

**Comment by TARS-Answer** [comment]
This is caused by a configuration error. If you use it on the platform, you can get the communicator directly.

**Comment by TARS-Answer** [comment]
这个是由于配置错误导致的，在平台上使用，直接获得communicator即可。
