### ISSUE TITLE
Where will the cache be updated?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#634]
> ![#634](https://user-images.githubusercontent.com/66677505/86265212-1bbde480-bbf6-11ea-8748-615e9662108d.jpg)

**Comment by TARS-Answer** [comment]
The code below the picture shows that the proxy object will be created when it is controlled in the cache and string2proxy will be used when calling the target service.

**Comment by TARS-Answer** [comment]
图片下面的代码有，代理对象在缓存中控的时候会创建，在调用目标服务的时候，会使用string2proxy。
