### ISSUE TITLE
How is code management and code compilation used in tars?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#635]
> ![#635](https://user-images.githubusercontent.com/66677505/86265405-53c52780-bbf6-11ea-8837-f288dadbfa78.jpg)

**Comment by TARS-Answer** [comment]
There are compiled pages in the web, but they are not opened by default. Java may not work. (Pb here means protobuf)

**Comment by TARS-Answer** [comment]
web里面有带编译页面，不过默认没打开，Java的话可能不行。(这里的PB是protobuf的意思)
