### ISSUE TITLE
Does the C + + version support call chain?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#636]
It's said in the document that Java, go version support, and C + + is about to support. Do you know if they already support it?

> ![#636](https://user-images.githubusercontent.com/66677505/86365110-a876aa00-bcab-11ea-8d83-274d2d6a9683.jpg)

**Comment by TARS-Answer** [comment]
C + + should be supported, but bugs are not excluded.

**Comment by TARS-Answer** [comment]
C++应该是支持了，但是不排除有bug。
