### ISSUE TITLE
Can't time-consuming operations be performed in the business initialization interface?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#637]
In the initialize() function, the loop sleep test always turns off after a few seconds. Is there any timeout setting for other components? Version 2.4 used.

> ![#637](https://user-images.githubusercontent.com/66677505/86365261-dc51cf80-bcab-11ea-8390-0b8eb3e179c1.jpg)

**Comment by TARS-Answer** [comment]
Initialization cannot take too long, which will be killed by tarsnode.

**Comment by TARS-Answer** [comment]
初始化不能有太耗时的操作，这样会被tarsnode杀掉。
