### ISSUE TITLE
If I want to add a PHP extension and I can't find the PHP source code in the docker of TarsNode, what should I do?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#640]

**Comment by TARS-Answer** [comment]
You can compile and upload the image source yourself. Or you can try to print phpinfo, check the location of php.ini, make a replacement, and map the expanded directory to docker.

**Comment by TARS-Answer** [comment]
可以自己编译上传镜像源。或者可以尝试下，打印phpinfo，查看php.ini的位置，做一下替换，同时把拓展的目录映射到docker。
