### ISSUE TITLE
Is there any missing config file?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#644]
The service registered by tarsgo in the master reports an error.

> ![#644(1)](https://user-images.githubusercontent.com/66677505/86513971-f96bd700-be40-11ea-8e80-f3312e772bad.png)

There is no problem with direct addressing.

> ![#644(2)](https://user-images.githubusercontent.com/66677505/86513972-fbce3100-be40-11ea-96bf-b78048f5a2b7.png)

**Comment by TARS-Answer** [comment]
This error can be ignored, under normal circumstances xxx —config = xxx.conf, this configuration is for the tars framework.

**Comment by TARS-Answer** [comment]
这个错误可以不管, 正常情况下 xxx —config = xxx.conf, 这个配置是给tars框架用的。
