### ISSUE TITLE
ERP system, when deleting the basic department information, check whether it is referenced by other tables. What is the better solution?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#647]
In the erp system, there is a basic data for department information. Many other tables refer to this field. When deleting the basic department information, check whether it is referenced by other tables. Is there a better solution?

**Comment by TARS-Answer** [comment]
This entanglement point is mainly in the statistics of the related table data. If the original table is associated, the query complexity will increase. If the data is not related, the deleted data cannot be excluded. Usually, when the amount of data is small, it is directly related, and when the amount of data is large, it is processed through an intermediate table.

Solution:
1. MySQL foreign key + cascade delete
2. Soft delete, the DB component is compatible with soft delete logic.
It is generally recommended to soft delete, if necessary, it can be redundant.

**Comment by TARS-Answer** [comment]
这个的纠结点主要还是在对关联表数据统计的时候，如果关联原表会导致查询复杂度升高，不关联又无法排除已删除的数据。通常数据量小的时候直接关联，数据量大的时候通过中间表来处理。

解决方法：
1. MySQL外键+级联删除
2. 软删除，在DB组件兼容软删除逻辑。
一般建议软删除，必要的情况下，可以冗余。
