### ISSUE TITLE
Java has been installed and configured, the service prompt starts successfully, but the status is still off, the service port is not occupied, what is it?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#648]
Prompt cannot execute java|errno=No such file or directory, manually start the service can be successful, through the tar web platform, restart can not start the service, what is the reason?

**Comment by TARS-Answer** [comment]
tarsnode restarts, otherwise the environment variables will not take effect

**Comment by TARS-Answer** [comment]
tarsnode重启 否则环境变量不会生效
