### ISSUE TITLE
How to pass parameters to setLocator when calling microservices out of Tars environment?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#649]

**Comment by TARS-Answer** [comment]
The client calls, you can specify the master address tars.tarsregistry.QueryObj@tcp -h master IP -t 60000 -p 17890.

**Comment by TARS-Answer** [comment]
客户端调用，可以指定主控地址 tars.tarsregistry.QueryObj@tcp -h 主控IP -t 60000 -p 17890。

**Comment by TARS-Question** [comment]
Is there a single point of failure? What if this server goes down?

**Comment by TARS-Question** [comment]
这样是否会存在单点故障？如果这台服务器挂了怎么办？

**Comment by TARS-Answer** [comment]
It is possible to configure multiple IPs.

**Comment by TARS-Answer** [comment]
是可以配置多个ip的。

**Comment by TARS-Question** [comment]
tars.tarsregistry.QueryObj@tcp -h master IP -t 60000 -p 17890, can the master IP be filled in more than one?

**Comment by TARS-Question** [comment]
tars.tarsregistry.QueryObj@tcp -h 主控IP -t 60000 -p 17890， 主控IP可以填多个吗？
