### ISSUE TITLE
Alicloud VPS has an intranet IP address. If the node is successfully installed and cannot be found in the node management, what should I do?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#650]
AliCloud VPS, with intranet IP, automatic node installation is successful, and node management cannot be found, manual start prompt:
[set admin adapter] OK
[main exception]:[TC_Socket::bind] bind error :Cannot assign requested address

**Comment by TARS-Answer** [comment]
Look at the service configuration file, what is the ip, this is caused by the wrong ip

**Comment by TARS-Answer** [comment]
检查服务配置文件中的ip是多少, 这种问题一般都是ip不对导致的

**Comment by TARS-Question** [comment]
tars.tarsnode.config.conf
localip=172.17.184.102
endpoint=tcp -h 47.94.149.80 -p 19385 -t 60000
endpoint=tcp -h 47.94.149.80 -p 19386 -t 60000
With intranet and with extranet

**Comment by TARS-Question** [comment]
tars.tarsnode.config.conf
localip=172.17.184.102
endpoint=tcp -h 47.94.149.80 -p 19385 -t 60000
endpoint=tcp -h 47.94.149.80 -p 19386 -t 60000
有内网的有外网的

**Comment by TARS-Answer** [comment]
It is possible to configure multiple IP.

**Comment by TARS-Answer** [comment]
是可以配置多个ip的。

**Comment by TARS-Question** [comment]
It's a bit troublesome. If you don't have a gateway in front and you need to bind a virtual external network IP, you need to:
1 Binding 0.0.0.0
2 Create a private template:
`<tars>`
<application>
<server>
local = tcp -h 127.0.0.1 -p 9999 -t 3000
</server>
</application>
</tars>
The local port should not conflict with your service IP

**Comment by TARS-Question** [comment]
It's a bit troublesome. If you don't have a gateway in front and you need to bind a virtual external network IP, you need to:
1 Binding 0.0.0.0
2 Create a private template:
```
<tars>
<application>
<server>
local = tcp -h 127.0.0.1 -p 9999 -t 3000
</server>
</application>
</tars>
The local port should not conflict with your service IP
```
