### ISSUE TITLE
As shown in the figure, the configuration file is configured from the web control terminal, how do I get it in the go code

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#653]
> ![#653](https://user-images.githubusercontent.com/66677505/86612455-bb0e1d80-bfe2-11ea-80cd-e01558c3f76a.png)

**Comment by TARS-Answer** [comment]
I suggest you use the yaml format directly.

**Comment by TARS-Answer** [comment]
建议你直接用yaml格式。

**Comment by TARS-Question** [comment]
If it is in yaml format, how to get this service on the server side. I don't seem to provide such a method through tars.xxxx (such as tars.GetServerConfig()). Do you need to parse the file?

**Comment by TARS-Question** [comment]
如果是yaml格式，在服务端怎么得到这个服务。我通过  tars.xxxx好像没有提供这样的方法（例如tars.GetServerConfig() 这样的方法）。需要解析文件吗？

**Comment by TARS-Answer** [comment]
Pull it down and analyze it yourself. Pull from the remote to the local hard drive, read it from the hard drive yourself, and then parse it into the yaml format.

**Comment by TARS-Answer** [comment]
拉下来自己解析。从远程拉到本地硬盘, 自己从硬盘读取, 然后解析成yaml格式。
