### ISSUE TITLE
As shown in the figure, why are there so many 127.0.0.1 connections in the same process?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#654]
> ![#654](https://user-images.githubusercontent.com/66677505/86612712-20faa500-bfe3-11ea-88ea-553df18ab042.png)

**Comment by TARS-Answer** [comment]
Because the epoll notification is done with a handle.

**Comment by TARS-Answer** [comment]
因为用了句柄做的epoll的通知。
