### ISSUE TITLE
The tars environment is deployed on server A. if some services are deployed on server B, do you need to deploy a set of tars environment on server B?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#655]
I deployed the Tars environment on the A server. If I deploy some services on the B server and register their IP and port in the Tars registry, do I need to deploy a Tars environment on the B server?

**Comment by TARS-Answer** [comment]
The B server is the node server. The node server only needs to deploy tarsnode.

**Comment by TARS-Answer** [comment]
B 服务器就是节点服务器, 节点服务器只需要部署tarsnode即可。
