### ISSUE TITLE
Can I fill in my node address when adding a deployment node? I want to add a server address with public IP address. How to operate?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#656]
As shown in the figure below, when adding a deployment node, can I fill in my node address here? The intranet IP here is the intranet IP of tars registry. I want to add a server address with public IP address here. How to do it?
![#656(1)](https://user-images.githubusercontent.com/66677505/86613192-cf9ee580-bfe3-11ea-9670-afa23f118098.png)

**Comment by TARS-Answer** [comment]
You must install a tarsnode for the node server, and then specify this node when deploying the service, and bind it to the external network.

**Comment by TARS-Answer** [comment]
节点服务器你得安装一个tarsnode, 然后部署服务的时候, 指定这台节点, 绑定到外网。

**Comment by TARS-Question** [comment]
The structure I want to achieve is probably as shown in the Figure 2. The Tars environment is deployed on Tencent Cloud Server, and then the business is deployed on other Tencent Cloud Servers. But some of the business is still in the IDC computer room. I plan to deploy the business on a machine with a public IP and register it in the Tars registration center. The problem here is that when I set up the Tars environment, when I run the linux-install.sh script to deploy Tars, the bound network card is the internal network card (mainly the name of the public network card cannot be seen in ifconfig), I am in IDC After installing tarsnode on the machine, can I register in the Tars registration center?

**Comment by TARS-Question** [comment]
我要实现的结构大概如图2所示，在腾讯云服务器上部署了Tars环境，然后把业务部署在其他腾讯云服务器上。但是有部分业务还在IDC机房，我打算把业务部署在有公网ip的机器上，注册到Tars注册中心里面。这里的问题是，我在搭建Tars环境时，运行linux-install.sh脚本部署Tars的时候，绑定的网卡是内网网卡(主要是ifconfig里面看不到公网网卡的名称)，我在IDC机器上安装tarsnode之后，能注册到Tars注册中心里面吗？

**Comment by TARS-Answer** [comment]
As long as the network is connected, but your mode is all external IP, which may be insecure.

**Comment by TARS-Answer** [comment]
只要网络都是连通的就可以，但是你这个模式都是外网ip，可能会不安全。

**Comment by TARS-Question** [comment]
Remove the external network IP of the business server on the cloud, and build an agent on a cloud server with an external network to route to these business servers. In this case, can the IDC server access the business server normally?

**Comment by TARS-Question** [comment]
把云上的业务服务器外网ip去掉，在一台有外网的云服务器上搭建代理，来路由到这些业务服务器上。这样的话，IDC的服务器能正常访问业务服务器吗？

**Comment by TARS-Answer** [comment]
Yes, just be a general agent.

**Comment by TARS-Answer** [comment]
可以的，做个通用代理就行。

**Comment by TARS-Question** [comment]
Is Nginx OK? I used to think that this need to be the fourth layer of the network, TCP.

**Comment by TARS-Question** [comment]
Nginx可以吗？我之前以为这种需要做到网络的第4层，TCP。

**Comment by TARS-Answer** [comment]
No.

**Comment by TARS-Answer** [comment]
不行。
