### ISSUE TITLE
Push the configuration file to the service node. When parsing, it prompts why the file cannot be found?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#657]
I want to know the difference between the following two folder paths?
Both folders are on the node service node
1./usr/local/app/tars/tarsnode/data/Test.test/bin/conf.yaml
2./data/tars/tarsnode-data/Test.test/bin/conf.yaml
After I push the configuration file to the service node. When parsing, it prompts that the file cannot be found.

**Comment by TARS-Answer** [comment]
Normally, push is not required. When the service is up, it will automatically pull the configuration. There are APIs to help you pull the configuration.

**Comment by TARS-Answer** [comment]
正常不需要push, 服务起来的时候自动会去拉取配置, 有api帮你拉取配置的。

**Comment by TARS-Question** [comment]
How to release multiple Servants on one server? Are App.Server.Servant1 and App.Server.Servant2 published in the same service? For example, under TarsDemo.HelloService, a HelloObj provides RPC service, hello, and an executable program. The other directly provides Web services and is another executable program. In Servants management, I added two.

> <img width="581" alt="#657(1)" src="https://user-images.githubusercontent.com/66677505/86690304-64343280-c03a-11ea-9fab-9464a9cc50cb.png">

But when it was released, there was only one.

> <img width="793" alt="#657(2)" src="https://user-images.githubusercontent.com/66677505/86690329-68605000-c03a-11ea-8106-31315c20013f.png">

The service file was successfully deployed and uploaded for the first time. The port was mapped on the host machine and the call was successful. An error was reported when adding one more.

**Comment by TARS-Question** [comment]
一个 Server 多个 Servant 怎么发布？App.Server.Servant1 和 App.Server.Servant2 要发布在同一个服务里面吗？例如在TarsDemo.HelloService 下，一个 HelloObj 提供 RPC 服务，打招呼，一个可执行程序。 另一个直接提供 Web 服务，是另一个可执行程序。在 Servants  管理里，我加成了两个。

> <img width="581" alt="#657(1)" src="https://user-images.githubusercontent.com/66677505/86690536-980f5800-c03a-11ea-9557-d21a360a89b4.png">

但是在发布的时候，只有一个。

> <img width="793" alt="#657(2)" src="https://user-images.githubusercontent.com/66677505/86690572-9fcefc80-c03a-11ea-8ac0-0cc5534c80de.png">

第一次顺利部署并上传了服务文件，端口映射出来在宿主机上并且调用成功了，再加一个的时候报错了。

**Comment by TARS-Answer** [comment]
Check the web log error. In fact, it is enough to deploy a service. In the business code, different servants are treated differently. One of them implements the rpc protocol listening port and the other listens to the web port. Deploying the same app and server on the same node will report duplicate errors.

**Comment by TARS-Answer** [comment]
查看web日志错误是什么。实际上这种部署一个服务就行了，在业务代码里边对不同的servant做不同处理，其中一个实现rpc协议监听端口，另一个监听web端口。 在同一个节点上部署相同的app、server，是会报重复错误的 。

**Comment by TARS-Question** [comment]
I looked at the log, the only constraint failed, I checked the database, and the last deleted thing was not deleted.

**Comment by TARS-Question** [comment]
翻看了一下日志，唯一约束失败，查看了数据库，上次删除的东西没删掉。

**Comment by TARS-Answer** [comment]
This is the application name, service name, and node. Repeat, you need to deploy before going offline, tars web v2.4.4+ version makes a more clear error prompt (see Figure
![QQ图片20200707105351](https://user-images.githubusercontent.com/66677645/86696679-4073eb00-c040-11ea-8a12-42e485e29a4a.jpg)
).

**Comment by TARS-Answer** [comment]
这个就是应用名、服务名、节点，重复了， 需要把之前的下线之后再部署，tars web v2.4.4+版本做更明确的错误提示（见图）
![QQ图片20200707105351](https://user-images.githubusercontent.com/66677645/86696788-5da8b980-c040-11ea-8724-3de37a33a597.jpg)
