### ISSUE TITLE
What's the reason for the prompt "TAS not find adapter"?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#658]
> ![#658](https://user-images.githubusercontent.com/66677505/86990529-5f54b780-c1cf-11ea-8dda-e62aaf00edcc.png)

**Comment by TARS-Answer** [comment]
The servantObj in your code may be different from the configuration. Check carefully that the characters in the addServant corresponding to your Server.cpp should be consistent with the web platform configuration.

**Comment by TARS-Answer** [comment]
可能你代码中的servantObj与配置的不一样，仔细检查下你Server.cpp对应addServant 中填的字符要跟web平台配置的一致。
