### ISSUE TITLE
Does tars have a link tracking log?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#660]

**Comment by TARS-Answer** [comment]
Yes, see you https://github.com/TarsCloud/TarsJava/blob/master/docs/tars_ tracing.md Now Zipkin is integrated.

**Comment by TARS-Answer** [comment]
有的，见https://github.com/TarsCloud/TarsJava/blob/master/docs/tars_tracing.md ，现在集成的是zipkin。

**Comment by TARS-Question** [comment]
Does Zipkin not support c + +, and what is the current solution for tar C + + link tracking? (see Notes)

**Comment by TARS-Question** [comment]
zipkin是不支持C++的吗，目前tars C++的链路追踪的解决方案是什么样子的？

> ![#660](https://user-images.githubusercontent.com/66677505/87064923-f1e26e80-c242-11ea-8075-de8222ea155c.jpg)

**Comment by TARS-Answer** [comment]
This CPP solution needs the next version.

**Comment by TARS-Answer** [comment]
这个cpp的方案需要下一个版本了。
