### ISSUE TITLE
How do you think about single connection and multi connection (or connection pool) design in RPC framework?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#666]
For example, Baidu's brpc uses a single connection by default, while Google's grpc reuses a connection based on http2?

Do multiple connections or connection pools theoretically have higher concurrent throughput and lower latency?

**Comment by TARS-Answer** [comment]
Packet reuse links can improve throughput and reduce latency. Simply speaking, reducing system calls is the biggest bottleneck.

**Comment by TARS-Answer** [comment]
小包复用链接才能提高吞吐和降低延时，简单说减少系统调用，纯服务，系统调用是最大的瓶颈。

**Comment by TARS-Question** [comment]
In the case of small packets, it is better to use fewer connections?

**Comment by TARS-Question** [comment]
就是说小包的情况下，应该用更少的连接更好？

**Comment by TARS-Answer** [comment]
Even in the reuse mode, multiple links are created. Generally, there are four sockets for the target IP node.

**Comment by TARS-Answer** [comment]
即使是复用的模式下，也是新建多个链接的。一般tars针对目标ip节点的socket是4个。

**Comment by TARS-Question** [comment]
So why does Dubbo use one? What are the reasons for this?

**Comment by TARS-Question** [comment]
那为什么dubbo这种用的是一个呢？这是出于什么考虑呢？

**Comment by TARS-Answer** [comment]
Not all of them are one. It's just that this configuration is sufficient in most cases, not fixed at 1. Especially when the contract is more than 10MB, connection needs to be added to improve some QPS. In this part, combined with the network infrastructure, an IP initiated port is only 65545 at most. When there are 10000 services in the back-end, the socket is definitely not enough. This part can solve this problem to a great extent. The second is the large-scale cluster environment, the traffic is particularly large, a large number of sockets will bring load to the router. Therefore, as long as the packet is not too large, in fact, a connection can also be used. It is OK to pay attention to the socket starvation effect.

This part needs a lot of theoretical knowledge, which is also the cornerstone of tar design. There will be sufficient theoretical basis for each design.

**Comment by TARS-Answer** [comment]
并不都是一个，只是说这个配置在大多数的情况下够用，不是固定是1，特别是在发包是10mb以上的时候，还是需要增加connection来提升部分qps。这一部分结合网络基础的情况，一个Ip可发起的端口，最大只有65545，当调用后端有1万个服务的时候，这个socket是肯定不够用的。这一部分可以很大程度解决这一个带来的问题。第二个是大规模的集群环境下，流量特别大，大量的socket会给路由器带来负载。所以，只要包不要太大，其实一个连接也可以，关注socket饥饿效应就可以了。
这一部分需要大量的理论知识，这个也是tars设计的基石，肯定会有各方面充足的理论基础给各个设计上面有支撑。
