### ISSUE TITLE
Proto3 protocol, java client calls C server, the result is null, no error is reported. It is suspected that there is a problem in parsing. Is there a switch that can print information when parsing exception?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#667]

**Comment by TARS-Answer** [comment]
The Pb of tars does not go directly through the Pb stream, which is suitable for the Pb flow call within the tars service;

If the C-side service directly provides the Pb flow, it will be good to follow the Pb official process request.

**Comment by TARS-Answer** [comment]
tars的pb不是直接走的是pb流，适合tars服务内部的Pb流调用；
若c端的服务直接提供pb的流，走pb官方的流程请求就好了。

**Comment by diracccc** [comment]
This issue is fixed by this [pr](https://github.com/TarsCloud/TarsJava/pull/121).
