### ISSUE TITLE
如果我协议想用protocolbuf 是不是得把tars 生成的cpp文件 里面的函数改成 非tars协议的函数 ？

### ISSUE THREAD

**Issue by ramosyang** [TarsCloud/Tars#67]

**Comment by ramosyang** [comment]
可以使用servantproxy的rpc_call或者async_rpc_call

**Comment by helloopenworld** [comment]
是的，参考我们第三方协议的https://github.com/Tencent/Tars/blob/master/docs/tars_cpp_http_demo.md
