### ISSUE TITLE
Is this code configuration read missing a slash? 

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#670]
Tarsgateway's FlowControlManager.cpp

> ![#670](https://user-images.githubusercontent.com/66677505/87156216-eb113580-c2ee-11ea-84b7-e59af79f299f.jpg)

**Comment by TARS-Answer** [comment]
It's like / main / < flow_ report_ Obj >?

It doesn't matter. It can be added or not.

**Comment by TARS-Answer** [comment]
是说要类似 /main/<flow_report_obj>  吗？
这个没关系， 加不加都可以的。
