### ISSUE TITLE
What's wrong with creating two communicators in a non tar framework?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#671]
Now, according to the business scenario, two sets of tar masters are deployed in two places. Individual services mainly communicate with other services under the two masters at the same time, so we want to create two new communicators.

> ![#671](https://user-images.githubusercontent.com/66677505/87156343-1bf16a80-c2ef-11ea-966b-04bc2f63e060.jpg)

**Comment by TARS-Answer** [comment]
No problem.

**Comment by TARS-Answer** [comment]
没有问题。
