### ISSUE TITLE
Will scrolling logs be automatically deleted when they exceed the number in the configuration file?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#673]
> ![#673](https://user-images.githubusercontent.com/66677505/87156517-5bb85200-c2ef-11ea-8ee6-9c6b3043878d.jpg)

**Comment by TARS-Answer** [comment]
It will be deleted automatically.

**Comment by TARS-Answer** [comment]
会被自动删除掉的。

**Comment by TARS-Question** [comment]
Modification tars.default It's OK to restart the service after that, right?

**Comment by TARS-Question** [comment]
修改tars.default后重启服务就可以了是吗？

**Comment by TARS-Answer** [comment]
Yes.

**Comment by TARS-Answer** [comment]
是的。
