### ISSUE TITLE
How to solve the problem when using docker.sh to create an image?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#675]
> ![#675](https://user-images.githubusercontent.com/66677505/87239683-9253b100-c444-11ea-994c-5814bfad977c.png)

**Comment by TARS-Answer** [comment]
For a centos source, refer to https://github.com/TarsCloud/TarsDocker.

**Comment by TARS-Answer** [comment]
换一个centos源，参照 https://github.com/TarsCloud/TarsDocker 。
