### ISSUE TITLE
I want to modify the code after packaging and publishing. Do I modify it locally and then compress and upload it?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#676]

**Comment by TARS-Answer** [comment]
Of course, you can get local development and debugging during debugging. The normal process is to package and upload the latest code, or you can find the project code directly modified in the tarsnode directory of the service deployment, but the second method also needs to restart the service.

**Comment by TARS-Answer** [comment]
当然, 调试时可以弄到本地开发调试。正常流程是打包上传最新代码，或者可以在服务部署的tarsnode目录下找到项目代码直接修改也行，但第二种方法还要重启服务才行。
