### ISSUE TITLE
How to call between various services? What method is used?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#678]

**Comment by TARS-Answer** [comment]
As shown in the figure, and refer to the document https://doc.tarsyun.com/adminer/start/index.html#/tarsdoc/hello-world/tarsphp.md.

**Comment by TARS-Answer** [comment]
如图所示，并参照文档https://doc.tarsyun.com/adminer/start/index.html#/tarsdoc/hello-world/tarsphp.md  。
