### ISSUE TITLE
How to solve the problem as shown in the picture?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#685]
MySQL is reinstalled, and the command line can be connected.

> ![#685](https://user-images.githubusercontent.com/66677505/87330693-8c0c2480-c56b-11ea-94ff-616530aa5fb4.png)

**Comment by TARS-Answer** [comment]
There may be many cases of failure to connect. It may be that during the installation of the Tars framework, the root account password is incorrectly filled in and the tars user cannot be created, or the mysql user may not have the corresponding host permission. You can check whether it is added in the user table in the mysql database. Corresponding permissions.

**Comment by TARS-Answer** [comment]
无法连接的情况可能有很多，可能在Tars框架安装过程中，root账号密码填错导致无法创建tars用户，也可能没有开mysql用户对应host的权限，可以在mysql数据库中的user表查看是否添加了对应权限。
