### ISSUE TITLE
As shown in the picture, what have I configured to cause errors?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#686]
![#686](https://user-images.githubusercontent.com/66677505/87330784-a514d580-c56b-11ea-8f51-5adf9e66e91f.png)

**Comment by TARS-Answer** [comment]
There is no connection library, you need to rely on tarscpp, right-click the project name property link library to add.

**Comment by TARS-Answer** [comment]
没有连接库，需要依赖tarscpp，项目名右键属性链接库添加。
