### ISSUE TITLE
Call the service more frequently and the service will restart. What is the solution?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#689]
> ![#689](https://user-images.githubusercontent.com/66677505/87428646-4146e700-c615-11ea-8b2c-4ef591fe3b70.jpg)

If the A service calls the B service interface too fast, the B service will restart, and there will be no problem calling at a very slow frequency.

**Comment by TARS-Answer** [comment]
There should still be problems with the service itself. For example, there are some thread safety problems in it. If the number of calls is small, it is generally difficult to trigger. If the concurrency is large, it is easy to trigger.

**Comment by TARS-Answer** [comment]
应该还是服务本身有问题，比如里面有些线程安全的问题，调用量小一般难触发，并发量大一些，就容易触发。

**Comment by TARS-Question** [comment]
There should still be problems with the service itself. For example, there are some thread safety problems in it. If the number of calls is small, it is generally difficult to trigger. If the concurrency is large, it is easy to trigger.

**Comment by TARS-Question** [comment]
The application has not found any problems for the time being.

**Comment by TARS-Question** [comment]
应用程序暂时没有发现有什么问题。

**Comment by TARS-Answer** [comment]
The application has not found any problems for the time being.

**Comment by TARS-Answer** [comment]
也没core？没道理突然退出，看看是否开启了core。

**Comment by TARS-Question** [comment]
How to set the core switch?

**Comment by TARS-Question** [comment]
怎么设置core开关？

**Comment by TARS-Answer** [comment]
Ulimit-c unlimited, first look at ulimit to see if the core is not allowed.

**Comment by TARS-Answer** [comment]
ulimit-c unlimited，先看下ulimit，看是不是不让core

**Comment by TARS-Question** [comment]
Ulimit - C is 0. Do I need to restart tars after opening it?

**Comment by TARS-Question** [comment]
ulimit -c是0，打开后要重启Tars吗？

**Comment by TARS-Answer** [comment]
Restart tarsnode, and then restart the service.

**Comment by TARS-Answer** [comment]
重启tarsnode，然后重启服务。

**Comment by TARS-Question** [comment]
The core file is still not found.

**Comment by TARS-Question** [comment]
还是没有发现core文件。

**Comment by TARS-Answer** [comment]
Did you exit from your program?

**Comment by TARS-Answer** [comment]
自己程序里exit了吗？

**Comment by TARS-Question** [comment]
No exit, but a panic.

**Comment by TARS-Question** [comment]
没有exit，但有Panic。

**Comment by TARS-Answer** [comment]
Panic will quit.

**Comment by TARS-Answer** [comment]
panic就会退出。
