### ISSUE TITLE
Which components of tar depend on the database? Does each component have its own independent database table?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#690]
Why is the remote log directory gone after a while?

> ![#690](https://user-images.githubusercontent.com/66677505/87445911-3a2ad380-c62b-11ea-8e73-1d39246407cb.png)

**Comment by TARS-Answer** [comment]
DB is in the template framework dB, which is on the tarslog server.

**Comment by TARS-Answer** [comment]
db都在模板framework-db, 都在这里面，在tarslog的服务器上。
