### ISSUE TITLE
The tarscpp library has been compiled and installed normally, and the tar protocol has been generated, but I did not generate cmakelist.txt after running 

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#691]
The cmake_tars_server.sh mentioned in the documentation is a tool for automatically generating cmakelists.txt.

> ![#691(1)](https://user-images.githubusercontent.com/66677505/87446189-8c6bf480-c62b-11ea-9991-b62423a4b807.png)

> ![#691(2)](https://user-images.githubusercontent.com/66677505/87446233-9aba1080-c62b-11ea-979b-c913fb63624f.png)

**Comment by TARS-Answer** [comment]
It is generated directly, plus the parameters
/usr/local/tars/cpp/script/cmake_tars_server.sh NetCheck NetCheckServer Net just fine

**Comment by TARS-Answer** [comment]
是直接生成的，加上参数
/usr/local/tars/cpp/script/cmake_tars_server.sh NetCheck NetCheckServer Net就好了
