### ISSUE TITLE
What is the reason for this error as shown in the remarks?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#692]
> ![#692](https://user-images.githubusercontent.com/66677505/87446442-e2409c80-c62b-11ea-8b89-882cf2ebe28c.png)

**Comment by TARS-Answer** [comment]
The version is not correct. It is recommended to update it completely.

**Comment by TARS-Answer** [comment]
版本不对，建议完整更新一下。

**Comment by TARS-Question** [comment]
If the error is reported in the remarks, it is because the static string STATUS_GRID_KEY in the servant; //User ID of grayscale
This paragraph is commented out, saying that the grayscale release is unstable, and then tars deleted this function. I released the note and compiled it. Will there be problems later?

**Comment by TARS-Question** [comment]
如备注图这个报错是因为servant里面static string STATUS_GRID_KEY;  //需要灰度的用户ID
这段被注释掉了，说是灰度发布不稳定，然后tars删除了这个功能，我把注释放开，编译通过了，后面会出现问题吗？

**Comment by TARS-Answer** [comment]
No problem.

**Comment by TARS-Answer** [comment]
不会有问题。
