### ISSUE TITLE
What is the reason to open go mod globally?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#694]
Go mod is turned on globally, and the dashed line in Remarks Figure 1 prompts bash: cd: C:\Users\Admin\go/src/github.com/TarsCloud/TarsGo/tars/tools/tars2go: No such file or directory.

> ![#694](https://user-images.githubusercontent.com/66677505/87558543-cd2b4280-c6eb-11ea-8046-49a72fc17cad.png)

**Comment by TARS-Answer** [comment]
Close go mod, it is recommended that go use version 13 or above, and go module use auto.

**Comment by TARS-Answer** [comment]
关闭go mod，建议go用13以上版本，gomodule用auto。
