### ISSUE TITLE
The main control and the node are currently on the same machine, and the deployed service cannot be started. I looked at the startup script and there is a space in the execution path. What could be the problem?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#695]
the framework version is 2.1.0

> ![#695](https://user-images.githubusercontent.com/66677505/87559978-8a6a6a00-c6ed-11ea-897a-9dc7fb9bb2ae.png)

**Comment by TARS-Answer** [comment]
That version of php has a bug, which was fixed afterwards. Now the more stable version is 2.4, you can upgrade it.

**Comment by TARS-Answer** [comment]
那个版本的php有bug, 之后修复了，现在比较稳定的版本是2.4，可以升级一下。

**Comment by TARS-Question** [comment]
Docker upgraded from 2.1.0 to 2.4.0 and found that the version number is stored in the data table, is there any effect?

**Comment by TARS-Question** [comment]
docker从2.1.0 升级2.4.0，发现版本号是存在数据表里的，有影响吗？

> ![#695(2)](https://user-images.githubusercontent.com/66677505/87856230-46c36a80-c950-11ea-95df-1a56321a71d8.png)

**Comment by TARS-Answer** [comment]
This version number can be ignored and is of little use.

**Comment by TARS-Answer** [comment]
这个版本号可以不管，用处不大。

**Comment by TARS-Question** [comment]
After upgrading from 2.1.0 to 2.4.0, the situation shown in Remark 3 will appear after restarting. But ~ business services can now be executed, what is the reason?

> ![#695(4)](https://user-images.githubusercontent.com/66677505/88202288-404c3000-cc7b-11ea-9683-77423d7b7c2b.png)

**Comment by TARS-Question** [comment]
从2.1.0升级到2.4.0，重启以后会有如备注图3所示的情况出现。但~业务服务，现在可以执行，这是什么原因？

> ![#695(4)](https://user-images.githubusercontent.com/66677505/88202416-6d98de00-cc7b-11ea-9797-dc32f847b5c6.png)

**Comment by TARS-Answer** [comment]
These services will not affect the business.

**Comment by TARS-Answer** [comment]
这几个服务挂了也不会影响业务。

**Comment by TARS-Question** [comment]
In the beginning, these basic services (see the picture above) are all running normally, but business services cannot be started on the platform. What is the reason? The following figure shows the service log.

> ![#695(5)](https://user-images.githubusercontent.com/66677505/88202668-ca949400-cc7b-11ea-82ce-affe50ffe739.png)

**Comment by TARS-Question** [comment]
一开始，这几个基础服务(见上一提问的图)，都运行正常，但业务服务在平台无法启动
这个是什么原因呢？下图是服务日志。

> ![#695(5)](https://user-images.githubusercontent.com/66677505/88202748-e730cc00-cc7b-11ea-99a9-e30f20fe6967.png)

**Comment by TARS-Answer** [comment]
Refresh the status , maybe the status is wrong when the service is started.

**Comment by TARS-Answer** [comment]
刷新一下状态, 可能服务刚起来状态不对。
