### ISSUE TITLE
The label indicates that Windows cannot be mounted because there is no such directory. What is the reason?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#696]
> ![#696](https://user-images.githubusercontent.com/66677505/87560486-1381a100-c6ee-11ea-9cbb-d741ac786711.png)

**Comment by TARS-Answer** [comment]
This is used to map time, just delete it, docker does not think too much about the windows system.

**Comment by TARS-Answer** [comment]
这个是用来映射时间的，删掉就可以了，docker没有过多考虑windows系统。
