### ISSUE TITLE
When I log in for the first time, it will prompt "system internal error" when changing the password, and check the log that the table is read-only. What is the possible reason?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#698]
The user permissions are given to the maximum.

> ![#698](https://user-images.githubusercontent.com/66677505/87560983-a15d8c00-c6ee-11ea-9867-2442c747991a.png)

**Comment by TARS-Answer** [comment]
It may be the problem of SLAVE parameters during deployment (see note 1); or this user may not have write permission for this table, and it needs to be set at the database level, try to manually execute sql in the terminal.

**Comment by TARS-Answer** [comment]
可能是部署的时候，SLAVE参数问题（见备注图1）；也可能这个用户对这张表的写权限没有，需要在数据库层面设置，尝试一下终端里手动执行sql。
