### ISSUE TITLE
What's the problem?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#699]
> ![#699](https://user-images.githubusercontent.com/66677505/87688258-55c3e480-c7b9-11ea-82d4-ce21be96f672.png)

**Comment by TARS-Answer** [comment]
After sending the http protocol to the stat service, check the related code of the call to see if you are actively sending requests to tarsstat.

**Comment by TARS-Answer** [comment]
把http协议发送到stat服务了,把调用的相关代码检查一下 ，查看自己是否主动发请求到tarsstat。
