### ISSUE TITLE
Compiled according to the tutorial, it still prompts that the tarsrpc plugin is unknown, how do I compile this protoc-gen-go plugin?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#700]
> ![#700(1)](https://user-images.githubusercontent.com/66677505/87688482-9d4a7080-c7b9-11ea-9ba5-fff590e719e2.png)

> ![#700(2)](https://user-images.githubusercontent.com/66677505/87688487-9e7b9d80-c7b9-11ea-91a8-b327e6d89dc4.png)

**Comment by TARS-Answer** [comment]
This plug-in is for the protobuf interface. The tars-node container comes with a compiled plug-in.

**Comment by TARS-Answer** [comment]
这个插件是给protobuf接口用的，tars-node容器中自带有个编译好的插件。

**Comment by Bingjian-Zhu** [comment]
@TARS-Answer 没找到您说的`tars-node容器中自带有个编译好的插件`插件位置，可以说下具体在哪里吗

**Comment by Bingjian-Zhu** [comment]
@TARS-Answer 同样按着教程，发现报`--go_out: protoc-gen-go: unknown plugin "tarsrpc"`错误，重试了很多遍都不行
