### ISSUE TITLE
What is the reason for the error reported by the client shown in Figure? 

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#701]
> ![#701(1)](https://user-images.githubusercontent.com/66677505/87688757-f7e3cc80-c7b9-11ea-9d11-47fb7116d374.png)

After the xxx.tars file is generated, the file has been modified, the interface is added, and then re-make releaseb, both sides have been modified. 

The client

> ![#701(2)](https://user-images.githubusercontent.com/66677505/87688850-15b13180-c7ba-11ea-898a-3e58e31d6ce3.png)

 imp.h

> ![#701(3)](https://user-images.githubusercontent.com/66677505/87688872-1c3fa900-c7ba-11ea-97ac-4a4cfe6ee2a4.png)

the client's Makefile

> ![#701(4)](https://user-images.githubusercontent.com/66677505/87688886-206bc680-c7ba-11ea-9b25-a6275b51a642.png)

**Comment by TARS-Answer** [comment]
The gameProxy is written incorrectly, you should use typedef tars::TC_AutoPtr<gameProxy> gamePrx.

**Comment by TARS-Answer** [comment]
gameProxy写错了，应该用typedef tars::TC_AutoPtr< gameProxy > gamePrx。
