### ISSUE TITLE
As shown in the figure, on the platform, service management->service monitoring, some basic services have no data, and all business services have no data. Is this normal?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#702]
The docker version is 2.4.0.

> ![#702](https://user-images.githubusercontent.com/66677505/87689150-73de1480-c7ba-11ea-811d-9dfda955626c.png)

**Comment by TARS-Answer** [comment]
Not normal. But it is normal for querystat to have no data. Both queries should have no data or very little data.

**Comment by TARS-Answer** [comment]
不正常。但querystat没数据是正常的，两个query应该都没数据或者很少数据。

**Comment by xiashulin** [comment]
![image](https://user-images.githubusercontent.com/11418033/114123966-f6e56300-9925-11eb-82d5-0bd9f1d5370e.png)
接口对比数据列表中，对比日的数据都是0是为啥？
