### ISSUE TITLE
It seems that tars is running, but the tar web, which accesses the public network through the browser, cannot be connected. What are the methods of investigation?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#703]
> ![#703](https://user-images.githubusercontent.com/66677505/87689308-a25bef80-c7ba-11ea-8dea-5b6f3ba54786.jpg)

**Comment by TARS-Answer** [comment]
Try telnet 3000 port, telnet can directly use the external network ip.

**Comment by TARS-Answer** [comment]
尝试telnet一下3000这个端口，telnet直接用外网ip即可。
