### ISSUE TITLE
I used Tencent cloud with 1 core 2GB and reported an error when compiling the source code of tars. How can I solve this problem?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#705]
> ![#705](https://user-images.githubusercontent.com/66677505/87819662-2d161a80-c89f-11ea-9643-396383679ea1.png)

**Comment by TARS-Answer** [comment]
The machine configuration is too low to compile with multi-threads, and the -j parameter cannot be used for 1 core.

**Comment by TARS-Answer** [comment]
机器配置太低，不能加多线程编译，1核不能用-j参数。
