### ISSUE TITLE
The time is not accurate, how to synchronize to become the latest time?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#706]
Source code compiled, mysql is installed by docker

> ![#706](https://user-images.githubusercontent.com/66677505/87819834-7cf4e180-c89f-11ea-8d4e-280ba0012ce5.jpg)

**Comment by TARS-Answer** [comment]
The reason may be that the virtual machine is used to install centos. When mysql is installed, it is not mapped to the host machine. You can try to correct the time zone of mysql in docker. The time zone needs to be synchronized.

**Comment by TARS-Answer** [comment]
原因可能是使用虚拟机装centos，安装mysql时候没有映射到宿主机，可以尝试将docker里的mysql的时区改正，时区需要同步。
