### ISSUE TITLE
A small question about the servant.

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#707]
During development and testing, the client directly connects to the service on the node node. The client configures the server parameters that need to be requested,

> ![#707(1)](https://user-images.githubusercontent.com/66677505/87819966-c6ddc780-c89f-11ea-9f56-1d286d74c632.png)

the name in front of @ and the back in @ If the IP port number does not match, it can still be called.

> ![#707(2)](https://user-images.githubusercontent.com/66677505/87819975-c8a78b00-c89f-11ea-914e-2789d60514f8.png)

Is it because the service name is not important when directly connected to the node?

**Comment by TARS-Answer** [comment]
Because the tars protocol server will verify this name, the http protocol is not important.

**Comment by TARS-Answer** [comment]
因为tars协议服务端会验证这个名称，所以http协议就不重要了。
