### ISSUE TITLE
When calling the service interface, this error occurred.

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#711]
> ![#711(1)](https://user-images.githubusercontent.com/66677505/87856276-ade11f00-c950-11ea-93d1-42cfd62de9e7.png)

The client log said that the link was closed, but the server received this request, what is the matter?

> ![#711(2)](https://user-images.githubusercontent.com/66677505/87856280-b3d70000-c950-11ea-9cbc-d43d656f0caa.png)

**Comment by TARS-Answer** [comment]
Client-to-server messages and server-to-client messages are asynchronous, tcp is full-duplex, and two channels are sent and received.

**Comment by TARS-Answer** [comment]
客户端到服务器的消息和服务器到客户端的消息是异步的，tcp是全双工的，收发走的是两条通道。
