### ISSUE TITLE
Is this added to the template configuration file?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#712]
> ![#712](https://user-images.githubusercontent.com/66677505/87856343-2ba52a80-c951-11ea-9f11-cfb2d2def457.jpg)

**Comment by TARS-Answer** [comment]
Yes, you need to add this node to the private template. When importing a project, you need to check whether the corresponding Zipkin package has been imported. Service a and service B need to have the corresponding Zipkin opened and imported. After reporting, you can see the specific data.

Java = > java can be used. Other mixed language calls are temporarily unknown.

**Comment by TARS-Answer** [comment]
是的，在私有模板里面要加上这个节点，项目引入的时候，要察看是否已经 引入对应的zipkin包，服务A、服务B都要有对应的zipkin的开启和引入，上报后就可以看得到具体的数据了。
java =>java的可以，其他的语言混合调用暂时未知。
