### ISSUE TITLE
The service monitoring as shown in the picture is not available. The error message is query 602. I have no corresponding localtime file in docker for windows. Is it because there is no time zone imported?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#714]
> ![#714](https://user-images.githubusercontent.com/66677505/87856387-6e670280-c951-11ea-80aa-52f6a5fd9fd4.png)

**Comment by TARS-Answer** [comment]
It does not matter, this is because yesterday's watch does not exist.

**Comment by TARS-Answer** [comment]
没关系，这是因为昨天的表不存在。
