### ISSUE TITLE
Is this 3001 of framwork? What is a management port?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#715]
> ![#715(1)](https://user-images.githubusercontent.com/66677505/87893753-60110780-ca73-11ea-803c-03062b4e93c1.png)

> ![#715(2)](https://user-images.githubusercontent.com/66677505/87893755-60a99e00-ca73-11ea-9c04-e55ac8229d18.png)

**Comment by TARS-Answer** [comment]
Remarks should not be shown in Figure 1, should be the service registration port, rpc port. The management port is a web port.

**Comment by TARS-Answer** [comment]
备注图1所示应该不是，应该是服务注册的端口， rpc的端口。管理端口是web端口。

**Comment by TARS-Question** [comment]
> ![#715(3)](https://user-images.githubusercontent.com/66677505/88201323-e434dc00-cc79-11ea-851e-4e74d9c2bfba.png)

> ![#715(4)](https://user-images.githubusercontent.com/66677505/88201325-e4cd7280-cc79-11ea-9e96-8cb91319bbea.png)

172.25.13 is the node of framewrok, and 172.25.1.5 is the node of work. 

What should be filled in for local?

> ![#715(5)](https://user-images.githubusercontent.com/66677505/88201451-0a5a7c00-cc7a-11ea-8d12-d4d9f3f68f8c.png)

**Comment by TARS-Question** [comment]
> ![#715(3)](https://user-images.githubusercontent.com/66677505/88201484-18100180-cc7a-11ea-8498-8bc94bacb1cb.png)

> ![#715(4)](https://user-images.githubusercontent.com/66677505/88201486-18a89800-cc7a-11ea-96b5-c803574343ea.png)

- 172.25.1.3是framewrok的节点，172.25.1.5是work的节点

还有这里所示的local应该填什么？

> ![#715(5)](https://user-images.githubusercontent.com/66677505/88201638-4988cd00-cc7a-11ea-8432-262b9cd47533.png)

**Comment by TARS-Answer** [comment]
The local is generated by the framework and does not need to be processed by yourself.

**Comment by TARS-Answer** [comment]
local是框架生成的，不需要自己处理。
