### ISSUE TITLE
Where can I see the version number of the corresponding tarsframework code for this image? And this stable?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#716]
https://hub.docker.com/r/tarscloud/framework

> ![#716(1)](https://user-images.githubusercontent.com/66677505/87893864-b9793680-ca73-11ea-82d8-b5b1a6ba82bc.jpg)

> ![#716(2)](https://user-images.githubusercontent.com/66677505/87893865-ba11cd00-ca73-11ea-836b-509d4974552a.jpg)

**Comment by TARS-Answer** [comment]
In tags. The latest version is v2.4.0, corresponding from 2.4.0. Stable is also the latest. Stable should not be 2.4.0, but the difference should be small. It hasn't changed much recently. It is recommended to use tag with version number as much as possible to avoid passive upgrade. In the future, it is recommended to use docker with version number.

**Comment by TARS-Answer** [comment]
在Tags中，最新的版本为v2.4.0，从2.4.0开始对应，stable目前也是最新的。stable应该不是2.4.0的, 但是差别应该也不大了, 最近没怎么改了。建议尽量使用带版本号的Tag，可以避免被动升级。以后建议就用带版本号的docker了。

**Comment by TARS-Question** [comment]
- How does this tar node correspond to the tarsframe version? Do you also push the version corresponding to 2.4.0?

https://hub.docker.com/r/tarscloud/tars-node

> ![#716(3)](https://user-images.githubusercontent.com/66677505/88202112-f82d0d80-cc7a-11ea-9128-92fcfa956705.jpg)

**Comment by TARS-Question** [comment]
- 这个tars-node跟tarsframe版本怎么对应？是否也推送下对应 2.4.0 的版本？

https://hub.docker.com/r/tarscloud/tars-node

> ![#716(3)](https://user-images.githubusercontent.com/66677505/88202137-067b2980-cc7b-11ea-885c-636e3bcefa84.jpg)

**Comment by TARS-Answer** [comment]
This is not necessary. Node is just the runtime environment. The tarsnode application will be installed automatically after the container starts and successfully connects to the framework, so there is no version concept.

**Comment by TARS-Answer** [comment]
这个不用，node只是运行时环境。TarsNode应用会在容器启动并成功连接Framework后自动安装，所以没有版本概念。
