### ISSUE TITLE
How is the directory after - CP added here? How to deal with this part of the address in the program?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#717]
> <img width="901" alt="#717" src="https://user-images.githubusercontent.com/66677505/87893998-0d841b00-ca74-11ea-92c7-b383657548f4.png">

**Comment by TARS-Answer** [comment]
This is implemented in the tarsnode part. It will help you to bring the address of this part. CP does not and does not affect; terminal problems may be plug-in problems.

**Comment by TARS-Answer** [comment]
这个是tarsnode部分实现的，会帮你带上这一部分的地址。cp里面没有也不影响；终端的问题 可能是插件的问题。
