### ISSUE TITLE
Are these two classes automatically generated? 

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#718]
> ![#718](https://user-images.githubusercontent.com/66677505/87894132-74a1cf80-ca74-11ea-93f8-0a3f1ed9a395.jpg)

What kind of order should be executed? Or where are the documents?

**Comment by TARS-Answer** [comment]
It's auto generated, with an MVN plug-in. Automatically generated plug-ins can run on MAC and Linux. (see https://github.com/TarsCloud/plugins/tree/master/java-protobuf-plugin  and  http://note.youdao.com/noteshare?id=ec37e7283c946dc98b9c03c6d0870a0e  and  https://github.com/TarsCloud/plugins)

**Comment by TARS-Answer** [comment]
是自动生成的，有个mvn插件。自动生成的插件可以在mac和linux运行。(见文档https://github.com/TarsCloud/plugins/tree/master/java-protobuf-plugin 和 http://note.youdao.com/noteshare?id=ec37e7283c946dc98b9c03c6d0870a0e 和 https://github.com/TarsCloud/plugins )
