### ISSUE TITLE
Why is the new node not displayed in the node list after I add a new node?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#726]
> ![#726](https://user-images.githubusercontent.com/66677505/87979088-17555f00-cb04-11ea-8683-576b7df16ee3.png)

**Comment by TARS-Answer** [comment]
Look at the tarsnode log of the corresponding machine, it may be a port problem. Or try to delete the original record from the mysql table and add it again.

**Comment by TARS-Answer** [comment]
看一下对应机器的tarsnode日志，有可能是端口的问题。或者尝试去mysql的表删除原来的记录，再添加一次。
