### ISSUE TITLE
How does TARS implement https in go language?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#727]

**Comment by TARS-Answer** [comment]
Go can use the go package method, https and tars are irrelevant, you need to implement it yourself.

**Comment by TARS-Answer** [comment]
go用go包方式就可以了, https和tars就无关了, 需要自己实现。

**Comment by TARS-Question** [comment]
How to use crt and key certificate files? Specifically, when deploying on TARS, how to load these certificates?

**Comment by TARS-Question** [comment]
如何使用crt和key等证书文件？具体到TARS上部署的时候，如何加载这些证书？

**Comment by TARS-Answer** [comment]
It can be made into remote configuration, pulled to the local, and then loaded; or packaged with the bin file for release.

**Comment by TARS-Answer** [comment]
可以做成远程配置, 拉取到本地, 然后加载；或者和bin文件打包到一起发布。
