### ISSUE TITLE
Does TarsGateway support HTTPS?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#728]

**Comment by TARS-Answer** [comment]
https entry is supported, but you need to compile the configuration yourself, enable https, and make your own certificate. Or you can add a NGINX outside, https forwarding http is enough.

**Comment by TARS-Answer** [comment]
支持https入口，不过需要自己编译配置，开启https，自己制作证书等。或者可以在外面加个NGINX，https转发http就可以了。
