### ISSUE TITLE
Tar + Yii remote download, if not exit, the following situation will appear. 

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#730]
> ![#730(1)](https://user-images.githubusercontent.com/66677505/87979473-b2e6cf80-cb04-11ea-8af9-c08e8f95d767.jpg)

> ![#730(2)](https://user-images.githubusercontent.com/66677505/87979479-b417fc80-cb04-11ea-8b42-d458839ca87b.jpg)

What function can be used instead of exit in the download.

**Comment by TARS-Answer** [comment]
You don't have to look at the swote document from the perspective of tars and Yii.

**Comment by TARS-Answer** [comment]
不用从tars和yii角度，看swoole文档。
