### ISSUE TITLE
If the two are all tars protocols, I can call A:: async_ in A. response_ Function, but how to do it in the HTTP protocol?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#732]
Asynchronous nested call:
After receiving the HTTP request from the web, a calls B service asynchronously, and wants to return to web asynchronously after B service returns.

> ![#732](https://user-images.githubusercontent.com/66677505/87979637-f0e3f380-cb04-11ea-8c23-33fd4bf6d8fa.jpg)

**Comment by TARS-Answer** [comment]
Take current and send response directly.

**Comment by TARS-Answer** [comment]
拿着current直接sendResponse。
