### ISSUE TITLE
The virtual machine was powered off. After the machine was restarted, the application services of tar could not be started, running / usr / local / APP / tars/ check.sh , show the content of the picture below. What's the situation?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#733]
![#733(1)](https://user-images.githubusercontent.com/66677505/87979826-3accd980-cb05-11ea-8614-ec76441d0cc6.jpg)

The normal running virtual machine does not find any application directory under the / tars directory, only the services of stars.

**Comment by TARS-Answer** [comment]
The directory does not exist. Check it. It is estimated that the configuration file of tarsnode is empty. Take a look. This problem is known and has not been modified.By the way, mirror docker libstdc.so Up.

**Comment by TARS-Answer** [comment]
目录不存在，检查一下，估计tarsnode的配置文件为空了，你看一下，这个问题已知了，还没修改。
顺便把docker镜像 libstdc.so 升一下。
