### ISSUE TITLE
Tarsjava: > = v1.7.2 gateway requires version 1.7.2? 

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#735]
Now Maven center still seems to be 1.7.1.

**Comment by TARS-Answer** [comment]
It is 1.7.2, and it has been to the central library. The gateway is supported in all language versions.

**Comment by TARS-Answer** [comment]
有1.7.2了，已经到中央库了，已经全语言版本都支持这个网关了。
