### ISSUE TITLE
Three questions about tar HTTP server.

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#736]
> ![#736](https://user-images.githubusercontent.com/66677505/87980284-f0982800-cb05-11ea-9d22-e8f526d4eec1.jpg)

1. 

@ tarshttpservice ("httpobj") this is to declare an obj and register it with TAF, right?

2. 

Is there a monitoring system for tar HTTP?

3. 

How can the tar protocol of tar server be quickly converted to the JSON protocol of HTTP?

**Comment by TARS-Answer** [comment]
1. Tarshttpservice is a functional annotation, which indicates that the application can have the capability of HTTP service, and obtain the port from the configuration of servant to listen to the corresponding port to provide services.
2. The monitoring request of httpservice is not available. It can report the monitoring information by itself.
3. You can use the gateway directly. Now it is open. You can have a try.

**Comment by TARS-Answer** [comment]
1、TarsHttpService是一个功能性注解，表示这个应用可以拥有HTTP服务的能力，并从servant的配置中获取端口侦听对应的端口提供服务。
2、httpService的监控请求并没有，可以自己上报监控信息。
3、可以直接用网关，现在已经开放了，可以试一试。

**Comment by TARS-Question** [comment]
Does this mean tupproxy? Is there a java version gateway?

**Comment by TARS-Question** [comment]
是指的tupproxy吗，有java版本的网关吗？

**Comment by TARS-Answer** [comment]
https://github.com/TarsCloud/TarsGateway
It can completely replace tupproxy. All gateway forwarding configurations can be configured on the tarsweb platform. Now Java language supports it.

**Comment by TARS-Answer** [comment]
https://github.com/TarsCloud/TarsGateway
可以全面替换tupProxy，所有网关转发配置，tarsweb平台上都可以配置了，现在java语言都是支持的。
