### ISSUE TITLE
Why does tarsgeway rely on tarsgateway_ user_ system？

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#738]

**Comment by TARS-Answer** [comment]
This should not depend on it. Why dependence?

**Comment by TARS-Answer** [comment]
不依赖吧?为什么说依赖?

**Comment by TARS-Question** [comment]
The token required to install gateway is from user_ System.

**Comment by TARS-Question** [comment]
安装gateway需要的token是从user_system获取的。

**Comment by TARS-Answer** [comment]
To install the gateway interface, you need to call the web, and the token calling the web is generated by the user system.

**Comment by TARS-Answer** [comment]
安装gateway接口，需要调用web，调用web的token都是用户系统生成的。

**Comment by harkhuang** [comment]
源码安装  部署getway 应该使用哪个ip呢?
