### ISSUE TITLE
The framework will have a tars in the client of low version 1.5.0_ client.log Log is the log file must be typed?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#739]
It is found that only the client is used, and this log file is not available online. What is the general question?

**Comment by TARS-Answer** [comment]
This is the client log controller added in last year's version. Only the client will automatically output a separate log controller.

**Comment by TARS-Answer** [comment]
这是去年的版本添加的客户端日志控制器，只有客户端会自动输出单独的日志控制器。
