### ISSUE TITLE
What to do if the token cannot be obtained when installing tarsgeway?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#742]
> ![#742(1)](https://user-images.githubusercontent.com/66677505/87981291-94360800-cb07-11ea-94ee-4eb4e49f63cc.jpg)

**Comment by TARS-Answer** [comment]
When providing the client with HTTP protocol capability, you can use this gateway. You don't need to start an HTTP service by yourself. It provides HTTP capability for all tar services.

**Comment by TARS-Answer** [comment]
提供给客户端http协议能力的时候，可以使用这个网关，不需要自己启动一个http服务了，统一给所有的tars服务提供了 http的能力。

**Comment by TARS-Question** [comment]
It's not the latest version. I don't see the user center.

> ![#742(2)](https://user-images.githubusercontent.com/66677505/88198913-cd40ba80-cc76-11ea-80d4-01668f1e4830.jpg)

**Comment by TARS-Question** [comment]
不是最新版本，没看到用户中心。

> ![#742(2)](https://user-images.githubusercontent.com/66677505/88198947-d92c7c80-cc76-11ea-93b1-f5fde4a8ca5f.jpg)

**Comment by TARS-Answer** [comment]
Change Chrome browser, or clear the browser cache, maybe JS cache, or command + R refresh. If none of these works, upgrade the version.

**Comment by TARS-Answer** [comment]
换Chrome浏览器，或者把浏览器的缓存清了，可能是js缓存了，再或者command+R刷新一下。都不行升级一下版本看看。
