### ISSUE TITLE
What happened to this mistake?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#744]
> ![#744(1)](https://user-images.githubusercontent.com/66677505/87981444-dbbc9400-cb07-11ea-9821-0c926a41b106.jpg)

- The document link on GitHub also failed. 

> ![#744(2)](https://user-images.githubusercontent.com/66677505/87981449-dd865780-cb07-11ea-993a-f9618283244d.jpg)

- The new version of tarsweb and tarsframwork is still the old version, not docker deployment. After I download the source code, I execute the SQL statement in the SQL folder, then change the configuration in the config, mainly change the database address and registry address, and set all enable to false, and finally execute NPM run PRD.

**Comment by TARS-Answer** [comment]
TarsWeb has a bug that the ticket is undefined. This problem has been fixed in the latest commit version. You can try to download the latest version and reinstall it. At the same time, TarsWeb currently has a bug in authentication, which may not be turned off if it is false in config.

**Comment by TARS-Answer** [comment]
TarsWeb存在ticket为undefined的bug，已经在最新的commit版本中修复了这个问题，可以尝试下载最新的版本重新安装。同时TarsWeb目前鉴权存在bug，在config中为false可能也无法关掉。
