### ISSUE TITLE
The business service platform cannot be started. I found that the start and stop scripts are not the same. The start php command stop is the execution path. Is there any intention to do this? 

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#745]
This is uniformly configured in the template, but there are two in the script.

> ![#745](https://user-images.githubusercontent.com/66677505/88203025-4393eb80-cc7c-11ea-80bb-fa17faded60d.jpg)

**Comment by TARS-Answer** [comment]
Take a look at the service template. PHP is configured in the template, which should be consistent.

**Comment by TARS-Answer** [comment]
看看服务模板, php这个是模板里面配置的, 按说应该要一致。
