### ISSUE TITLE
Remote login, it is not convenient to stop using the web. Tars cpp2.x is on the node side, what is the script command to manually stop the service?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#748]

**Comment by TARS-Answer** [comment]
There is no way. After manually killing it, as long as the tarsnode node is still there and the node service status is active, the service will continue to be activated. In the source code implementation, only the stopServer that calls the node node will set the service status to inactive.

**Comment by TARS-Answer** [comment]
没有办法，手动kill掉之后，只要tarsnode节点还在，并且节点服务状态为active，就会一直拉起服务。源码实现中，只有调用node节点的stopServer才会将服务状态设置为inactive。
