### ISSUE TITLE
As shown in the figure, tarNode has been started when the framework is deployed. Do I need to install tarNode separately in this step of TarNode deployment?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#751]
> ![#751(1)](https://user-images.githubusercontent.com/66677505/88412296-e7f86800-ce0b-11ea-8d46-de569b1f18a7.jpg)

> ![#751(2)](https://user-images.githubusercontent.com/66677505/88412298-e890fe80-ce0b-11ea-9770-39eadf208524.jpg)

**Comment by TARS-Answer** [comment]
This is for other servers, that is, if the framework is on machine A and the business service is on machine B, you need to install tarNode separately on B. The same node is not needed.

**Comment by TARS-Answer** [comment]
这个是给其他服务器准备的，就是说框架在A机器，业务服务在B机器的话就需要给B上单独安装tarNode，同节点是不需要了。
