### ISSUE TITLE
Must 3000 and 3001 be specified for this web port?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#753]
- I can't access the web with my 3008.

> ![#753(1)](https://user-images.githubusercontent.com/66677505/88412783-acaa6900-ce0c-11ea-9586-d7aef9f955e7.jpg)

> ![#753(2)](https://user-images.githubusercontent.com/66677505/88412786-addb9600-ce0c-11ea-8231-2d474ce5a892.jpg)

**Comment by TARS-Answer** [comment]
3008:3000
3009:3001

**Comment by TARS-Question** [comment]
In other words, the container port must specify 3000 and 3001, and the external port is optional, right?

**Comment by TARS-Question** [comment]
也就是说，容器端口必须指定3000  和3001，外部端口随意，是吗？

**Comment by TARS-Answer** [comment]
Yes, unless you change the configuration of tarsweb. However, it is best not to modify the port number. If the login jump address is written dead in the configuration file of the web project and the port number of the login service is changed, the login jump will fail.

**Comment by TARS-Answer** [comment]
对，除非你改tarsweb的配置。不过最好是不要修改端口号，web 项目里配置文件中写死了登录跳转地址，改了登录服务的端口号，登录跳转会失败。

**Comment by TARS-Question** [comment]
Is the node port limited?

**Comment by TARS-Question** [comment]
那node节点端口有限制吗？

**Comment by TARS-Answer** [comment]
No.

**Comment by TARS-Answer** [comment]
没有。
