### ISSUE TITLE
Where is the entry point for this property report?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#754]
> ![#754(1)](https://user-images.githubusercontent.com/66677505/88412883-cfd51880-ce0c-11ea-9686-c0085338e820.jpg)

> ![#754(2)](https://user-images.githubusercontent.com/66677505/88412886-d06daf00-ce0c-11ea-92ae-fa5a751d1dec.jpg)

**Comment by TARS-Answer** [comment]
The interface is here to view. (see note figure)

https://tarscloud.github.io/TarsDocs/dev/tarscpp/tars-guide.html

Report can see here 12. Attribute statistics.
![QQ图片20200725094633](https://user-images.githubusercontent.com/66677645/88446336-c757fe80-ce5b-11ea-95d6-8f7801ad5ef6.png)

**Comment by TARS-Answer** [comment]
界面上是这里可以查看。(见备注图)
https://tarscloud.github.io/TarsDocs/dev/tarscpp/tars-guide.html
上报可以看看这里12.属性统计。
![QQ图片20200725094633](https://user-images.githubusercontent.com/66677645/88446352-e22a7300-ce5b-11ea-93b7-d7d21a61af10.png)
