### ISSUE TITLE
I don't understand the gateway document. What is the format of the content to be transmitted? Where is the basepacket? 

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#756]
> ![#756](https://user-images.githubusercontent.com/66677505/88413129-3c501780-ce0d-11ea-98e6-65e951b71d9d.jpg)

**Comment by TARS-Answer** [comment]
生成的插件里面要处理一下这个节点，example Server里面，要把这个节点改成true，重新生成servsant发布服务即可，你拿的hello的example，这个标签是false。(图三)

**Comment by TARS-Answer** [comment]
这个意思是说当你使用这个tup proxy的时候，在客户端请求的时候，需要自己把tarsObject序列化成二进制，放到Body中做转发。一般的场景并不会用到。核心且实用的功能，是json的模式。

**Comment by TARS-Question** [comment]
In what scenarios will tup proxy be used?

**Comment by TARS-Question** [comment]
tup proxy在什么场景下会用到？

**Comment by TARS-Answer** [comment]
tup can use this mode when your IOS or Android serialization scenario uses the tar protocol. The benefits and choices depend on your business scenario and the employees' grasp of the overall project. After all, this part requires IOS & Android development engineers to be familiar with this part of the resolution protocol.

The core point is still JSON as the RPC transport protocol, or the tar stream as the RPC transport protocol. Their role in the forwarding service is equivalent, so is the scenario used.

Generally speaking, it is recommended to use JSON for gateway users. In the future, the JSON coming in from the gateway will be dyed directly on the web. You will see the call chain and parameters of the complete gateway. After using JSON, you can configure and dye some.

**Comment by TARS-Answer** [comment]
tup在你的ios OR android的序列化场景使用的是tars协议的时候，可以使用这种模式。收益和选择看你的业务场景和员工对整体工程的把握，毕竟这一部分需要ios&& android的开发的工程师也熟悉这一部分的解析协议。
核心点还是json作为Rpc传输协议，还是tars流作为rpc传输协议，他们的作用在转发服务中是对等的，使用的场景也是如此。
总体而言，建议走网关的用json，后续，会在web上直接对网关进来的json做染色，会看到完整网关进来的调用链和参数，用json后面好配置染色一些。

**Comment by TARS-Question** [comment]
How do I access the HTTP proxy in the gateway as shown in the figure above? I tried http://127.0.0.1 : gateway port / testhost is 404.

> ![#756(2)](https://user-images.githubusercontent.com/66677505/88828672-26bc6280-d1fe-11ea-8208-8421ce6ffd6f.jpg)

**Comment by TARS-Question** [comment]
在gateway像上图那样配置http代理， 要怎么访问？我试了下 http://127.0.0.1:gateway端口/testhost，是404。

> ![#756(2)](https://user-images.githubusercontent.com/66677505/88828701-2fad3400-d1fe-11ea-9a19-6c5bf4dd2fa6.jpg)
