### ISSUE TITLE
If I use the HTTP website deployed by tars, how can I configure the domain name pointing? Do I still need nginx to forward it?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#757]
> ![#757](https://user-images.githubusercontent.com/66677505/88480108-8c9eb500-cf86-11ea-9ffe-136c02c30f76.png)

**Comment by TARS-Answer** [comment]
Just add nginx in front of the gateway, and nginx is not needed for forwarding. You can use tars that gateway directly.

**Comment by TARS-Answer** [comment]
在网关前加nginx就可以了，不需要nginx进行转发。可以直接用tars那个网关。
