### ISSUE TITLE
When deploying a cluster, can I use keepalived + multiple Tars gateway servers?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#760]

**Comment by TARS-Answer** [comment]
If it is deployed on Tencent Cloud or the like, just go to the gateway via slb. If you deploy by yourself, the gateway is deployed on the external network and the domain name can be directly resolved.

**Comment by TARS-Answer** [comment]
如果是部署在腾讯云之类的, 通过slb转到网关就可以了。如果是自己部署, 网关部署在外网, 域名直接解析即可。
