### ISSUE TITLE
If nodes are distributed on various physical machines, some problems may be encountered during actual use.

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#761]
> For example, if multiple services are deployed on a node, there may be java, php, and go. Once one of the services is abnormal, such as If the CPU is used up, other services will also be affected. Is there any way to avoid this situation?

**Comment by TARS-Answer** [comment]
In theory, as long as multiple services are deployed on the same node, this kind of problem cannot be avoided. It is recommended to improve your monitoring and give early warning in time. Normally, each service is backed up at multiple points. Even if a server is really down, there will be no impact. It can also be solved with docker, k8s and the like, one docker for each service, limit it.

**Comment by TARS-Answer** [comment]
理论上来说，只要是多个服务部署在同一个节点，这种问题就避免不了。建议完善你的监控，及时预警。正常来说每个服务都是多点备份的，就算一台服务器真的宕机了，也不会有什么影响。用docker, k8s之类的也可以解决的, 每个服务一个docker, 限制一下。
