### ISSUE TITLE
  The relative path used in the code was originally started by its own script, which is a relative path. After taking it, the code in the project can't find the root directory of the service, so an error is reported. What's the matter? (see below for details)

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#763]
- Put the generated tars_ start.sh After the script content is copied, it is OK to start in the foreground, but click start on the page, and a configuration file (not tarsconfig configuration, but local) in the project is not loaded.

- See the document for configuration

> java -Dconfig=/usr/local/app/tars/tarsnode/data/TestApp.VertxHelloServer/conf/TestApp.VertxHelloServer.config.conf -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Xms2000m -Xmx2000m -Xmn1000m -Xss1000k -XX:CMSInitiatingOccupancyFraction=60 -XX:+CMSParallelRemarkEnabled -XX:+CMSScavengeBeforeRemark -verbosegc -XX:+PrintGCDetails -XX:ErrorFile=/usr/local/app/tars/app_log//TestApp/VertxHelloServer/jvm_error.log -Xbootclasspath/a:/usr/local/app/tars/tarsnode/data/TestApp.VertxHelloServer/bin/conf -cp /usr/local/app/tars/tarsnode/data/TestApp.VertxHelloServer/bin//classes:/usr/local/app/tars/tarsnode/data/TestApp.VertxHelloServer/bin//lib/* com.qq.tars.server.startup.Main
> 
> 
> 
> -Xbootclasspath/a:/usr/local/app/tars/tarsnode/data/TestApp.VertxHelloServer/bin/conf
> 
> 
> 
> 直接执行java -Dconfig=/usr/local/app/tars/tarsnode/data/TestApp.VertxHelloServer/conf/TestApp.VertxHelloServer.config.conf -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Xms2000m -Xmx2000m -Xmn1000m -Xss1000k -XX:CMSInitiatingOccupancyFraction=60 -XX:+CMSParallelRemarkEnabled -XX:+CMSScavengeBeforeRemark -verbosegc -XX:+PrintGCDetails -XX:ErrorFile=/usr/local/app/tars/app_log//TestApp/VertxHelloServer/jvm_error.log -Xbootclasspath/a:/usr/local/app/tars/tarsnode/data/TestApp.VertxHelloServer/bin/conf -cp /usr/local/app/tars/tarsnode/data/TestApp.VertxHelloServer/bin//classes:/usr/local/app/tars/tarsnode/data/TestApp.VertxHelloServer/bin//lib/* com.qq.tars.server.startup.Main 就可以把程序正常启动起来 在页面上点击就启动不起来 错误日志提示 我的/usr/local/app/tars/tarsnode/data/TestApp.VertxHelloServer/bin/conf中的一个配置文件找不到
>

**Comment by TARS-Answer** [comment]
Restart the tarsnode. I think it's still necessary to think about the business code.

**Comment by TARS-Answer** [comment]
把tarsnode重启一下，估计还是得业务代码上想想办法。
