### ISSUE TITLE
  I want to publish a service, a demo Hello world service, and the server is ready to write it in go. But there are three questions I don't understand.

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#764]
> The tars I just used, and Docker. The main control is on 172.25.0.3. 172.25.0.4 is node1 and 172.25.0.5 is node2.
> 
> .3 mapped out 3000,3001.
> .4 mapped out 9000-9010 to host 9000-9010
> .5 maps out 9010-9020 to 9010-9020 of the host.

- Q1. Choose tars.default or tars.go.default for the template? The picture in the document is tars.default.

- Q2. Can the selected node be .3? Still can only choose .4 or .5?

- Q3. The port to which OBJ is bound must be between 9000-9010 or 9010-9020, or can it be random, for example 17874?

**Comment by TARS-Answer** [comment]
-  A1. Templates are fine, no difference

- A2. Go services can be published

- A3. If docker is in host mode, the port can be unmapped or random.

**Comment by TARS-Answer** [comment]
- A1. 模板都可以，没区别

- A2. go的服务都可以发布 

- A3. docker如果是host模式的,端口可以不用映射，也可以随机。
