### ISSUE TITLE
After I restart, there is no web and system under PM2 list. What is the reason?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#768]
> ![#768](https://user-images.githubusercontent.com/66677505/88805397-b0116c00-d1e1-11ea-90b7-4d60dd90fd45.jpg)

**Comment by TARS-Answer** [comment]
Look at the output warm log. If the saved list is not synchronized, enter the command according to the prompt.

**Comment by TARS-Answer** [comment]
看输出的warm日志，没有同步saved list，按照提示输入命令试试。
