### ISSUE TITLE
As shown in the figure, in the production environment deployment, can the service node and application node be placed on the same server?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#769]
> ![#769](https://user-images.githubusercontent.com/66677505/88827883-15268b00-d1fd-11ea-8353-49c7c3960bd7.png)

**Comment by TARS-Answer** [comment]
No, the production environment usually uses net=host mode.

**Comment by TARS-Answer** [comment]
不能 ，生产环境通常用net=host模式。
