### ISSUE TITLE
The result of the request on the server is shown in the figure. , May I ask what may cause it?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#771]
- After installing the framework through docker on the server, port 3001 can be accessed and the password is reset after success. Later, when the gateway is installed to generate the token, it is found that 3001 cannot be accessed. 3000 can be accessed normally.

> ![#771(1)](https://user-images.githubusercontent.com/66677505/88828129-59b22680-d1fd-11ea-831f-c8c7b28f6ad1.png)

> ![#771(2)](https://user-images.githubusercontent.com/66677505/88828135-5ae35380-d1fd-11ea-848b-4739e6a20911.png)

**Comment by TARS-Answer** [comment]
Just use 3000, because the latest version is merged into one port.

**Comment by TARS-Answer** [comment]
就用3000，因为最新版本合并成一个端口了。
