### ISSUE TITLE
As shown in the figure, what is this mechanism?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#773]
> ![#773](https://user-images.githubusercontent.com/66677505/89052374-31a2fe80-d388-11ea-8356-c7838071bd13.png)

**Comment by TARS-Answer** [comment]
The self-start detection after down, that is, the frequency protection is pulled up after the program hangs.

**Comment by TARS-Answer** [comment]
down之后的自启检测，也就是程序挂了之后拉起做个频率保护。
