### ISSUE TITLE
As shown in the figure, I have configured the tracing configuration in the tars-java template and started a zipkin server, but found that the data is not reported to zipkin. What could be the reason?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#774]
> ![#774](https://user-images.githubusercontent.com/66677505/89052515-6747e780-d388-11ea-828b-aa344a1d98ac.png)

**Comment by TARS-Answer** [comment]
After configuration, you can check if there are corresponding zipkin logs when zipkin and local requests are made. If not, it means the configuration was unsuccessful.

**Comment by TARS-Answer** [comment]
可以在配置好后，看一下zipkin和本地的请求的时候 ，有没有对应的zipkin的日志。若是没有的话，就表示配置不成功。
