### ISSUE TITLE
In Application.cpp, why should an AdminObj be set?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#775]
> ![#775](https://user-images.githubusercontent.com/66677505/89052652-99f1e000-d388-11ea-9727-250094cef3d8.png)

**Comment by TARS-Answer** [comment]
This is the management port of the service, used by tarsnode.

**Comment by TARS-Answer** [comment]
这是服务的管理端口, 给tarsnode用的。
