### ISSUE TITLE
When the Internet machine is migrated and the IP and port of the target obj are modified, will tars stringtoproxy get the new address immediately? How is this synchronized?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#778]

**Comment by TARS-Answer** [comment]
It needs to be migrated to a machine where tarsnode has been deployed. When the client requests it, it will first request the service address stored in the cache. If it is not available, it will obtain the update service address from the registry and then request the service.

**Comment by TARS-Answer** [comment]
需要迁移到已经部署tarsnode的机器上，客户端请求时会优先请求缓存中保存的服务地址，不可用时从注册中心获取更新服务的地址，再请求服务。
