### ISSUE TITLE
Tars has been created in k8s. What can I do to let the Internet access the services inside?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#779]

**Comment by TARS-Answer** [comment]
This involves the use of k8s. Exposing applications in k8s to the Internet can be achieved by exposing pod or service. You can find related implementation methods by yourself and choose the implementation method that suits you.

**Comment by TARS-Answer** [comment]
这个就涉及到k8s使用的问题了，向外网暴露k8s中的应用，可以通过暴露pod或者是service等实现，可以自行查找相关实现方法，选择适合自己的实现方式
