### ISSUE TITLE
一些文本错误和不明确的地方

### ISSUE THREAD

**Issue by cmjzzx** [TarsCloud/Tars#78]
1. Java 用户指南文档里的set方式调用这一节的

    > 因此框架则按set部署的基础上增加了客户端可以指定set名称去调用业务服务的功能

    应该是“因此框架**在**按set部署的基础上……”吧
2. Java 用户指南文档里的业务配置这一节的

    > 服务在启动通过在注册监听器里面加载到服务conf目录

    这句话怎么理解？
3. API 文档中的服务配置新增配置文件的参数注释
  
    > "set_area": "",     // Set取

    应该是Set区

**Comment by loveyacper** [comment]
非常细心的指出了文档中的文笔问题或错别字，我们修改下文档。
