### ISSUE TITLE
What does the load here mean?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#780]
Why some display 0, some display 1, did not make relevant choices during installation. 

> ![#780](https://user-images.githubusercontent.com/66677505/89114995-45984e80-d4b5-11ea-9eed-69654ba8e633.png)

**Comment by TARS-Answer** [comment]
This is the load load of the machine. It is only displayed for the moment, it has no effect

**Comment by TARS-Answer** [comment]
这是机器的负载load，目前只是显示看看, 无作用
