### ISSUE TITLE
How do I set the timeout period of TARS microservice call?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#781]

**Comment by TARS-Answer** [comment]
It can be set in the template, or prx in the code can be configured.

**Comment by TARS-Answer** [comment]
模板里面可以设置，或者代码里面prx有函数可以配置。

**Comment by TARS-Question** [comment]
Is the value on this page shown in the picture?

> ![#781(1)](https://user-images.githubusercontent.com/66677505/89140111-42639800-d573-11ea-916d-f4d727cf7c9e.png)

**Comment by TARS-Question** [comment]
如图是这个页面的值吗？

> ![#781(1)](https://user-images.githubusercontent.com/66677505/89140123-4d1e2d00-d573-11ea-8791-42f257eee631.png)

**Comment by TARS-Answer** [comment]
No, it is configured in the template.

**Comment by TARS-Answer** [comment]
不是，是在模板里面配置的。

**Comment by TARS-Question** [comment]
Which field is configured in the figure below?

> ![#781(2)](https://user-images.githubusercontent.com/66677505/89723256-68cb7c80-da26-11ea-9817-cdabda3faed9.png)

**Comment by TARS-Question** [comment]
是在下图哪个字段配置的？

> ![#781(2)](https://user-images.githubusercontent.com/66677505/89723260-754fd500-da26-11ea-917a-b2b78225c83e.png)

**Comment by TARS-Answer** [comment]
In the client domain.

**Comment by TARS-Answer** [comment]
client域内。
