### ISSUE TITLE
Getting started with HelloGo, the execution file here does not specify the ip and port in the previous code, what is the use?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#782]
> ![#782](https://user-images.githubusercontent.com/66677505/89140181-7474fa00-d573-11ea-8965-f6ef687bcb55.png)

**Comment by TARS-Answer** [comment]
The make & make tar command in the example executes compilation and packaging, first compiling and then packaging. The executable file is generated during the compilation phase, and the file is added to the release package during the packaging phase. Therefore, the executable file is the file generated during the intermediate phase of the command. It can also be used for debugging. In general, the service code does not specify the IP and port, but is specified when publishing the service through TarsWeb.

**Comment by TARS-Answer** [comment]
示例中的make & make tar命令执行编译和打包，先编译再打包，可执行文件是编译阶段生成的，打包阶段会将文件加入发布包，因此可执行文件是命令中间阶段生成的文件，可以不予理会，也可用于调试。一般情况下服务代码不会指定IP和端口，而是通过TarsWeb发布服务时指定的。
