### ISSUE TITLE
How do I see the version of the TARS framework currently used in the system?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#783]

**Comment by TARS-Answer** [comment]
There is currently no direct way to view it. You can see the version of TarsWeb on the TarsWeb management page. If necessary, you can view the current git commit record through git log, and find the corresponding version on GitHub

**Comment by TARS-Answer** [comment]
目前没有直接查看的方式，TarsWeb管理页面可以看到TarsWeb的版本。如若需要可以通过git log查看当前的git提交记录，在GitHub上找到对应版本
