### ISSUE TITLE
What is the reason for this prompt after login? 

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#784]
The previously deployed business can run up, and today I want to redeploy this problem on another one. 

> ![#784](https://user-images.githubusercontent.com/66677505/89238415-941a2a00-d628-11ea-98bd-ba5aeb13504a.png)

Refreshing or logging out will not work, and it still prompts that you are not logged in.

**Comment by TARS-Answer** [comment]
It may be a bug that the ticket returned in the user module is undefined. The latest version of TarsWeb has fixed this problem. You can try to upgrade TarsWeb to solve this problem.

**Comment by TARS-Answer** [comment]
可能是用户模块中返回的ticket为undefined的bug，最新版的TarsWeb已经修复这个问题，可以尝试升级TarsWeb解决这个问题。
