### ISSUE TITLE
能否升级tars-php-server的依赖库

### ISSUE THREAD

**Issue by lizcao** [TarsCloud/Tars#785]
### What language are you using?
 PHP
 
### What operating system (Linux, Ubuntu, …) and version?
 Centos
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 gcc
 
能否升级tars-php-server的依赖库，
我尝试安装illuminate/database的时候  也只能安装5.x的因为它依赖tars_server的这两个库  但安装illuminate/database5.x的时候提示有相关的库已经废弃 建议安装高版本的
https://packagist.org/packages/phptars/tars-server

![image](https://user-images.githubusercontent.com/65020767/89258868-9ea1e700-d65b-11ea-8fd9-5be55cb2949a.png)

**Comment by dpp2009** [comment]
升级下版本
