### ISSUE TITLE
Tars cpp2. X is on the node side. The script command to manually stop the service is?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#788]
Remote login, not convenient to stop with the web.

**Comment by TARS-Answer** [comment]
There is no way to manually kill it as long as the tarsnode node is still there and the node service status is active, the service will continue to be pulled. In the source code implementation, only the stopServer that calls the node node will set the service status to inactive.

**Comment by TARS-Answer** [comment]
没有办法，手动kill掉只要tarsnode节点还在，并且节点服务状态为active，就会一直拉起服务。源码实现中，只有调用node节点的stopServer才会将服务状态设置为inactive。
