### ISSUE TITLE
Tars cpp2. X is on the node side. The script command to manually stop the service is? Remote login, not convenient to stop with the web.

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#789]

**Comment by TARS-Answer** [comment]
The first parameter of the install.sh installation script is the host address of TarsWeb, which needs to include the port, that is, ip:port, such as 1.2.3.4:3000. Only entering the IP will not call the relevant interface. Shows that the installation is successful is a problem with the current installation script, which will be repaired later.

**Comment by TARS-Answer** [comment]
install.sh安装脚本的第一个参数为TarsWeb的host地址，需要包含端口，即ip:port，例如1.2.3.4:3000，只输入IP会无法调用相关接口。显示安装成功是目前安装脚本存在的问题，后期会进行修复。
