### ISSUE TITLE
  Why is there no web and system under PM2 list after restart?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#792]
> - Attachment: CMD log command PM2 list
> 
> [PM2][WARN] Current process list running is not in sync with saved list. tars-node-web tars-user-system differs. Type 'pm2 save' to synchronize.

**Comment by TARS-Answer** [comment]
Follow the WARN log output by cmd. The reason is that the currently running process list is not synchronized with the saved list. Just enter pm2 save as prompted in the log.

**Comment by TARS-Answer** [comment]
按照cmd输出的WARN日志，原因是当前运行的进程列表没有和已保存的列表同步，按照日志中的提示输入pm2 save即可
