### ISSUE TITLE
Does this koa need to be downloaded separately? Or where did I put it wrong?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#794]
- The previous 2.1 web did not have this problem.

> ![#794(1)](https://user-images.githubusercontent.com/66677505/89475273-50572a00-d7ba-11ea-80e9-e72915f97c1d.jpg)

**Comment by TARS-Answer** [comment]
It seems that the uploading and publishing interface of tarsweb is not verified, and the service can be successfully published without a token.
![QQ图片20200809094916](https://user-images.githubusercontent.com/66677645/89723192-abd92000-da25-11ea-9555-4710837e0870.jpg)

**Comment by TARS-Answer** [comment]
TarsWeb的上传发布接口好像没有做验证，没有带token也能成功发布服务。(见备注图)
![QQ图片20200809094916](https://user-images.githubusercontent.com/66677645/89723204-c3180d80-da25-11ea-9c5c-3349b238c4a4.jpg)
