### ISSUE TITLE
TARS_ CLIENT_ Where can logger be configured to turn off?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#795]

**Comment by TARS-Answer** [comment]
Define the corresponding path in logback and modify the log level.

Or in the <  logger name = tars_ CLIENT_ LOGGER" level="ERROR" >

< appender-ref ref="client_ logger"/  >

It is also OK after <  / logger  >.

Similar to other Dao layers. If you need mybatis log and other operations. The output can be modified or not according to the package path or loggername.

This log and log4j are basically consistent with other log controllers

1. The log output level can be customized for a package path

2. You can customize the log output level for loggername

**Comment by TARS-Answer** [comment]
在logback中定义对应的路径修改日志的等级即可。
或者在    <logger name="TARS_CLIENT_LOGGER" level="ERROR">
        <appender-ref ref="client_logger"/>
    </logger>后也是可以的。
类似操作其他的dao层一样。若是需要Mybatis的日志等操作。也是按这样的package 路径 或者loggername来修改输出或者不输出。
这个日志和Log4j与其他的日志控制器基本一致的
1、 可以针对某个package路径统一定制日志输出等级
2、 可以针对loggerName来定制日志的输出等级
