### ISSUE TITLE
What should I do if the installation and release prompt timed out? 

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#797]
- The docker version is Version: 2.1.0.

> ![#797](https://user-images.githubusercontent.com/66677505/89595154-603c4000-d886-11ea-8ec0-68a48230c220.png)

**Comment by TARS-Answer** [comment]
The version is too low. Use version 2.4.5. It is recommended to update to tarscloud/framework:v2.4.5.

**Comment by TARS-Answer** [comment]
版本太低了, 用2.4.5版本，建议更新至tarscloud/framework:v2.4.5。
