### ISSUE TITLE
服务列表状态inactive问题

### ISSUE THREAD

**Issue by WhatDream** [TarsCloud/Tars#80]
我跑得是PromiseDemo的代码，编译打包AServer、BServer、CServer之后，在web系统上发布，三个包都无法active
![image](https://user-images.githubusercontent.com/15125028/29309320-c2b4a3d0-81db-11e7-8f63-97325d7612b8.png)
exit: [TARS]ServantHelperManager::addServant PromiseDemo.AServer.AServantObj not find adapter.(maybe not conf in the web)
![image](https://user-images.githubusercontent.com/15125028/29309340-d8142a84-81db-11e7-9692-04b8d11e5333.png)

**Comment by loveyacper** [comment]
PromiseDemo.AServer.AServantObj
检查一下是不是名字写错了，特别注意是否有Adapter后缀。
