### ISSUE TITLE
  Why is there no demo in tarsweb? What's going on in the directory?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#800]
Tip: 2020-08-05 18:06:22 mysql is alive
cp: Unable to get the file status of "/data/app/tars/cpp/deploy/web/demo/sql/*.sql" (stat): No such file or directory
  2020-08-05 18:06:22 mysql version is: 5.7.29-log,

**Comment by TARS-Answer** [comment]
It needs to cooperate with the latest version of the framework. The new version of the demo directory is gone, and the web provides a port and service externally.

**Comment by TARS-Answer** [comment]
需要配合最新版的framework，demo目录新版本没有了, web对外就提供一个端口和服务。
