### ISSUE TITLE
In the tars management background to modify the replacement template, is it possible to manually modify the template file for the previously added micro server to take effect?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#801]
> ![#801(1)](https://user-images.githubusercontent.com/66677505/89595525-5535df80-d887-11ea-91a4-cb72dd3fda71.png)

> ![#801(2)](https://user-images.githubusercontent.com/66677505/89595527-56670c80-d887-11ea-8c42-77e3660086ad.png)

> ![#801(3)](https://user-images.githubusercontent.com/66677505/89595537-58c96680-d887-11ea-96fa-554e63987ae5.png)

**Comment by TARS-Answer** [comment]
Try restarting, it should be regenerated after restarting.

**Comment by TARS-Answer** [comment]
尝试重启，重启了就应该重新生成了的。
