### ISSUE TITLE
The swoole extension has been installed, and the PHP execution path in the template has been changed. What is the following prompt?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#802]
> ![#802(1)](https://user-images.githubusercontent.com/66677505/89595682-c2e20b80-d887-11ea-851a-9f6eba98a1e9.png)

> ![#802(2)](https://user-images.githubusercontent.com/66677505/89595684-c4133880-d887-11ea-918a-ab648fa18383.png)

**Comment by TARS-Answer** [comment]
Check whether there are multiple PHP versions on the server. This is generally the reason.

**Comment by TARS-Answer** [comment]
查看服务器上是否有多个PHP版本，一般都是这个原因。

**Comment by TARS-Question** [comment]
But the PHP execution path of the template has been modified, why is another one executed?

**Comment by TARS-Question** [comment]
可是模板的php执行路径已经修改了，为什么执行了另一个？

**Comment by TARS-Answer** [comment]
Check the startup script and the php execution path in the configuration sent to the node node, and the modified template may not be synchronized.

**Comment by TARS-Answer** [comment]
查看启动脚本和发到node节点的配置里的php执行路径，可能改的模板并没有同步过来。
