### ISSUE TITLE
What could be the cause of the error as shown in the figure?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#804]
> ![#804](https://user-images.githubusercontent.com/66677505/89699765-ac0ce900-d95b-11ea-9eaf-6ce856ec4cd2.png)

- Error log:

```
|ERROR|[TARS][ObjectProxy::doTimeout, objname:tars.tarsstat.StatObj, queue timeout error]
|ERROR|[TARS][ObjectProxy::doTimeout, objname:tars.tarsstat.StatObj, queue timeout error]
|ERROR|[TARS][ObjectProxy::doTimeout, objname:tars.tarsproperty.PropertyObj, queue timeout error]
```

**Comment by TARS-Answer** [comment]
The request timeout for Stat and Property is shown here, and the restart result is null for the query node. Maybe the Query node is suspended and you can try to restart the TARS framework

**Comment by TARS-Answer** [comment]
这里显示Stat和Property的请求超时，重启结果报错为query节点null，可能是query节点挂了，可以尝试重启TARS框架
