### ISSUE TITLE
Is the error reported as shown in the figure a configuration problem?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#805]
> ![#805](https://user-images.githubusercontent.com/66677505/89699798-fc844680-d95b-11ea-8f33-72b1da8b40f5.png)

**Comment by TARS-Answer** [comment]
There may be many reasons why active nodes cannot be found based on the error message for the Query node. The information in the figure is not enough to tell. You can look at the relevant logs or try to reinstall the TARS framework.

**Comment by TARS-Answer** [comment]
根据报错信息为query节点无法找到active的节点，可能原因很多，图中的信息不足以判断，可以看看相关日志，或者尝试重新安装TARS框架。
