### ISSUE TITLE
  Do I need to write UI display for the data reported by PP monitoring function?

### ISSUE THREAD

**Issue by TARS-Question** [TarsCloud/Tars#807]
- What effect can be achieved by reporting PP?

**Comment by TARS-Answer** [comment]
You can report a value, which will be displayed on the UI. There can be several algorithms such as summation and average. There is a display on the tars native page.

**Comment by TARS-Answer** [comment]
可以上报一个数值, ui上会展示这个数值, 可以有求和, 平均等几种算法。在tars 原生的页面有展示。

**Comment by TARS-Answer** [comment]
Feature monitoring.

**Comment by TARS-Question** [comment]
Only service monitoring and feature monitoring can be seen on the page. Which page is displayed?

**Comment by TARS-Question** [comment]
在页面上只看到服务监控和特性监控，是在哪个页面展示呢？

**Comment by TARS-Answer** [comment]
Feature monitoring.

**Comment by TARS-Answer** [comment]
就是特性监控。
