### ISSUE TITLE
web部署的服务名称可以用“-”分隔符吗？

### ISSUE THREAD

**Issue by liulinghao0421** [TarsCloud/Tars#811]
![无标题](https://user-images.githubusercontent.com/67670474/91548149-891c9600-e957-11ea-9067-457798eccd19.png)

web的服务名称可以用“-”分割符呢，如果使用了分隔符，除了界面上的输入限制，其他的代码处还有没有添加关于分割符的限制呢？

**Comment by ruanshudong** [comment]
建议还是别用特殊字符

**Comment by liulinghao0421** [comment]
好的，谢谢
