### ISSUE TITLE
加密算法

### ISSUE THREAD

**Issue by liulinghao0421** [TarsCloud/Tars#822]
### What language are you using?
 
 c++
### What operating system (Linux, Ubuntu, …) and version?
 
 Linux
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 gcc
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

大佬，请教一下，tars框架对协议加密，推荐用什么算法啊，客户端是c#，tars框架我看到有提供算法，但是没有对应的c#版本，

**Comment by ruanshudong** [comment]
cpp里面算法都是标准的, 你找个c#标准的匹配算法, 就可以用啊, des啥的

**Comment by liulinghao0421** [comment]
好的，搞定了，谢谢大佬
