### ISSUE TITLE
web后台服务部署

### ISSUE THREAD

**Issue by liulinghao0421** [TarsCloud/Tars#827]
### What language are you using?
 
 c++
### What operating system (Linux, Ubuntu, …) and version?
 
 linux
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 gcc
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
请教一下大佬，我这边可能有十个服务，这十个服务都是同样的功能，只是服务名称不一致，比如说是game1,game2,game3,....game10,执行文件都是同一个，起得是负载的作用，但是在后台的发布部署的时候我看到上传的发布包名称必须和服务名称一样，这样是不是说如果我有十个服务，功能一样，只是服务名不一样，那也必须打包十个不同的对应服务名的发布包呢，再一个一个上传，这样就有点太麻烦了，请教一下有没有什么解决方案呢？如果我十个服务都用同一个发布包进行发布，后台就会报错，
![error](https://user-images.githubusercontent.com/67670474/98510707-87981400-229e-11eb-8f90-9b9ff67df40c.png)

>

**Comment by dpp2009** [comment]
相同服务名  配置不同的set就行

**Comment by langxgm** [comment]
web上创建10个应用

**Comment by liulinghao0421** [comment]
> 相同服务名 配置不同的set就行

![image](https://user-images.githubusercontent.com/67670474/98642171-f1c8bb80-2367-11eb-8cd6-2b9220a4d07a.png)
服务名不能相同呢

**Comment by liulinghao0421** [comment]
> web上创建10个应用

建10个应用是可以，这样10个应该要更新时得上传10个发布包，这样太麻烦了，不知道有没有什么更方便的方法呢请教一下？

**Comment by langxgm** [comment]
用命令行上传并发布，写个脚本，一次上传10个
https://tarscloud.github.io/TarsDocs/dev/tars-web-api.html#upload-and-publish

**Comment by liulinghao0421** [comment]
> 用命令行上传并发布，写个脚本，一次上传10个
> https://tarscloud.github.io/TarsDocs/dev/tars-web-api.html#upload-and-publish

![500](https://user-images.githubusercontent.com/67670474/98651705-8ede2100-2375-11eb-8019-0c3fd2ae6afb.png
大佬，我试了一下curl，我这么写的，总提示系统内部错误，我格式不对吗？请教一下，万分感激！！！

**Comment by liulinghao0421** [comment]
> 用命令行上传并发布，写个脚本，一次上传10个
> https://tarscloud.github.io/TarsDocs/dev/tars-web-api.html#upload-and-publish

看到了，谢谢大佬指教！！！万分感激

**Comment by langxgm** [comment]
:stuck_out_tongue_winking_eye:
