### ISSUE TITLE
tarsweb 上装了tarsgateway,可是在网关配置那里没有找到站点配置的按钮

### ISSUE THREAD

**Issue by chengbin223** [TarsCloud/Tars#831]
### What language are you using?
 
 php
### What operating system (Linux, Ubuntu, …) and version?
 centos
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by chengbin223** [comment]
![image](https://user-images.githubusercontent.com/22760715/99784828-55689b00-2b57-11eb-9b6e-f3e7f03d2613.png)

**Comment by dpp2009** [comment]
先添加网关控制服务obj

**Comment by chengbin223** [comment]
> 先添加网关控制服务obj

![image](https://user-images.githubusercontent.com/22760715/99943703-acb37900-2dac-11eb-8c35-6a8b3d7dafe9.png)
