### ISSUE TITLE
网关配置的使用BUG

### ISSUE THREAD

**Issue by chengbin223** [TarsCloud/Tars#832]
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by chengbin223** [comment]
![image](https://user-images.githubusercontent.com/22760715/100061773-86074800-2e69-11eb-80c3-5dce3140f1cf.png)
这里的这个Tars服务我以前设置的，点击删除了，再次添加设置，提示已存在

**Comment by chengbin223** [comment]
![image](https://user-images.githubusercontent.com/22760715/100062499-9c61d380-2e6a-11eb-85dd-cb7fbca7d3b9.png)
该路由下的配置填写提示这个，我是在删除了配置之后，重新添加就会提示这个

**Comment by ruanshudong** [comment]
网关的问题, 最好去网关那个仓库的issue里面问
