### ISSUE TITLE
DCache

### ISSUE THREAD

**Issue by liulinghao0421** [TarsCloud/Tars#833]
### What language are you using?
 
 c++
### What operating system (Linux, Ubuntu, …) and version?
 linux
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
 gcc
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

求教大佬，DCache还有更详细一点的文档吗？总是安装失败，https://github.com/Tencent/DCache/blob/master/docs/install.md  这里的安装还是太粗略

**Comment by ETZhangSX** [comment]
可以参考文章 [DCache 分布式存储系统｜安装部署与应用创建](https://blog.csdn.net/TARSFoundation/article/details/112989775)，后续还会有关于 DCache 如何使用的系列文章更新
