### ISSUE TITLE
Tars web管理平台上传jar包提示“发布包与服务名称不匹配“错误

### ISSUE THREAD

**Issue by zilianglei** [TarsCloud/Tars#834]
![image](https://user-images.githubusercontent.com/24541563/104462418-827f7a00-55eb-11eb-87af-30ab13b97121.png)

**Comment by ruanshudong** [comment]
去掉后面那个时间, 这个问题, 后面优化一下

**Comment by vell001** [comment]
> 去掉后面那个时间, 这个问题, 后面优化一下

遇到了同样的问题，请问具体是怎么处理呢？

**Comment by vell001** [comment]
> > 去掉后面那个时间, 这个问题, 后面优化一下
> 
> 遇到了同样的问题，请问具体是怎么处理呢？

解决了，把包名改成服务名就好了，打扰了

**Comment by dbhuang** [comment]
看了你们的评论都描述有点模糊，
把生成出来的压缩包名字src/HelloServer_20220428081241.tar.gz修改为src/HelloServer.tar.gz
