### ISSUE TITLE
Tars Gateway使用场景

### ISSUE THREAD

**Issue by st-tree** [TarsCloud/Tars#837]
### What language are you using?
 php
 
### What operating system (Linux, Ubuntu, …) and version?
 Linux centos 7
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
能否作为外部调用内部http服务网关，使用网关如何实现修改头信息，token验证等。

**Comment by ETZhangSX** [comment]
TarsGateway 可以让外部服务和客户端通过HTTP调用内部使用tars、json、tarsTup和HTTP协议的服务，具体使用方式可以参考 [Tars网关文档](https://tarscloud.github.io/TarsDocs/SUMMARY.html#gateway)
