### ISSUE TITLE
framework的docker镜像打包后是否包含对应的映射数据?

### ISSUE THREAD

**Issue by harkhuang** [TarsCloud/Tars#841]
使用docker搭建框架的时候, 保持数据库不变, 通过官方的faramwork镜像进行提交后,打包后的镜像文件 , 是否能保存用户提交的tars服务包数据.(未使用docker文件映射)
经过尝试之后,我发现基于镜像打包后的framework中丢失了我之前提交的rpc服务包,请问应该通过什么方式避免这个问题?

# question

```
docker container commit -m "create the 159 copy framework image" -a "hk" 44d1e0444be7 framework:v1
```

**Comment by ruanshudong** [comment]
为什么不映射目录? 映射就是为了保持文件的

**Comment by harkhuang** [comment]
由于dcache建表比较繁琐,想把表结构放到镜像中去,如果把映射文件持久化到打包镜像 部署起来就方便了
