### ISSUE TITLE
DCache稳定性

### ISSUE THREAD

**Issue by liulinghao0421** [TarsCloud/Tars#842]
### What language are you using?
 
 c++
### What operating system (Linux, Ubuntu, …) and version?
 
 Linux
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
 gcc
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

大佬，请问下DCache现在开源版本稳定吗？可以用于生产环境吗？打算接入生产环境DCache

**Comment by ruanshudong** [comment]
普通key-value应该是稳定的

**Comment by liulinghao0421** [comment]
那大佬的意思是搬上生产环境还不太成熟吗？求建议

**Comment by ruanshudong** [comment]
只是使用普通的key-value是没有问题的
