### ISSUE TITLE
配置方案咨询

### ISSUE THREAD

**Issue by wjguo2002** [TarsCloud/Tars#845]
您好：
在我的系统中，规划了三种配置，以定义应用程序运行逻辑，分别是程序启动参数，动态参数，实验参数；

我的问题：
1.在Tars中，没有看到可以定义启动参数的地方，唯一的conf模板，框架在应用自动生成并下发的，我可以自定义吗？

2.服务的配置（目前支持了应用配置，set配置、服务配置和节点配置）但是在我的部署中，添加了配置，但服务没有能动态拉取；
可能是什么原因导致的？
3.有一些离线生成的数据文件需要动态加载，这个框架是如何支持它的？在整个系统中，没有看到数据文件的推送。

**Comment by ruanshudong** [comment]
1 启动参数目前是没有办法控制的
2 拉取配置, 需要在代码中增加addConfig这个调用
3 服务可以监听命令的, 可以通过发送命令给服务来实现文件的动态加载

具体可以参考相关的文档.

**Comment by wjguo2002** [comment]
多谢支持
不知道添加启动参数这个Feature，是否有计划添加
该Feature在很多服务中，还是很重要的。

**Comment by ruanshudong** [comment]
启动参数暂时没计划, 你可以直接放在配置文件中, 没啥太本质的区别

**Comment by wjguo2002** [comment]
我们设计中，引入了插件开发，在刚启动的时候就创建对象了；
而定义的动态参数，是程序运行过程中可以动态更新的，

如果启动参数和动态参数放到一起，每次更新参数都重启的话，代价就要大一些。

这个问题，我已经修改框架，暂时支持了，不过还是希望有官方解决方案。
