### ISSUE TITLE
tarsnode 安装报错，缺少依赖的库

### ISSUE THREAD

**Issue by lanlin** [TarsCloud/Tars#847]
```shell
/lib64/libm.so.6: version `GLIBC_2.29' not found
/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found
```

能不能将依赖的库等放到项目里一起发布出来，安装的时候解决起来太麻烦了

**Comment by lanlin** [comment]
呃...有人在么？
 
现在 tars 都没有维护的么，还是说又变成 KPI 项目了，有知情人么？

我看每个 project 下面都是一堆 2020年的问题都没人回答...

**Comment by ruanshudong** [comment]
你这明显是编译环境和服务器环境stdc++版本不一致导致, 和tarsnode有啥关系

**Comment by lanlin** [comment]
是的，的确是我环境的问题，已经解决，谢谢。

框架服务是用的官方的docker化部署，业务节点是用的自己的镜像，然后节点注册是参考的 tarsdocker 里的
https://github.com/TarsCloud/TarsDocker/blob/master/tarsnode/php/entrypoint.sh

记得好像就是这个脚本执行节点注册时提示的库依赖问题，记不太清了，好像这个脚本会去框架节点下载一个包，这个包里面的某个地方貌似有依赖到

**Comment by helloHKTK** [comment]
> ```shell
> /lib64/libm.so.6: version `GLIBC_2.29' not found
> /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found
> ```
> 
> 能不能将依赖的库等放到项目里一起发布出来，安装的时候解决起来太麻烦了

请问怎么解决的？
