### ISSUE TITLE
./linux-install.sh 报错

### ISSUE THREAD

**Issue by micalliu** [TarsCloud/Tars#856]
在安装./linux-install.sh的时候报错，mysql的用户名密码都是正确的，提示错误如下：
exec mysql parameter: [charset]=[utf8]|[host]=[172.16.0.110]|[pass]=[*****]|[port]=[*****]|[sql]=[grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICAT
ION CLIENT, CREATE VIEW, SHOW VIEW, CREATE USER on *.* to 'tarsAdmin'@'%' identified by 'Tars@2019' with grant option;]|[user]=[admin]error: [TC_Mysql::execute]: mysql_query: [ grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE USER on *.* to 
'tarsAdmin'@'%' identified by 'Tars@2019' with grant option; ] :Proxy ERROR:Sanity error: do not support sql relate to privileges,use chitu 2021-07-20 17:57:15 exec_mysql_script grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE USER on *.* to 'tar
sAdmin'@'%' identified by 'Tars@2019' with grant option;, ret code: 255  2021-07-20 17:57:15 grant error, exit.

**Comment by bartdong** [comment]
这个是MySQL用户赋权失败的提示，建议单独处理MySQL用户的权限后继续安装。
This is a notice of the failure of MySQL user grant privilege. It is recommended to deal with the permissions of MySQL users before continuing with the installation.
