### ISSUE TITLE
问下tars目前如何支持后台C#开发的服务呢?

### ISSUE THREAD

**Issue by ramosyang** [TarsCloud/Tars#88]

**Comment by loveyacper** [comment]
使用tars客户端访问已有的C#后台服务吗？
使用addServantProtocol函数在tars客户端设置你的协议编解码函数即可；
使用rpc_call函数发起调用。（tars协议是使用tars_invoke）

**Comment by ElderJames** [comment]
https://github.com/tarsnet 支持C#的开发工作已经开始
