### ISSUE TITLE
tars框架里面可以部署异构服务吗？ 

### ISSUE THREAD

**Issue by ramosyang** [TarsCloud/Tars#89]
即非tars协议，而且也没有实现里面的doRequest之类的，只需指定一个ip+port，因为我的服务已经在tomcat上跑起来了，不想对那个服务做改动

**Comment by helloopenworld** [comment]
可以，需要在taf平台上设置异构服务的启动脚本和停止脚本。

**Comment by kikoroc** [comment]
@helloopenworld  你好，在tars后台上设置了启动和停止脚本，能正常启动服务，但是因为是异构服务，没有上报keepalive信息，导致每隔一分钟就好报“[alarm] zombie process,no keep alive msg for 60 seconds”然后服务被adminreg自动重启，这个问题该如何解决呢？

**Comment by tianking** [comment]
如果是JAVA应用，example里有一个 AppStartListener， 加到工程里让listener运行起来就好了
